### ISSUE TITLE
xml error

### ISSUE THREAD

**Issue by monkeysax** [Kagamia/WzComparerR2#10]
It occurs an error when re-importing after exporting xml with WzCompareR2

Error
---------------------------
The file "C:\Users\a\Desktop\String.Mob.img.xml" is invalid and will be skipped. Error: unknown main XML prop dir
---------------------------

**Comment by Kagamia** [comment]
I'm sorry about that I don't know where you will IMPORT TO.
Does it require a specific file format or xml tag name? If so, you'd better write a custom plugin extension for it. 
Another, WzComparerR2 can extract more stuff than others, like large string, 64bit-integer, dxt3/dxt5 canvas, encrypted sound/binary files, encrypted lua scripts, not all extractors or softwares could be compatible with it.

**Comment by monkeysax** [comment]
thank you
