### ISSUE TITLE
avatar坐騎問題

### ISSUE THREAD

**Issue by s23301955** [Kagamia/WzComparerR2#100]
KMST1076
Character/TamingMob/1983488~1983492
皆有相同問題
動作sit會出現身體
![](https://media.discordapp.net/attachments/503467427942629396/503467480921014283/unknown.png)
手動調整為hidebody照樣會出現身體
![](https://media.discordapp.net/attachments/503467427942629396/503468270435827718/unknown.png)

**Comment by Kagamia** [comment]
该骑宠没有声明hidebody相关的信息，所以无法通过读取wz处理
