### ISSUE TITLE
Comma separators only working for Max HP

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#101]
The comma separator for Max MP is not working.

```
string mpNum = !string.IsNullOrEmpty(MobInfo.FinalMaxMP) ? this.AddCommaSeparators(MobInfo.FinalMaxMP) : MobInfo.MaxMP.ToString();
```

To fix, add "N0" in the parameters for ToString()
```
string mpNum = !string.IsNullOrEmpty(MobInfo.FinalMaxMP) ? this.AddCommaSeparators(MobInfo.FinalMaxMP) : MobInfo.MaxMP.ToString("N0");
```

Values for PADamage, MADamage, and Accuracy could use as well, but they usually go up to 5-6 digits max, so not as big of a priority.

**Comment by Kagamia** [comment]
fixed by https://github.com/Kagamia/WzComparerR2/commit/b3db88125582a293b54a1428a44baa53e1671cee

**Comment by PirateIzzy** [comment]
👍
