### ISSUE TITLE
MaxHP only accounts for up to 2.1 billion

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#102]
The MaxHP stat only goes up to 2.1 billion; any value higher than that is shown as 0.
An example of this is mob ID 8644719, which has a maxHP of 18688692000.

![8644719](https://user-images.githubusercontent.com/34289651/47599850-bfb4ae80-d984-11e8-918a-654d631609a2.png)

To fix this, switch maxHP from an int to a long in LifeInfo.cs and Mob.cs

![8644719 new](https://user-images.githubusercontent.com/34289651/47599873-57b29800-d985-11e8-8e81-01c4ca4cccf1.png)

**Comment by Kagamia** [comment]
fixed by https://github.com/Kagamia/WzComparerR2/commit/b3db88125582a293b54a1428a44baa53e1671cee

**Comment by PirateIzzy** [comment]
👍
