### ISSUE TITLE
cannot use SearchString

### ISSUE THREAD

**Issue by grjsm99** [Kagamia/WzComparerR2#105]
![image](https://user-images.githubusercontent.com/44054161/49529957-857eeb00-f8fa-11e8-9932-4d986e00a224.png)
( translate ) error : open base.wz first. 

i want to use searchstring but i get this error message when i use search

**Comment by KENNYSOFT** [comment]
Which version are you using?

**Comment by KENNYSOFT** [comment]
Right, that's the problem. You can use v3.0.0 now, so please upgrade it.

https://github.com/KENNYSOFT/WzComparerR2/releases

**Comment by grjsm99** [comment]
thanks!
