### ISSUE TITLE
Sound.wz Looping Runs out of Memory

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#109]
Looping any mp3 file in Sound.wz will cause it to run out of memory and break.

I know HaRepacker addressed this and freed the memory after each playback. If you need me to provide an example, I can upload a video.

**Comment by Kagamia** [comment]
I have looped a bgm for a hole day in vs2017 debug mode, but never meet an OOM exception.



![snapshot20190608202912](https://user-images.githubusercontent.com/10445904/59147313-840ab880-8a2c-11e9-989f-0c53802902c1.png)

**Comment by PirateIzzy** [comment]
Strange. It may only occur with certain computers.
