### ISSUE TITLE
plz add select multi rows

### ISSUE THREAD

**Issue by monkeysax** [Kagamia/WzComparerR2#11]
like pressing SHIFT and clicking the mouse
http://cfile211.uf.daum.net/image/261A56375801AE6620F923

plz thank you

**Comment by Kagamia** [comment]
What would you do next after selecting multiple nodes? Extract and view? Or just dump as xml files?
That is really an unusual operation.

**Comment by monkeysax** [comment]
yes i need extract all xml files

that too difficult?

**Comment by Kagamia** [comment]
Not too difficult but makes selection fuzzy, and it makes UI lags.

'Lua Console' plugin is designed for batch jobs.
In this case, I recommend that write a script to do those massy works, like wz 
statistics accounting, or batch export.

If you are not familiar with Lua programming language, wz image dump function would move to WzLib project, and an example will show for you in next commit.

**Comment by KENNYSOFT** [comment]
Oh, could you show me a sample of lua script for batch jobs? I'm also interested in scripting, too.

**Comment by monkeysax** [comment]
thank you

**Comment by Kagamia** [comment]
New version update.
See https://github.com/Kagamia/WzComparerR2/commit/0e96cf7732a1b48bd008117548bb36292e355131

and example https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/Examples/DumpXml.lua

**Comment by monkeysax** [comment]
I added a modified parts and build, but there was no reaction.

**Comment by monkeysax** [comment]
how can fix it?

http://cfile203.uf.daum.net/image/2662CB385806242C21468A
http://cfile229.uf.daum.net/image/247417385806242D0CE9A4

like CS0579  C# Duplicate 'AssemblyTitle' attribute

**Comment by Kagamia** [comment]
See here, from msdn forum. [Compile Error CS0579: Duplicate 'AssemblyVersion' attribute](https://social.msdn.microsoft.com/Forums/en-US/8671bdff-9b16-4b49-ba9e-227cc4df31b2/compile-error-cs0579-duplicate-assemblyversion-attribute?forum=vsgatk)
