### ISSUE TITLE
Avatar: HandleUol enters endless loop

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#111]
(Original issue: https://github.com/KENNYSOFT/WzComparerR2/issues/14)

https://github.com/Kagamia/WzComparerR2/blob/cb060a67409cafb90dc276ad4629b36a3df91090/WzComparerR2.Avatar/AvatarCanvas.cs#L689-L692

Above `while` block causes an endless loop. (Especially in KMS `1012083`, with `hit` face; `hit` -> `blink` -> `default`) It should be changed like below:

```cs
                    while (linkNode?.Value is Wz_Uol) 
                    {
                        linkNode = ((Wz_Uol)linkNode.Value).HandleUol(linkNode); 
                    }
```

The same patch in KMS version repository: https://github.com/KENNYSOFT/WzComparerR2/commit/2b88e5d13856366d3b03a0af07cb98c8ed348bbc

**Comment by Kagamia** [comment]
Good catch! Thanks!
