### ISSUE TITLE
lucid skeleton json file unpacking problem

### ISSUE THREAD

**Issue by maplecircuit** [Kagamia/WzComparerR2#115]
Map.wz/Effect3.img/BossLucid
In this directory, there are some of Lucid skeleton animations.
To set up skeleton animation, it must have texture png, atlas, and json file.
But only this directory(I thought) has some music files instead of json, and their type is binary, not mp3. So it seems to be a problem unpacking json files.
I hope this problem is fixed as soon as possible.

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/62816231-7d94dc00-bb56-11e9-9496-b1f723d8990c.png)

Renders well for my CMST client.

Please select *.atlas node then click ExtractGif button.

**Comment by maplecircuit** [comment]
How to reduce animation size? It can't be extracted if its size is too big.

**Comment by Kagamia** [comment]
Already support customize render size in this commit: https://github.com/Kagamia/WzComparerR2/commit/2cfa1a344f042097bd76f5dd03ee519f9874c9bc
