### ISSUE TITLE
部分技能无法读取

### ISSUE THREAD

**Issue by tzy502** [Kagamia/WzComparerR2#116]
有一些五转技能能搜索的到但是点不开
整个40001地下所有的技能 用的是2.1.1

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/64490753-efb22b00-d292-11e9-89ee-bda2faf9ce88.png)

对于最新的CMST可以正常渲染。请编译最新的wcR2版本。
