### ISSUE TITLE
map.wz Error問題

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#117]
> [Error][MapRender] Coroutine Error: System.AggregateException: 發生一或多項錯誤。 ---> System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
>    於 WzComparerR2.MapRender.FrmMapRender2.LoadBgm(MapData mapData)
>    於 WzComparerR2.MapRender.FrmMapRender2.<LoadMap>d__66.MoveNext()
>    --- 內部例外狀況堆疊追蹤的結尾 ---
> ---> (內部例外狀況 #0) System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
>    於 WzComparerR2.MapRender.FrmMapRender2.LoadBgm(MapData mapData)
>    於 WzComparerR2.MapRender.FrmMapRender2.<LoadMap>d__66.MoveNext()<---

JMS BGM錯誤
867131600.img

![1569475523516](https://user-images.githubusercontent.com/37591855/65660725-285b4e00-e062-11e9-9afd-f2fbb219b45c.jpg)
![1569475760214](https://user-images.githubusercontent.com/37591855/65660726-285b4e00-e062-11e9-8e70-a8ee49170aff.jpg)

**Comment by Kagamia** [comment]
尝试修复。是loadBgm时没有处理uol导致的错误。

因为没有JMS客户端，在CMS和KMS也没有找到合适的例子。
如果修复失败，请回到这里反馈。

**Comment by lowrt** [comment]
![1571546710915](https://user-images.githubusercontent.com/37591855/67154963-a34d1700-f337-11e9-9062-dbca2bf679f0.jpg)

正常運作 感謝~
