### ISSUE TITLE
How to use SearchString in Lua console?

### ISSUE THREAD

**Issue by OniOniOn-** [Kagamia/WzComparerR2#118]
I'm trying to export gear imgs in this format:
folder name: gear name, contains Icon, props, etc...
I want to search over 1000 gears with their Item name and export their contents.
ex) search "AbsoLab" and export all item containing the string in name
How can I access WzComparerR2's SearchString function inside Lua console?

**Comment by Kagamia** [comment]
access the global string linker instance from lua:
 `local stringLinker = env.Context.DefaultStringLinker`
