### ISSUE TITLE
Alignment of tooltip icons

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#12]
**Path**: WzComparerR2\CharaSimControl\GearTooltipRender2.cs
**Line**: 1023 in your version (code is below)
**Issue**: As of the V update, the 'Magic Defense' stat is no longer used and is condensed into simply 'Defense'. Therefore only three icons are used in the tooltip of equipment and they are now centered. Before they were aligned to the left. How can it be fixed?

The three icons can be seen below the level requirements and above the class names.

**Simulated version**
![Simulated version](https://cdn.discordapp.com/attachments/236180502200057856/254213492272267275/1152200.png)

**In-game version**
![In-game version](https://cdn.discordapp.com/attachments/236180502200057856/254213507296395264/ss2016-12-02at06.41.31.jpg)

**Code**:

```        private void DrawPropDiffEx(Graphics g, int x, int y)
        {
            int value;
            string numValue;
            //Defense tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_pdd, x, y);
            x += 62;
            DrawReqNum(g, "0", NumberType.LookAhead, x - 5, y + 6, StringAlignment.Near);

            //Boss DMG tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_bdr, x, y);
            x += 62;
            this.Gear.Props.TryGetValue(GearPropType.bdR, out value);
            numValue = (value > 0 ? "+ " : null) + value + " % ";
            DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Near);

            //Ignored Monster DEF tooltip icon
            g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_igpddr, x, y);
            x += 62;
            this.Gear.Props.TryGetValue(GearPropType.imdR, out value);
            numValue = (value > 0 ? "+ " : null) + value + " % ";
            DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Near);
        }
```

Thank you.

**Comment by Kagamia** [comment]
Simply change the x position of every draw call.
like this:

````
{
    int value;
    string numValue;
    //Defense tooltip icon
    x += 62;
    g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_pdd, x, y);
    DrawReqNum(g, "0", NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);

    //Boss DMG tooltip icon
    x += 62;
    g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_bdr, x, y);
    this.Gear.Props.TryGetValue(GearPropType.bdR, out value);
    numValue = (value > 0 ? "+ " : null) + value + " % ";
    DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);

    //Ignored Monster DEF tooltip icon
    x += 62;
    g.DrawImage(Resource.UIToolTip_img_Item_Equip_Summary_icon_igpddr, x, y);
    this.Gear.Props.TryGetValue(GearPropType.imdR, out value);
    numValue = (value > 0 ? "+ " : null) + value + " % ";
    DrawReqNum(g, numValue, NumberType.LookAhead, x - 5, y + 6, StringAlignment.Far);
}
````

**Comment by Sunaries** [comment]
Thank you @Kagamia!

I have one more question.

![Simulated version](https://cdn.discordapp.com/attachments/236180502200057856/255324050853855232/1152200.png)

Is there a way to change the overlap of the text? For example, if the item name has X characters, it will automatically add an ellipsis?

**Comment by Kagamia** [comment]
Yes, we can use 'StringTrimming.EllipsisCharacter' to control the layout of texts. See[msdn](https://msdn.microsoft.com/en-us/library/system.drawing.stringformat.trimming(v=vs.110).aspx)
Here's some pseudo codes:

````
var fmtItemName = new StringFormat(){Trimming=StringTrimming.EllipsisCharacter};
var fmtItemType = new StringFormat(){Alignment = StringAlignment.Far};

//measure itemType's text width
var layoutSize = g.MeasureString(itemType, font, MAX_WIDTH, fmtItemType);

//draw texts
g.DrawString(itemName, font, brush, new RectangleF(LEFT, y, MAX_WIDTH-laytouSize.Width, lineHeight), fmtItemName);
g.DrawString(itemType, font, brush, RIGHT, y, fmtItemType);
y+=lineHeight;
````

**Comment by Sunaries** [comment]
@Kagamia Oh, I see... Where would you add the code?

**Comment by Kagamia** [comment]
Currently `GearGraphics` can only used for monospaced font formatting.
I'm still trying to support all possible fonts and word wrap, maybe it will appear in next version XD

**Comment by Sunaries** [comment]
Thank you for your hard work and dedication on this program. It's amazing. 
I will close this thread since my questions have been answered. :)
