### ISSUE TITLE
New Face Category "5" is not picked up by the Avatar Render

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#120]
KMS just added a new set of faces under 0005XXXX for the new class Adele, but the avatar render isn't picking them up.
![Avatar](https://user-images.githubusercontent.com/34289651/72668581-58a27000-39f6-11ea-9ba3-87af269c8dfd.PNG)

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/74497877-c076a880-4f19-11ea-85d3-36733f97c79b.png)

fixed.

**Comment by PirateIzzy** [comment]
👍
