### ISSUE TITLE
使用ExportSkill导出CMS技能表Skill001.wz时遇到错误

### ISSUE THREAD

**Issue by MaiBaooo** [Kagamia/WzComparerR2#125]
导出后得到了一份Skill.wz的技能列表

**Comment by Kagamia** [comment]
可以试图只加载string.wz和skill001.wz来完成skill001的导出。

**Comment by MaiBaooo** [comment]
感谢大佬翻牌！
依据此方法实际尝试后，反馈如下异常文本：

************** 异常文本 **************
System.Exception: ID 'X' not found.
   在 WzComparerR2.Calculator.Execute(List`1 inst, EvalContext param)
   在 WzComparerR2.Calculator.Parse(String mathExpression, Decimal[] args)
   在 WzComparerR2.CharaSim.SummaryParser.GetSkillSummary(String H, Int32 Level, Dictionary`2 CommonProps, SummaryParams param)
   在 WzComparerR2.CharaSim.SummaryParser.GetSkillSummary(Skill skill, Int32 level, StringResult sr, SummaryParams param)
   在 WzComparerR2.CharaSim.SummaryParser.GetSkillSummary(Skill skill, StringResult sr, SummaryParams param)
   在 WzComparerR2.DBConnection.GenerateSkillTable()
   在 WzComparerR2.MainForm.btnExportSkill_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 DevComponents.DotNetBar.ButtonX.OnClick(EventArgs e)
   在 DevComponents.DotNetBar.ButtonX.OnMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 DevComponents.DotNetBar.PopupItemControl.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Kagamia** [comment]
出现不明参数的话大多数情况为wz中属性声明不规范导致解析失败。

这个没办法，只能case by case去游戏里找正常的解析结果，然后推算客户端是如何处理这些意外声明的。。。

**Comment by MaiBaooo** [comment]
感谢大佬耐心讲解，受益良多

**Comment by Kagamia** [comment]
https://github.com/Kagamia/WzComparerR2/commit/bf1b3df8cf6cfcb05637f49b1d488082179d4377

查看了一下skill001有两个技能出现了意外的格式，一个是X一个是x30，貌似两个技能在游戏里都很难找到了。
稍微更新下代码，用于跳过这个解析错误。

**Comment by Kagamia** [comment]
（因为似乎这个功能用的人比较少就不弹错误提示了...）

寻找wz中全部wztype的api还没有设计，暂不想实现，留个坑在这里（
更新后的可执行文件可以去release里自取。

**Comment by MaiBaooo** [comment]
天啊太激动，感谢大大！
