### ISSUE TITLE
Map002.wz not being picked up for JapanMS

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#126]
When I load Base.wz with KoreaMS, it loads all the WZ files, including Map002.wz:
![KMS Comparison](https://user-images.githubusercontent.com/34289651/75729375-9e6e7b80-5cb8-11ea-9961-d9402d21c3de.png)

However, loading JapanMS does not load Map002.wz by default:
![JMS Comparison](https://user-images.githubusercontent.com/34289651/75729569-e9888e80-5cb8-11ea-8708-9b769e87c41b.png)

I double checked, and I have the auto-detect option selected:
![Auto-detection](https://user-images.githubusercontent.com/34289651/75729640-ef7e6f80-5cb8-11ea-9d2e-26b8f80b9d15.PNG)

GMS does not have Map002.wz yet so I can't check that.

**Comment by Sunaries** [comment]
I can confirm this error while I was updating MSEA v192 -> v193. In v193, Map002.wz was added and it was not picked up by the comparison.

![test](https://cdn.discordapp.com/attachments/345081079578755086/684818663806861365/56.png)

**Comment by Kagamia** [comment]
I have neither JMS or MSEA client, just try to fix that.

**Comment by PirateIzzy** [comment]
Confirming that it was fixed for JMS. I'll let @Sunaries confirm if it works for MapleSEA, since I don't have v193 yet.

**Comment by Sunaries** [comment]
I will try it out with the added code once the GMS update arrives.

**Comment by PirateIzzy** [comment]
Confirming that this is fixed.

**Comment by PirateIzzy** [comment]
Turns out I was wrong; it's fixed for all versions except ChinaMS it seems.

![image](https://user-images.githubusercontent.com/34289651/84049349-537c9800-a97a-11ea-82e0-9f72eace327f.png)

**Comment by Kagamia** [comment]
@PirateIzzy  do you have enabled **detect extra wz files** in options?
![image](https://user-images.githubusercontent.com/10445904/84049679-4e9dff80-a9df-11ea-8bf6-4f4ce26987a2.png)

**Comment by PirateIzzy** [comment]
@Kagamia I did, turns out I forgot to save a commit, as I moved to a new PC. We can disregard, it's working.
