### ISSUE TITLE
能增加批量修改和正则表达式匹配查找功能么？

### ISSUE THREAD

**Issue by MDamageOver** [Kagamia/WzComparerR2#128]
如题

**Comment by Kagamia** [comment]
wcR2不是wz编辑器，不提供任何修改wz文件的功能。

正则匹配查找可以考虑~

**Comment by Kagamia** [comment]
https://github.com/Kagamia/WzComparerR2/commit/704d00b367dc396af862bd860a48846dec1fa832

已经加入正则搜索
