### ISSUE TITLE
裝備素質模擬

### ISSUE THREAD

**Issue by leovincentseles** [Kagamia/WzComparerR2#129]
![image](https://user-images.githubusercontent.com/36748589/79184361-7ab95c00-7e46-11ea-8081-4a44054e430e.png)
請問該如何使用裝備模擬功能?
我在Character->Weapon中任一img點兩下並沒有跳出裝備素質的圖

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/79184483-da176c00-7e46-11ea-8ac9-d10426982150.png)

点击菜单 Modules-CharaSim-QuickView会主动执行一次装备模拟
当启用下面的autoQuickView后，点击对应节点会自动进行装备模拟。

**Comment by leovincentseles** [comment]
![image](https://user-images.githubusercontent.com/36748589/79184881-fbc52300-7e47-11ea-8f08-096ed8207dcd.png)
點擊Modules後沒有跳出下排的視窗，請問是編譯要加哪些選項嗎
我用的是Visual Studio 2019 Community

**Comment by Kagamia** [comment]
程序界面库使用的是DevComponents.DotNetBar2，如果想要自行编译的话，需要在开发环境中安装[dotnetbar](http://www.devcomponents.com/dotnetbar/download.aspx)，以保证界面可以正常的在开发工具里进行编辑。

如因为各种原因无法安装的话，请确认所有界面的`*.designer.cs`源代码未被改动过，否则就会出现类似您这样的“菜单无法弹出”的问题。

**Comment by leovincentseles** [comment]
安裝後重新開機並重新下載專案編譯就沒問題了，感謝
