### ISSUE TITLE
some bugs in MapRenderer with the new map MasteriaGL

### ISSUE THREAD

**Issue by ilovuxay** [Kagamia/WzComparerR2#13]
if you render the map "610010000 幽影森林：曲树", you will find some bricks are lost.
![image](https://cloud.githubusercontent.com/assets/17734954/21077116/6b805218-bf7a-11e6-9742-b002117afeed.png)
and  what will it do when i press ctrl+1~9 ?

by the way, the software can not preview the hairstyle, face, etc.
![23457](https://cloud.githubusercontent.com/assets/17734954/21077120/affbc792-bf7a-11e6-919c-d42f3595aaef.png)

Above all, thank you for developing such an magnificent software.

**Comment by Kagamia** [comment]
Hello, thanks for bug reporting.

1> MapRender plugin has not updated to version 2.x, so it does not support the newest optimized wz files with canvas links, terriains and portals will blink or disappear when you try to simulate the maps on newest clients. 

Unfortunately, almost all of the world Maplestory clients have updated to this version.

MapRender v2.0 is still under development, I've forked [a brunch](https://github.com/Kagamia/WzComparerR2/tree/mapRender2) , it is only a preview version without any UI components, but it renders the maps and skeletons well at the moment. You can fork it and compile if you can't wait for the final version. 😆 

2> Ctrl+1~9: show or hide specific layer.
1 - back
2 - reactor
3 - obj
4 - tile
5 - npc
6 - mob
7 - foothold/ladder/rope
8 - portal show/hide/designMode
9 - front

For detail, See [source code](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.MapRender/FrmMapRender.cs) line:487~554

3> Avatar parts act as dummy equipments in game data, they do not contains an icon like normal weapons or items. 
[WcR2.Avatar](https://github.com/Kagamia/WzComparerR2/tree/master/WzComparerR2.Avatar) is an optional plugin for avatar simulation. Checking 'Plugin' folder and see whether it is installed.

**Comment by ilovuxay** [comment]
Amazing work! Since the v137 version, we could not use the old Momiji Software for avatar simulation because it can not display the eyes and faces. Now we could learn to use WcR2.Avatar.

However, something strange happened when i looking for the "草木精灵", the newest WzComparer still only lists one result, but it is obvious that there should be "草木精灵套服" & “草木精灵鞋”.

And the simulator can not display some certain equipment, such as "狗狗耳朵"&"阿丽莎的翅膀". I think there could be some advanced effect it haven't supported. 

![image](https://cloud.githubusercontent.com/assets/17734954/21741493/6fdb0990-d512-11e6-9e53-1eb4078737ee.png)

**Comment by Kagamia** [comment]
@ilovuxay 

1> Momiji has updated a new version today. I will not post the download link. 😆 
    Follow author -> [Exrpg BBS](http://bbs.exrpg.com/thread-121783-1-1.html)

2> "草木精灵套服" and “草木精灵鞋” are set item part names, not specific equip names.
    Checking wz node `Etc.wz\SetItemInfo.img\602` for more details.

3> Yeah, wcR2.Avatar not support item effect and multi layers till now. In fact, this part has already completed for a long time. [Entry.cs](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.Avatar/Entry.cs) leaves a ton of codes for manually dumping skill and chair effect animations, but there is not a well designed UI for them.

**Comment by ilovuxay** [comment]
![image](https://cloud.githubusercontent.com/assets/17734954/21791476/f58e85d2-d71d-11e6-978d-3a84c70ddaa9.png)

Ah, So it is.... Now I know there are discrepancies between the two names ...

By the way, it seems that you are quite familiar with the Momiji developer?
