### ISSUE TITLE
可以提供一个有avatar保存功能的版本吗？

### ISSUE THREAD

**Issue by MikyWang** [Kagamia/WzComparerR2#130]
之前有个版本我记得是可以保存修改好的人物gif动图的，最新版好像去掉了，可以提供一个吗，这个对我非常有用，拜托了！

**Comment by Kagamia** [comment]
其实一开始做avatar就想做保存功能，但是有很多没解决的坑，比如多图层动画时长不同步时如何渲染，如何计算时间轴，后来拖得时间太长就没在做了。

**Comment by Kagamia** [comment]
已经实现了初步gif导出
