### ISSUE TITLE
Any way to export sprites instead of an .img?

### ISSUE THREAD

**Issue by Araraura** [Kagamia/WzComparerR2#131]
I'm trying to export sprites from an entire category (In this case, UIWindowPL2) but I can't find an option that lets me export all of the sprites from that category. I could still export them one by one, but that would just take a lot of time.

**Comment by Kagamia** [comment]
Since there's no way to export all images in one-click.

an alternative function is to use lua plugin, here's the sample code: [DumpImages](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/Examples/DumpImages.lua)

**Comment by Araraura** [comment]
> Since there's no way to export all images in one-click.
> 
> an alternative function is to use lua plugin, here's the sample code: [DumpImages](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/Examples/DumpImages.lua)

Can I make this script only extract UIWindowPL2 instead of everything?

**Comment by Kagamia** [comment]
Just specify parameter in the script

start from [line 37](https://github.com/Kagamia/WzComparerR2/blob/6e1a89f5315d2cbc064820220360a290560fb7e8/WzComparerR2.LuaConsole/Examples/DumpImages.lua#L37):
```
-- all variables
local topWzPath = 'UI\\UIWindowPL2.img' -- maybe here? I can't find that from CMS client
local topNode = PluginManager.FindWz(topWzPath)
local outputDir = "x:\\somewhere\\on\\your\\disk"
```

**Comment by Araraura** [comment]
> UI\\UIWindowPL2.img

It tells me "Done." but nothing appears at the output folder

**Comment by Araraura** [comment]
> Just specify parameter in the script
> 
> start from [line 37](https://github.com/Kagamia/WzComparerR2/blob/6e1a89f5315d2cbc064820220360a290560fb7e8/WzComparerR2.LuaConsole/Examples/DumpImages.lua#L37):
> 
> ```
> -- all variables
> local topWzPath = 'UI\\UIWindowPL2.img' -- maybe here? I can't find that from CMS client
> local topNode = PluginManager.FindWz(topWzPath)
> local outputDir = "x:\\somewhere\\on\\your\\disk"
> ```

It tells me "Done." but nothing appears at the output folder

**Comment by Kagamia** [comment]
Update. https://github.com/Kagamia/WzComparerR2/commit/f32ab684153b4a22f42173b34ff6df3a9d37c167

plz retry with the latest version.

**Comment by Araraura** [comment]
> Update. [f32ab68](https://github.com/Kagamia/WzComparerR2/commit/f32ab684153b4a22f42173b34ff6df3a9d37c167)
> 
> plz retry with the latest version.

Works now. Thanks!
