### ISSUE TITLE
如何通过lua批量导出mp3音乐

### ISSUE THREAD

**Issue by maplestars** [Kagamia/WzComparerR2#133]
你好，我想批量导一下bgm，有尝试在lua中使用ExtractSound()获取mp3数据，但是始终无法正确解析返回的数据，想请教一下如何通过lua，正确解析并保存bgm为mp3格式。

**Comment by Kagamia** [comment]
```
-- 导出声音文件内容为byte[]
local bytes = wzSound:ExtractSound()

-- 通过SoundType判断文件类型的后缀名
local ext = ''
if wzSound.SoundType ==Wz_SoundType.Mp3 then ext = '.mp3'
elseif wzSound.SoundType ==Wz_SoundType.WavRaw then ext = '.wav'
else ext = '.bin'
end
fn = 'xxxx'..ext

-- 保存文件
File.WriteAllBytes(fn, bytes)
```

**Comment by maplestars** [comment]
搞定了，十分感谢！^_^

**Comment by juwell** [comment]
> ```
> import 'WzComparerR2.WzLib'
> import 'System.IO'
> 
> -- 导出声音文件内容为byte[]
> local bytes = wzSound:ExtractSound()
> 
> -- 通过SoundType判断文件类型的后缀名
> local ext = ''
> if wzSound.SoundType ==Wz_SoundType.Mp3 then ext = '.mp3'
> elseif wzSound.SoundType ==Wz_SoundType.WavRaw then ext = '.wav'
> else ext = '.bin'
> end
> fn = 'xxxx'..ext
> 
> -- 保存文件
> File.WriteAllBytes(fn, bytes)
> ```

不懂就问:
最后保存文件的这行, 是不是不是lua的代码?网上搜了一圈, 好像是c#的
所以lua要怎么写入二进制的文件?

**Comment by Kagamia** [comment]
@juwell 

可以使用lua内置的io库，类似这样：
```
local out = io.open("outfile.dat", "wb")
local strBytes = string.char(150,160,170,180,190,200,210,220)
out:write(strBytes)
out:close()
```
