### ISSUE TITLE
Forked Repository - Map002 No Longer Opens MapRender

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#134]
So today I fetched some recent MapRender changes from the main fork into my local repository:

https://github.com/PirateIzzy/WzComparerR2-Code/commit/01b8f4e8311f81cd2ec02dcfec96a0b596a74d51#diff-a9c55d9f1f1ac047b4832d911826c86f

While it now picks up Map002, now the MapRender no longer works:
![unknown](https://user-images.githubusercontent.com/34289651/84091339-1b00ac80-a9c2-11ea-8118-083603b499fe.png)

The full error message is here, I wasn't able to figure out the issue:
https://pastebin.com/h8b3TChQ

It points to this line:
https://github.com/PirateIzzy/WzComparerR2-Code/blob/01b8f4e8311f81cd2ec02dcfec96a0b596a74d51/WzComparerR2.MapRender/FrmMapRender2.cs#L65

Also received an error log pointing to another error:
`[2020-06-08 18:16:05][Error][MapRender] MapRender error:System.NullReferenceException: Object reference not set to an instance of an object.
   at WzComparerR2.MapRender.UI.MapRenderUIRoot.InitGlobalResource()
   at WzComparerR2.MapRender.UI.MapRenderUIRoot..ctor()
   at WzComparerR2.MapRender.FrmMapRender2.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at WzComparerR2.MapRender.Entry.<>c__DisplayClass5_0.<btnItem_Click>b__0()`

Pointing to this line, I assume:
https://github.com/PirateIzzy/WzComparerR2-Code/blob/01b8f4e8311f81cd2ec02dcfec96a0b596a74d51/WzComparerR2.MapRender/UI/MapRenderUIRoot.cs#L124

Is it possible that there's a file missing / corrupted?

**Comment by charlescao460** [comment]
#135 Fix in my PR. I will be really appreciated if you could test it:)

**Comment by Kagamia** [comment]
@charlescao460  Thanks for your contribution, I'll test it tonight.

**Comment by PirateIzzy** [comment]
I tried out Kagamia's suggestion (moving RegisterAllSection() to the top of the OnLoad() method). and now the MapRender works. I will commit it to my fork for now, but I'll keep this issue open in case something else comes up.

**Comment by Kagamia** [comment]
@PirateIzzy  however it is a quick way to fix the bug with a little hacking. 

I suggest both of us to add some comment for it, so that we won't encounter the bug any more. 🤣

**Comment by PirateIzzy** [comment]
Okay, this works. Thank you.
