### ISSUE TITLE
传送门不显示

### ISSUE THREAD

**Issue by uaex** [Kagamia/WzComparerR2#137]
最新Release版本
国服V79
跨图传送门不显示(图内传送门正常)

**Comment by Kagamia** [comment]
可以提供实际效果的截图和预期效果的详细解释吗？

**Comment by uaex** [comment]
![A](https://user-images.githubusercontent.com/13354302/86423373-4735f180-bd12-11ea-925e-d91a3761366d.jpg)
如图所示，方框中应该有传送门。

**Comment by Kagamia** [comment]
可以提供完整界面截图吗？

截图中无法显示出你是否手动隐藏了传送门，您可以尝试使用ctrl+8来切换传送门的状态。
![image](https://user-images.githubusercontent.com/10445904/86430961-12339a00-bd26-11ea-92be-f446fd3072af.png)

**Comment by uaex** [comment]
> 可以提供完整界面截图吗？
> 
> 截图中无法显示出你是否手动隐藏了传送门，您可以尝试使用ctrl+8来切换传送门的状态。
> ![image](https://user-images.githubusercontent.com/10445904/86430961-12339a00-bd26-11ea-92be-f446fd3072af.png)

嗯,确实打开CTRL+8就可以显示了,不过默认关闭吗?我第一次使用. CTRL+N中有几个切换没反应不知道是什么图层效果的开关🤣
另外传送门没有动画效果,是静态的

还有一个建议:关于img排序,应该考虑按数字排序,  比如目前排序完是 1000.img 100001.img 1001.img 但1000.img 1001.img 100001.img 的顺序应该更好

**Comment by Kagamia** [comment]
1> 可能是旧版客户端对于传送门ID的定义与新版本不同，wc没有义务永远兼容旧版客户端。
2> 按ID排序可自行开启
![image](https://user-images.githubusercontent.com/10445904/86431899-9b4bd080-bd28-11ea-859c-9623ceab0d65.png)
![image](https://user-images.githubusercontent.com/10445904/86431885-91c26880-bd28-11ea-9c5d-abd1b7e93d34.png)

**Comment by uaex** [comment]
> 1> 可能是旧版客户端对于传送门ID的定义与新版本不同，wc没有义务永远兼容旧版客户端。
> 2> 按ID排序可自行开启
> ![image](https://user-images.githubusercontent.com/10445904/86431899-9b4bd080-bd28-11ea-859c-9623ceab0d65.png)
> ![image](https://user-images.githubusercontent.com/10445904/86431885-91c26880-bd28-11ea-9c5d-abd1b7e93d34.png)

🤣好吧
