### ISSUE TITLE
Are these Equipment/Item?Ability windows just aesthetic or can we use them?

### ISSUE THREAD

**Issue by Dban1** [Kagamia/WzComparerR2#139]
![image](https://user-images.githubusercontent.com/33821975/87240057-8a960b80-c448-11ea-9dfe-c519336b2c57.png)

**Comment by Kagamia** [comment]
The UI is inherited from wzcomparer1 (previous version of wzcomparerR2) as a part of CharaSim module, which could simulate your stat with given gears and buffs.

But it has been freezing for more than 7 years. Fomula and mechanism become more and more complex after BigBang, and no one have time or be interested in maintaining it. The only use for it is to add a lot of items and view them together.

![image](https://user-images.githubusercontent.com/10445904/87240326-3d676900-c44b-11ea-9251-157caa9f67f4.png)

**Comment by Dban1** [comment]
Ah I see! True, MapleStory is so complex now. Thanks for clarifying!
