### ISSUE TITLE
Ellipsis & Width window Set Effect

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#14]
Greetings,

![TEST](https://cdn.discordapp.com/attachments/126464569664077824/265908406366371842/1482142.png)

What exact line defines the width of the set effect window? As you can see, the text `Invincible for 1 more seconds after getting attacked.` overlaps. I don't know how to make it look like this in-game:

![ingame](https://puu.sh/t9VtA/e7d5514b8e.png)

Furthermore, as you can see in the first screenshot there is an ellipsis. However, if you check the in-game version it says `Epaulet` while mine is cut-off at `Epau...`

Here is the code: http://pastebin.com/81xwABYu - Do you know how to make it so that I can adjust the maximum characters, so that it'll appear as `Epaulet` and when it is much longer, the ellipsis will come in.

(`TextRenderer.DrawText(g, itemName, GearGraphics.EquipDetailFont2, new Rectangle(50, picHeight, MAX_WIDTH - (int)layoutSize.Width, 40), ((SolidBrush)brush).Color, TextFormatFlags.EndEllipsis);`

(`TextRenderer.DrawText(g, itemName, GearGraphics.EquipDetailFont2, new Rectangle(8, picHeight, MAX_WIDTH - (int)layoutSize.Width, 18), ((SolidBrush)brush).Color, TextFormatFlags.EndEllipsis);`)

(line beginning with `var MAX_WIDTH = 261;`)

**Comment by Kagamia** [comment]
Re: problem2:
````C#
//line: 182
//measure itemType's text width
  var layoutSize = g.MeasureString(typeName + "...", GearGraphics.EquipDetailFont2, MAX_WIDTH, fmtItemType);
````

`+"..."` could be dropped, it makes `layoutSize` a bit wide than its real size.

---------------------------------

Re: problem1:
Annoying word-wrap appears everywhere 😢 

Actually, both GDI and GDI+ support word-wrap/word-break in their format flags, but we cannot set line space with neither of them, default line space is based on the font which you selected. So I have to layout the words manually.

Replace GDI/GDI+ drawString function with `GearGraphics.DrawString` may solve this issue. If you don't care about pixel-level-perfect simulation of the game, just add `TextFormatFlags.WordBreak` in your code.

**Comment by Sunaries** [comment]
@Kagamia 

Thanks! I dropped `+ "..."` and it fixed the issue.

![fix](https://cdn.discordapp.com/attachments/236180502200057856/266266184108736513/1482142.png)

&

![fix2](https://cdn.discordapp.com/attachments/236180502200057856/266266182909296643/1152174.png)

Thank you!
