### ISSUE TITLE
PNG Format 513 is showing well, but saved wrongly

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#141]
https://github.com/Kagamia/WzComparerR2/blob/fd64241240069fd3d81784109d2970fabdc78480/WzComparerR2.WzLib/Wz_Png.cs#L209-L211

`PixelFormat.Format32bppArgb` to `PixelFormat.Format16bppRgb565`

KENNYSOFT/WzComparerR2#33

**Comment by Kagamia** [comment]
Nice catch! fixed.
