### ISSUE TITLE
Remember MainForm state on close

### ISSUE THREAD

**Issue by OniOniOn-** [Kagamia/WzComparerR2#147]
Hello, I want WcR2 to remember MainForm state on close. I wrote some codes below.
```
public MainForm()
{
    InitializeComponent();
    Form.CheckForIllegalCrossThreadCalls = false;
    this.MinimumSize = new Size(600, 450);
    advTree1.AfterNodeSelect += new AdvTreeNodeEventHandler(advTree1_AfterNodeSelect_2);
    advTree2.AfterNodeSelect += new AdvTreeNodeEventHandler(advTree2_AfterNodeSelect_2);
    //new ImageDragHandler(this.pictureBox1).AttachEvents();
    RegisterPluginEvents();
    createStyleItems();
    initFields();
    loadFormState();
}

protected override void OnFormClosing(FormClosingEventArgs e)
{
    base.OnFormClosing(e);
    saveFormState();
}

private void saveFormState()
{
    WcR2Config.Default.WindowState = (int)this.WindowState;
    WcR2Config.Default.Width = this.Size.Width;
    WcR2Config.Default.Height = this.Size.Height;
    ConfigManager.Save();
}

private void loadFormState()
{
    int value = WcR2Config.Default.WindowState.Value;
    this.WindowState = Enum.IsDefined(typeof(FormWindowState), value) ? (FormWindowState)value : FormWindowState.Normal;
    this.Size = new Size(WcR2Config.Default.Width, WcR2Config.Default.Height);
}
```
It might look bad, but it works. (I've never used WinForm before)
I tried to 'set' the top ribbon `Expanded` state but it doesn't update the ribbon on startup.
![image](https://user-images.githubusercontent.com/6011621/102722076-070b0f80-4342-11eb-8dd3-26e1916bcfa9.png)
Also, I couldn't find these highlighted parts' names. I would like WcR2 to remember these parts' position(size) as well.

**Comment by Kagamia** [comment]
they are all components from dev dotnetbar.
1> try to remove `ribboncontrol.expanded = false` from `mainForm.designer.cs` and your code would work.
2> try to load and save `expandablesplitter.splitPosition` 
3> that is docksite and I'm not familiar with that. try something like `dotnetbarManager.Load/SaveLayout`

**Comment by OniOniOn-** [comment]
![image](https://user-images.githubusercontent.com/6011621/102803781-25cddc80-43fc-11eb-9c14-78659421b444.png)
![image](https://user-images.githubusercontent.com/6011621/102804000-7cd3b180-43fc-11eb-989b-4339875321d1.png)
It remembers WindowState(minimized), WindowSize, Ribbon expanded/selected tab, both splitter position, column(3~9) width and bottom dotnetbar's height.
I modified default sizes to make them easier to use. Bigger window, larger search result columns, etc.
If you'd like, I will make draft PR. (Or make a fork and just use myself)
