### ISSUE TITLE
Skill simulation variable bug

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#15]
Greetings,

I have encountered a bug with the `cr` variable:

![bug](https://cdn.discordapp.com/attachments/236180502200057856/265934214371868672/skill_400011005.png)

`100ising Sun` 

It should say `Rising Sun`, but since descriptions start with `#c` and the letter after it being an R, the program will recognize it as the variable `cr` used for skills in the data.

**Comment by KENNYSOFT** [comment]
Haha, it's funny! I think that SummaryParser.cs:50 (GetValueIgnoreCase) is the problem.

**Comment by Kagamia** [comment]
AhA~ there must be something happened that makes the code become like what we see now...
`#propName` has priority over `#c`, `#propName` is case-insensitive and greedy matched.

It can't be corrected immediately,  but you could disable `IgnoreCase` comparison in your version. 😆

**Comment by Sunaries** [comment]
Changed `if (kv.Key.Equals(key, StringComparison.CurrentCultureIgnoreCase))` 
to
`if (kv.Key.Equals(key, StringComparison.CurrentCulture))` in SummaryParser.cs to fix this issue.
