### ISSUE TITLE
No longer able to load World Map in Map Simulator

### ISSUE THREAD

**Issue by Dban1** [Kagamia/WzComparerR2#150]
Recently when I tried to load the World Map in the simulator, it gives me this error. I am on v219 of GMS:

![image](https://user-images.githubusercontent.com/33821975/104395986-d145f900-5584-11eb-96cf-521673fe5478.png)

**Comment by Kagamia** [comment]
I have no GMS installed, and for WcR2-KMS issues please post to https://github.com/KENNYSOFT/WzComparerR2

**Comment by Kagamia** [comment]
Someone tested with GMS229 but can't repro, 
I think Ne*on has already fixed the client, that means duplicated nodes are not expected.
