### ISSUE TITLE
Avatar能否将模拟后的动作输出为PNG/GIF？

### ISSUE THREAD

**Issue by Fyllan** [Kagamia/WzComparerR2#154]
想把Avatar模拟后的效果输出成PNG或者GIF，不知道WCR2现在是否有这个功能？

**Comment by Kagamia** [comment]
avatar由三个独立图层组成：身体、表情、座驾（可能未来还要加入effect？），所以一直没想好如何计算动画长度来输出gif，因为各部分动画时长不一样。

记忆里momiji是粗暴排列组合输出的png，不过也没实现输出gif。

**Comment by KENNYSOFT** [comment]
https://github.com/KENNYSOFT/WzComparerR2/pull/6

https://github.com/KENNYSOFT/WzComparerR2/blob/f12185e92509399b831178321dc6b6643c3ed159/WzComparerR2.Avatar/UI/AvatarForm.cs#L1308

@craftingmod contributed.

**Comment by Kagamia** [comment]
https://github.com/Kagamia/WzComparerR2/commit/d11bc683b42b277d43bd992d6436d41d5df75f2a

And thanks to @KENNYSOFT
