### ISSUE TITLE
avatar 角色初始化失败

### ISSUE THREAD

**Issue by ShiverZm** [Kagamia/WzComparerR2#155]
![image](https://user-images.githubusercontent.com/26861023/119856976-bd080480-bf45-11eb-9640-0c73d9df097c.png)

**Comment by Kagamia** [comment]
请详细说明您使用的wcR2版本，客户端地区及版本。

**Comment by ShiverZm** [comment]
[wcR2版本]最新版本 2.1.5.0
[客户端版本]079V2 大陆

**Comment by Kagamia** [comment]
很抱歉，wc明确不支持老旧的冒险岛客户端结构。

不过如果您想强行使用的话，可以试图关闭img检测。
home-options-skip img checksum validation

![image](https://user-images.githubusercontent.com/10445904/119857973-98f8f300-bf46-11eb-9715-5b2635036a3e.png)
![image](https://user-images.githubusercontent.com/10445904/119857950-939ba880-bf46-11eb-8043-3a5ddf6f3f67.png)
