### ISSUE TITLE
Windows 11 22000.51下使用WCR2容易出现下半部分搜索结果无法点击问题

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#156]
如题。
如果搜索结果较多，使用鼠标滚轮滚动容易导致部分搜索结果无法点击，但是如果手动拖动旁边的滚动条就不会出现此问题。

https://user-images.githubusercontent.com/29157608/124418015-0e997f80-dd8d-11eb-825d-e8a8235b8256.mp4

**Comment by Kagamia** [comment]
acknowledged.

但是没有环境无法测试....

**Comment by Kagamia** [comment]
已于Win11pro, 22000.65版本复现，但是没有找到错误根源。

该控件使用dotnetbar的listviewex，可能因为控件本身存在bug，也可能因为win11的事件机制有什么变化，这个问题搁置到win11正式版发布后再考虑如何修复。

**Comment by HikariCalyx** [comment]
前几天我跟 MSFT 那边反馈了此问题，现在已经在 22000.71 下修复。

**Comment by HikariCalyx** [comment]
呃，好像最近一个什么更新又把这东西搞坏了……
回头继续跟 Microsoft 反馈去。

**Comment by HikariCalyx** [comment]
22000.120又修好了，目前22000.132先观望一会儿。等下一个累积更新推送下来如果确定不能再重现这个BUG的话，我就可以close issue了。

**Comment by Kagamia** [comment]
感谢测试 🤣

**Comment by HikariCalyx** [comment]
22000.160 已推送，确定已经完全修正。closed.
