### ISSUE TITLE
How to find the dropitem information?

### ISSUE THREAD

**Issue by ChineseDragon-code** [Kagamia/WzComparerR2#157]
want to know how to get the item,  including the dropping

**Comment by KENNYSOFT** [comment]
Drop is controlled by the server, there are not any information in the client.

**Comment by ChineseDragon-code** [comment]
even which items drop from which mob?

**Comment by Elem8100** [comment]
String.wz/MonsterBook.img
But only for old version and useless.

**Comment by ChineseDragon-code** [comment]
Thanks! other, did you know where eqps effect-------- 原始邮件 --------发件人： Elem8100 ***@***.***>日期： 2021年7月12日周一 10:39收件人： Kagamia/WzComparerR2 ***@***.***>抄送： ChineseDragon-code ***@***.***>, Author ***@***.***>主    题： Re: [Kagamia/WzComparerR2] How to find the dropitem information? (#157)
String.wz/MonsterBook.img
But only for old version and useless.

**Comment by Kagamia** [comment]
Most of the eqps effect stores in `Effect.wz/ItemEff.img` and `Effect.wz/SetEff.img`

**Comment by ChineseDragon-code** [comment]
Sorry!  no the vision, but the drop rate effect or + exp % effect. like having the cash eqps，three or four eqps，then adding the effect to another item drop rate or more % exp-------- 原始邮件 --------发件人： Kagamia ***@***.***>日期： 2021年7月25日周日 08:24收件人： Kagamia/WzComparerR2 ***@***.***>抄送： ChineseDragon-code ***@***.***>, Author ***@***.***>主    题： Re: [Kagamia/WzComparerR2] How to find the dropitem information? (#157)
Most of the eqps effect stores in Effect.wz/ItemEff.img and Effect.wz/SetEff.img

**Comment by Kagamia** [comment]
Could you please share any eqp name, eqp id, or just a snapshot?

 I don't think there is a unified mechanism for what you say.
