### ISSUE TITLE
需要 KMST 1.2.125 的适配支持

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#158]
首先，现有版本的 WzComparerR2 无法将 KMST 1.2.124 更新到 KMST 1.2.125。
重新下载客户端之后，和原有旧版客户端相比，重新产生了一个很大的 Data 目录。Data 目录结构已经随附件给出。
[kmst1125.txt](https://github.com/Kagamia/WzComparerR2/files/6866664/kmst1125.txt)

在这之后的加载逻辑可能需要调整成加载整个 Data 目录。

**Comment by Kagamia** [comment]
Thanks, already in draft.
![}27UH)WKC1P$NE%EZ$YCTYD](https://user-images.githubusercontent.com/10445904/126775776-40efd33c-c46a-4d89-8486-9d755bd2b85d.png)

**Comment by Kagamia** [comment]
Already update.
