### ISSUE TITLE
How to use this new version WzR2

### ISSUE THREAD

**Issue by ChineseDragon-code** [Kagamia/WzComparerR2#159]
not include exe file in win10

**Comment by ChineseDragon-code** [comment]
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

打不开程序，即使修改注册表以后

**Comment by Kagamia** [comment]
Could you please take a screenshot for your wcr2 folder?

The execution file may be blocked by any antivirus software or firewall or windows defender, double check their logs if you've installed any of them.

**Comment by ChineseDragon-code** [comment]
I fixed it.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月28日(星期三) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kagamia/WzComparerR2] How to use this new version WzR2 (#159)





 
Could you please take a screenshot for your wcr2 folder?
 
The execution file may be blocked by any antivirus software or firewall or windows defender, double check their logs if you've installed any of them.

**Comment by ChineseDragon-code** [comment]
thanks!







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kagamia/WzComparerR2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kagamia/WzComparerR2] How to use this new version WzR2 (#159)





 
Could you please take a screenshot for your wcr2 folder?
 
The execution file may be blocked by any antivirus software or firewall or windows defender, double check their logs if you've installed any of them.
