### ISSUE TITLE
Sylph Rings missing skill description

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#16]
Greetings,

![sylph](https://i.imgur.com/UO7iOhjh.jpg)

The above image is taken from in-game. The line `10% chance to apply Lv. 2 Freeze when attacking.` is missing from the simulation.
See:

![sylph2](https://cdn.discordapp.com/attachments/236180502200057856/265935944941568000/1114240.png)

![data](https://cdn.discordapp.com/attachments/236180502200057856/265936329265774594/ring.png)

**Comment by KENNYSOFT** [comment]
Oh, thanks for reporting! I have seen this item, but I didn't noticed! :)

**Comment by Kagamia** [comment]
Get it!
Never seen this before >.<
