### ISSUE TITLE
CMS v181 -> v182 补丁无法通过 DeadPatch 方式正常应用

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#160]
错误提示如下。
![2021-08-04 (1)](https://user-images.githubusercontent.com/29157608/128052937-5dcc4e5b-0047-413f-963e-4fae0c0a498a.png)
补丁配置只勾选DeadPatch就会弹出以上错误提示。使用旧版WzComparerR2可以顺利安装该补丁。

使用的补丁文件为 MaplePatch181to182.exe。

**Comment by Kagamia** [comment]
感谢提交bug。

已于最近一次提交修复。
