### ISSUE TITLE
Using Regex Characters in Non-Regex Search causes an error and messes up the UI

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#164]
Before Regex search was added, we could search with regex characters (such as ? or *)
![image](https://user-images.githubusercontent.com/34289651/130127579-22499adf-0893-40e0-8659-6a9404a91491.png)

However, now searching with those characters gives an error, even when Regex is unchecked:
![image](https://user-images.githubusercontent.com/34289651/130127659-2a49b5c7-d719-4fd7-9934-7a43cebd7118.png)

Stack Trace:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentException: parsing "?" - Quantifier {x,y} following nothing.
>    at System.Text.RegularExpressions.RegexParser.ScanRegex()
>    at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
>    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
>    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
>    at WzComparerR2.MainForm.<searchStringLinker>d__80.MoveNext() in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2\MainForm.cs:line 1939
>    at WzComparerR2.MainForm.buttonItemSearchString_Click(Object sender, EventArgs e) in C:\Izzy\WzComparerR2-source\WzComparerR2-Code\WzComparerR2\MainForm.cs:line 1913
>    at DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
>    at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
>    at DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
>    at DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
>    at DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
>    at DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
>    at DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

After closing the error message, the search result UI will be distorted:
![image](https://user-images.githubusercontent.com/34289651/130127907-15999d37-1f13-4488-998f-85a6b4efb02c.png)

![image](https://user-images.githubusercontent.com/34289651/130128010-97853c10-91f9-4a01-a9a9-40cdbe955607.png)

Expanded a bit:
![image](https://user-images.githubusercontent.com/34289651/130128055-a6810337-8f06-4a67-b2ca-e95b1c87dab3.png)

We could fix the first issue with the Regex characters in Non-regex characters by moving the `var re = new Regex(key, RegexOptions.IgnoreCase);` line here:

![image](https://user-images.githubusercontent.com/34289651/130128189-65bb91f1-e092-4fa9-a07c-7325bfbf5085.png)

However, I'm uncertain how to fix the UI.

**Comment by Kagamia** [comment]
nice catch.

As of performance consideration I simply catch the error outside, hope it could fix the bug.

**Comment by PirateIzzy** [comment]
Confirming that the regex search is fixed with it unchecked:
![image](https://user-images.githubusercontent.com/34289651/130277439-689289c6-120b-4859-b52c-caf57d8f24c2.png)

And the try-catch fixed the UI:
![image](https://user-images.githubusercontent.com/34289651/130277556-b26b68e6-ba57-4f36-b5f7-3ca99de73136.png)
![image](https://user-images.githubusercontent.com/34289651/130277591-dea3e416-4bed-4a26-8e40-418d0379509d.png)
