### ISSUE TITLE
Where can I found inner monospaced font "REQ LEV"?

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#17]
![image](https://cloud.githubusercontent.com/assets/6624567/21645948/83dfd96c-d2d7-11e6-8978-7e6a14976cc6.png)

![image](https://cloud.githubusercontent.com/assets/6624567/21646218/9777d398-d2d8-11e6-949a-74bf0559568b.png)

Like first image, this is a chair, which has a "REQ LEV". It is not matching with second image, which is created with WzComparerR2. It looks simillar with GearTooltip2's font of "REQ ~", but not same. I think the digit part is same with GearTooltip(OLD version)'s font (Like https://github.com/Kagamia/CharaSimResource/blob/master/Resources/ToolTip.Equip.Cannot.3.png), but I can't find localized "REQ LEV" image in KMS client. Where can I found this font?

**Comment by Kagamia** [comment]
UI/UIWindow.img/ToolTip/Equip/Can/reqLEV

Maybe is it.

**Comment by Sunaries** [comment]
@Kagamia got it right.

Here it is: ![image](https://cdn.discordapp.com/attachments/236180502200057856/266229039780331520/Equip.Can.reqLEV.png)

**Comment by KENNYSOFT** [comment]
Oh, thank you! I just try to find in UITooltip.img.. and not noticed about UIWindow.img/Tooltip. :<
