### ISSUE TITLE
能否在 QuickView 内添加 desc_leftalign 数值？

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#171]
某些特定的消耗类道具在实际游戏中存在额外的一些内容，这些内容位于 String 的 desc_leftalign 中，例如本次 CMST v173 的道具 2634040：
![cmst_2634040](https://user-images.githubusercontent.com/29157608/135551812-cb47ff73-f9cb-4e78-9b08-964c75402aff.png)
但是用 QuickView 模拟出来的道具介绍中没有 desc_leftalign 部分的内容。
![2634040](https://user-images.githubusercontent.com/29157608/135551862-291e8cdd-6857-46b0-9563-a21b63141801.png)

能否在 QuickView 中添加 desc_leftalign 显示的内容？

啊补充一下， @KENNYSOFT 的 WzComparerR2-KMS 是支持显示这部分的。
![2634040kms](https://user-images.githubusercontent.com/29157608/135552163-cb662c94-d519-48a8-9b78-1e32cae794df.png)

**Comment by KENNYSOFT** [comment]
https://github.com/KENNYSOFT/WzComparerR2/commit/68e6c341b1f041ed1c97510ea97163f25917d7d1#diff-74f2b64b7f446e1f1f863110286ac8a23cc40c864c5a7ad38470f8dc5724e836R547-R557

**Comment by Kagamia** [comment]
请问是否有游戏内表现的清晰带边框截图？

**Comment by PirateIzzy** [comment]
@Kagamia Here is a screenshot from GMS, item ID is 2631494.
![image](https://user-images.githubusercontent.com/34289651/135555770-effcafd1-98f8-418a-a78c-28e3cb309221.png)

**Comment by HikariCalyx** [comment]
其它类似的运用到了 desc_leftalign 的道具是 2633951。
![Maple_211118_101916](https://user-images.githubusercontent.com/29157608/135555785-ecf9bc75-b30a-4a2d-9b2d-c33312315120.png)
使用现有版本的 WcR2 模拟出来的结果是没有下面列举的内容的，用 WcR2-KMS 就有。
![2633951](https://user-images.githubusercontent.com/29157608/135555850-b7b06d3f-1135-4225-907d-4ad4310d3d25.png)
![2633951kms](https://user-images.githubusercontent.com/29157608/135555936-718fec0d-5d05-4a4a-8abd-14a7920bb4fc.png)

**Comment by Kagamia** [comment]
cool! thanks to all. I will add it later.

**Comment by Kagamia** [comment]
Fixed.
