### ISSUE TITLE
能否实现简单的命令行形式的WzCompare和Patcher功能？

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#177]
主要是为了方便在更新补丁或是新版本测试服一推送下来就可以第一时间进行比对，以及方便某些用户将客户端比对功能整合进服务器实现无人值守的自动比对。
假如说，这个命令行主程序名字叫做 wcr2_cli.exe，我想实现的两个客户端之间对比可以按照类似这样的方式实现：
两个客户端之间内容对比：
`wcr2_cli --compare --oldwz="D:\maplestory\Maple\Data\Base\Base.wz" --newwz="D:\maplestory\MapleT\Data\Base\Base.wz" --outputpng --outputaddedimg --outputremovedimg --pngcomparison=sizeanddatalength --resolvepnglink --reportout="D:\output"`
自动安装补丁并实现新旧客户端之间对比：
`wcr2_cli --patch --patchfile="D:\Downloads\01131to01132.patch" --gamepath="D:\maplestory\MapleT" --deadpatch --outputpng --outputaddedimg --outputremovedimg --pngcomparison=sizeanddatalength --resolvepnglink --reportout="D:\output"`
单纯安装补丁：
`wcr2_cli --patch --patchfile="D:\Downloads\MaplePatch183to184.exe" --gamepath="D:\MapleStoryCN" --deadpatch`

查询游戏内物品ID的功能可能实现起来略为复杂，可以先不做。

**Comment by Kagamia** [comment]
patcher和wzcomparer本身就是可独立运行的类，您只要简单地创建一个console application，并添加wzcomparerR2.exe和wzlib.dll为依赖即可直接调用。
