### ISSUE TITLE
KMST v1.2.132: Encoding prevents WZ files from being opened

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#180]
In the latest KMST patch, it seems that Nexon changed the encoding. When I load Base.wz, it only loads the Base.wz file without any of the other files:
![image](https://user-images.githubusercontent.com/34289651/144367911-8961a13e-17bc-414d-bf3f-4658fbb50834.png)

If I attempt to load another main WZ file (Npc.wz, Sound.wz, etc), then it gives me System.IO.EndOfStreamException:
![image](https://user-images.githubusercontent.com/34289651/144368012-a4fe82c6-ac1a-4c9f-b9e7-20529ce1836c.png)

If I attempt to load a partition of a WZ file (Npc_001.wz, Sound_003.wz, Mob_000.wz, etc, it gives me NullReferenceException:
![image](https://user-images.githubusercontent.com/34289651/144368094-3bdc9ac4-6fbc-4be7-a7ce-0026a6b68684.png)

It seems the encoding was indeed changed. Thanks to Neo for finding this:
![image](https://user-images.githubusercontent.com/34289651/144368191-54fb1af4-3fdf-49f3-8e38-ff9f1887f0ae.png)

**Comment by Kagamia** [comment]
😭

**Comment by PirateIzzy** [comment]
> 😭

Agreed😭
