### ISSUE TITLE
lua脚本批量导出xml的问题

### ISSUE THREAD

**Issue by tanruixin458** [Kagamia/WzComparerR2#182]
你好, 我发现批量导出的xml没有格式化, 研究了下, 发现c#源码里用到了XmlWriterSettings, 但是lua里怎么调用XmlWriterSettings的构造方法呢

**Comment by KENNYSOFT** [comment]
```lua
import 'System.Text'

local xsetting = XmlWriterSettings()
xsetting.CloseOutput = true
xsetting.Indent = true
xsetting.Encoding = Encoding.UTF8
xsetting.CheckCharacters = true
xsetting.NewLineChars = Environment.NewLine
xsetting.NewLineOnAttributes = false
```

and then replace `local xw = XmlWriter.Create(fs)` to:

```lua
local xw = XmlWriter.Create(fs, xsetting)
```

**Comment by tanruixin458** [comment]
> ```lua
> import 'System.Text'
> 
> local xsetting = XmlWriterSettings()
> xsetting.CloseOutput = true
> xsetting.Indent = true
> xsetting.Encoding = Encoding.UTF8
> xsetting.CheckCharacters = true
> xsetting.NewLineChars = Environment.NewLine
> xsetting.NewLineOnAttributes = false
> ```
> 
> and then replace `local xw = XmlWriter.Create(fs)` to:
> 
> ```lua
> local xw = XmlWriter.Create(fs, xsetting)
> ```

ok. it works, but it needs to add `import 'System'`
thank you very much!

**Comment by KENNYSOFT** [comment]
Right, I've modified.
