### ISSUE TITLE
Incorrect Potential tier in fixed weapons

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#19]
Greetings,

I have also brought this to KENNYSOFT's attention for his version.
In the V update in Korea, players could earn Absolab weapons that have 17 stars and fixed potential.

![pot1](https://cdn.discordapp.com/attachments/236180502200057856/266262675841875968/AbsoLab_fixed_PotentialKR.png)
↑ This is how it looks like in-game. You will see that there is U (Unique) and 3 lines: Damage +9%, Boss Damage +35% and Critical Rate: +10%

Using KENNYSOFT's build, if we simulate it we get the following result:

![pot2](https://cdn.discordapp.com/attachments/236180502200057856/266262675904921611/AbsoLab_fixed_PotentialKR_2.png)
↑ The simulation says the tier is Legendary (L). Is this a bug? It also says L in my GMS version. Unsure how this is in the Chinese version.

Further information:

![pot3](https://cdn.discordapp.com/attachments/236180502200057856/266262678325035021/AbsoLab_fixed_PotentialKR_3.png)

**Comment by KENNYSOFT** [comment]
@Kagamia Please see https://github.com/KENNYSOFT/WzComparerR2/issues/5 for the second bug paragraph. Thanks!

**Comment by Kagamia** [comment]
Hm... I'm not sure is it different between CMS and KMS.

Since no one from CMST tester group earns this type of the weapons, I've not even got a snapshot about them. 😢 

You could fixed it yourself in KMS version.

**Comment by Kagamia** [comment]
@KENNYSOFT 
Waiting for CMST update in half a year. 😆

**Comment by Sunaries** [comment]
@Kagamia I have no idea how to code it since I'm not really a coder myself, haha.

**Comment by Kagamia** [comment]
https://github.com/KENNYSOFT/WzComparerR2/issues/5  @KENNYSOFT has gave out a solution.

````C#
//Gear.cs, line:542-545
if (gear.Props.TryGetValue(GearPropType.fixedGrade, out value))
{
    switch(value) {
        case 2: gear.Grade = Grade.B; break;
        case 3: gear.Grade = Grade.A; break;
        case 5: gear.Grade = Grade.S; break;
        default: //since we know that there is only 2,3,5 in the game.
            gear.Grade = (GearGrade)(value - 1); //default convertion
            break;
    }
}
````

**Comment by Sunaries** [comment]
I've replaced those lines with the code you've provided, but it gives me 6 build errors.

![test](https://cdn.discordapp.com/attachments/236180502200057856/266651862462234624/te5.png)

**Comment by Sunaries** [comment]
It is lowercase? It's still giving me build errors.

**Comment by Kagamia** [comment]
`= Grade.B` -> `= GearGrade.B` It's my fault.
Typo fixed. 😆

**Comment by Sunaries** [comment]
@Kagamia Fixed. 😄 

![ab](https://cdn.discordapp.com/attachments/236180502200057856/266723538134630411/1212121.png)

In your code I see B,A and S. No SS?

```                case GearGrade.B: return "(Rare Item)";
                case GearGrade.A: return "(Epic Item)";
                case GearGrade.S: return "(Unique Item)";
                case GearGrade.SS: return "(Legendary Item)";
                case GearGrade.Special: return "(Special Item)";```

**Comment by KENNYSOFT** [comment]
No, because we don't know the specific value for SS. Before, if value is 5 then it is treated as SS.
