### ISSUE TITLE
MapRender加载失败，没有地图数据。最新版GMS V229 WZ

### ISSUE THREAD

**Issue by pessimo** [Kagamia/WzComparerR2#190]
下载了发布的最新版本，20220104。打开V229 的GMS wz之后，可以看到wz结构，

选中 obj下的所有img 用于测试，obj -> img，点击modules -> maprender 的时候什么都看不到，显示MapRender加载失败， 没有地图数据。

选择 tile -> img，点击modules -> maprender 没有报错，但是全黑。

音乐可以正常提取播放。

不太清楚是不是我的操作有问题……

**Comment by Kagamia** [comment]
maprender仅可用于地图模拟，您上述所有操作都没有选择一个地图

**Comment by pessimo** [comment]
没有选择 地图的 .img 的话 打开 modules -> maprender 会报错，我选择了之后就不会报错了。我这应该算是选了的？
![image](https://user-images.githubusercontent.com/11849439/148677571-775a7eb8-60cd-4938-b887-73cf71c4dbf4.png)

**Comment by Kagamia** [comment]
您所选择的img不指向任何一个地图。

合法的指向地图的img为`Map.wz/Map/Map[0-9]/*.img`，或`UI.wz/MapLogin*.img`

**Comment by pessimo** [comment]
按照您的指示，尝试了 UI.wz/MapLogin*.img 是可以打开的。 但是 Map.wz 下面只有 Obj，Tile 两个可以展开的项没有Map[0-9]一类的可选项。

**Comment by Kagamia** [comment]
`Map.wz`不止指Map.wz本身，还包括`Map1.wz`、`Map001.wz`等一系列扩展wz文件。

**Comment by pessimo** [comment]
感谢大佬的耐心解答。 在 Map2.wz 中找到了可以渲染打开的地图文件。
