### ISSUE TITLE
New Particle type in KMST v1.2.136 can't be opened with MapRender

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#191]
A few Explorer-specific quests added in KMST v1.2.136, specifically these 3 and a few others, can't be opened with MapRender.
![image](https://user-images.githubusercontent.com/34289651/150072285-7e17d1eb-3a24-4ef9-85a8-7a3f1c32d337.png)

![image](https://user-images.githubusercontent.com/34289651/150072371-daaa8253-ca47-44b6-87b0-44c4b5ebd5b3.png)

There seems to be something new in terms of particles.
![image](https://user-images.githubusercontent.com/34289651/150072376-ec40e447-98c5-4aed-9d55-c74c84abe45c.png)

**Comment by Kagamia** [comment]
Is there a video shows the actual effect in game?

**Comment by PirateIzzy** [comment]
> Is there a video shows the actual effect in game?

https://youtu.be/xs-DCqR-B-k

A few examples include Southperry (23:46, map ID 2100000), as well as the maps with Darkened Snails from 23:54 - 25:25 (map IDs 993166150 and 993166175). However, the exception occurs with pretty much all Destroyed Maple Island maps.

**Comment by Kagamia** [comment]
commit a fix: https://github.com/Kagamia/WzComparerR2/commit/ba3af2aa580ee0cb8720a5f0e2e7f31041635e8e

![image](https://user-images.githubusercontent.com/10445904/150630363-1906d0f7-850e-4202-a0f8-90f11aaa6fd7.png)

I think the new particles are the dark fog underground.

**Comment by PirateIzzy** [comment]
👍  closing
