### ISSUE TITLE
CMST v179 String搜索图腾类型的装备无法定位到img

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#199]
例如，搜索“轮回碑石”后双击搜索结果无法定位到对应的道具ID 1202193，但是 NodeText 手动搜索 1202193 就可以顺利定位到。
![photo_2022-03-26_19-02-43](https://user-images.githubusercontent.com/29157608/160236681-4318659c-d057-4d35-a695-da504793119d.jpg)

![photo_2022-03-26_19-08-20](https://user-images.githubusercontent.com/29157608/160236778-76258e52-247c-46e5-948c-112ed987c459.jpg)

此前未拆分WZ的客户端可以正常搜索并定位到对应的道具。不排除其它装备类型也存在该问题。

**Comment by Kagamia** [comment]
所有的图腾都存在这个问题，算是wz结构不规范导致。
该道具在string.wz的位置是accessory，但是实际物品位置在Totem。

记忆里string搜索对于装备跳转是有fallback逻辑的，我会检查一下。

**Comment by Kagamia** [comment]
更新了一个修复。
