### ISSUE TITLE
Name of certain item is in Korean gibberish

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#20]
Greetings,

The Lachelein Arcane Symbol is bugged in its name.

![lachelein1](https://cdn.discordapp.com/attachments/236180502200057856/266274855530266628/1712003.png)
↑ This appears when I simulate it.

![lachelein2](https://cdn.discordapp.com/attachments/156223807026102272/266274281061744640/unknown.png)
↑ The area was just released in GMS, and I do not see the same error there in its item name.

I used an outdated extraction program for reference and I got this:
![lachelein3](https://cdn.discordapp.com/attachments/244458112864485378/266331373671940106/tttttt45467.png)

**Comment by KENNYSOFT** [comment]
Hmm.. that's interesting. If you can find the exact hex code for that '?' character really indicates, that would be helpful.

**Comment by Kagamia** [comment]
Interesting...
I find out the bytes by tracing the source code.
GMS v.179 string.wz, position: 3413826

````C#
	using (var fs = File.OpenRead(@"C:\Users\-\Desktop\string.wz")) {
		var br = new BinaryReader(fs);
		fs.Position = 3413826;
		br.ReadByte();
		int size = br.ReadSByte(); //-24
		size = -size; //negative size -> ascii chars,  positive -> unicode chars.
		
		var buffer = br.ReadBytes(size);
		
		byte mask = 0xAA; //GMS does not encrypted now, simple XOR with mask.
		for(int i=0;i<size;i++) {
			buffer[i] ^= mask++;
		}
		
		// print hex bytes
		string.Join(" ", buffer.Select(b=>b.ToString("x2"))).Dump();

		// print decoded strings.
		Encoding.ASCII.GetString(buffer).Dump();
		Encoding.Default.GetString(buffer).Dump(); //Simplified Chinese on my laptop
		Encoding.GetEncoding(949).GetString(buffer).Dump(); //Korean code page
		Encoding.GetEncoding(1252).GetString(buffer).Dump(); //West European code page
	}
````

Output: 
````
41 72 63 61 6e 65 20 53 79 6d 62 6f 6c 3a a0 4c 61 63 68 65 6c 65 69 6e
Arcane Symbol:?Lachelein
Arcane Symbol:燣achelein
Arcane Symbol:쟊achelein
Arcane Symbol: Lachelein
````

The `?` is `a0H (1010 0000b)` here.
WcR2 treat them as ANSI string so weird chars appeared in respective Windows systems. 😆

**Comment by Sunaries** [comment]
Are there pros and cons to using ASCII compared to ANSI?

**Comment by Kagamia** [comment]
I am almost sure that GMS client use CP1252 fixed instead of local Ansi encoding.
According to [Wiki-CP1252](https://en.wikipedia.org/wiki/Windows-1252), char `a0H` means `nbsp` here, so it is rendered normally in game.

Further, variant MS clients use a suitable encoding as their default Encoding, to decode ansi strings in wz, regardless of your system language and code page.

ASCII is a primitive encoding where only contains a charset of 126 chars. A character out of range will be decoded as a fallback char `?`. 

It's necessary to add more configuration to WzLib.  I've no idea how to automaic recognize which version of wz file you are loaded. 😂

**Comment by Sunaries** [comment]
@Kagamia In the 182→183 it is fixed. No idea why it didn't affect in-game...

![t](https://cdn.discordapp.com/attachments/236180502200057856/286633889504690177/54545454545454.png)

**Comment by Kagamia** [comment]
WzLib has supported text encoding for future use.  -> https://github.com/Kagamia/WzComparerR2/commit/3da949948a4c026a8f2c3aa1a501b0def66de972
