### ISSUE TITLE
experimental feature: optimize wz folder loading speed

### ISSUE THREAD

**Issue by Kagamia** [Kagamia/WzComparerR2#200]
checkout the new pre-release version, and enable this feature manually:

![Z$9BJ0 6$MTH)HZ@8MKR7~Y](https://user-images.githubusercontent.com/10445904/162784988-9c9f3804-b6c9-4465-95d9-ec36cd2429ee.png)

waiting your feedback :)

**Comment by KENNYSOFT** [comment]
Cool, just like https://github.com/Kagamia/WzComparerR2/pull/184#issuecomment-1030829919. Will try!

**Comment by Kagamia** [comment]
@KENNYSOFT  instead of reading limited size of the img, I just compute the data range of all images in a wz file, and check if they have overlapped segment.

Compare with the old strategy, there's no FILE IO any more!

in a specific test (CMST 179), the old strategy will try extracting 280 images, with the total size of 6GB, and cost more than 10 seconds on my notebook (SAMSUNG 980).
