### ISSUE TITLE
MapRenderer: map variants and dynamic object removal

### ISSUE THREAD

**Issue by nanochromatic** [Kagamia/WzComparerR2#201]
In KMST 1.2.140, the 19th anniversary map `993200000` is covered in clouds. There appears to be several versions of this map, referenced by the 4 `miniMap` entries: `canvas` along with `canvas[1-3]`. Is there client side data to determine which objects should be rendered on the map for each version of the map? If so, it would be a great feature if MapRenderer can render each of the 4 variants separately.

If the data does not exist, would it be possible to enable a way to click and remove objects dynamically while the user is in MapRenderer?

**Comment by Kagamia** [comment]
interesting, I've never heard that, is there a video record or screenshot show what it looks like in game?

**Comment by nanochromatic** [comment]
I don't think there's video or screenshots of the different phases yet, as they're likely unlocked based on time. Here's a [video](https://youtu.be/2d4nTuFog4w?t=696) that shows what's in KMST at the moment. All the platforms are covered in clouds except the lowest one. This is also the default map configuration in the base mini map canvas (first image below).

Here are the mini map canvases from the client data:

![993200000 img miniMap canvas_new](https://user-images.githubusercontent.com/5650392/163596734-4557bfda-762a-4426-b338-f2e18dd09666.png)
![993200000 img miniMap canvas1_new](https://user-images.githubusercontent.com/5650392/163596736-25fd485c-7cca-4189-8c45-29b36f6f2647.png)
![993200000 img miniMap canvas2_new](https://user-images.githubusercontent.com/5650392/163596738-3f61e959-bb01-4ce8-affb-1cdaeeb949c1.png)
![993200000 img miniMap canvas3_new](https://user-images.githubusercontent.com/5650392/163596740-b6d57793-d591-4f1b-ab6a-efa92e3753c7.png)

**Comment by Kagamia** [comment]
thanks, looking.

**Comment by Kagamia** [comment]
looks like it is controlled by some quest state, and the clouds are enabled by tags.

plan to add command to show/hide all objects by tag, too lazy to design an UI window for it.

**Comment by Kagamia** [comment]
added the following commands to control the visibility of minimap and objects, please checkout the new version.

```
/minimap list
/minimap set (name)
/scene tag list
/scene tag show (name)
/scene tag hide (name)
/scene tag reset
```

**Comment by KENNYSOFT** [comment]
I and @PirateIzzy are experiencing the compile error. 😭

![image](https://cdn.discordapp.com/attachments/398087600428285956/964976717779333140/unknown.png)

**Comment by Kagamia** [comment]
@KENNYSOFT interesting, neither CI-pipeline and my local environment report this error.

ok, quick fix.

**Comment by KENNYSOFT** [comment]
Right, wondering why the error occurs. 🤔 Using VS 2019.

**Comment by Kagamia** [comment]
add more command.
```
/scene tag info
/scene tag reset (name)
/scene tag set-default (true/false)
```
support backTags
support multiple names in once call.

**Comment by Kagamia** [comment]
VS2022 (17.1.4) from my side, that could be a difference? (with newer version of roslyn)

checked build pipeline, it also use vs2022 as default build tool.
```
CoreCompile:
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /highentropyva- /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\CharaSimResource.dll /resource:obj\Release\CharaSimResource.Resource.resources /target:library /utf8output /langversion:7.3 Properties\AssemblyInfo.cs Resource.Designer.cs
  CompilerServer: server - server processed compilation - 3b39bafe-5a4e-456f-9918-e6425eae1eae

```

**Comment by nanochromatic** [comment]
This looks great, thanks for the quick turnaround!

One behavior I've noticed: using `/scene tag set-default false` on `993200000` will also disable the background. I think this is because the background images have an empty `backTags` property. Using `/scene tag list` on the map will display an empty tag as the first entry, which is likely the empty `backTag`. Is there a better way of handling empty tags?

**Comment by Kagamia** [comment]
@nanochromatic 
bug fix. 

object with empty tags/backtags should always be visible.

**Comment by nanochromatic** [comment]
That resolved it, everything looks good! Closing out this issue 💯
