### ISSUE TITLE
地圖模擬器 截圖儲存增加去背功能

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#203]
原本
![image](https://user-images.githubusercontent.com/37591855/166671009-c9773282-f8ea-484a-bf40-a5a6bd0b9467.png)

別家的程式去背功能(地圖是直接只擷取物件存成圖)
![image](https://user-images.githubusercontent.com/37591855/166671049-4f7dd890-d1df-4287-99b9-d327aec5d623.png)

**Comment by Kagamia** [comment]
似乎只和这一句相关：
https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.MapRender/FrmMapRender2.cs#L822

`GraphicsDevice.Clear(Color.Black);` 强制把截图重置成了黑色背景（为了粒子特效等非常规blendstate的元素可以被截图），使这个参数可配置就可以解决问题了。

**Comment by Kagamia** [comment]
已经在最新的版本中修复（详见#236）
