### ISSUE TITLE
能不能提供提取的算法呀，我需要把WZ还原成原本的文件

### ISSUE THREAD

**Issue by HoneyTorres** [Kagamia/WzComparerR2#206]
RT，因为我不会C#，所以。。。。需要这样的

**Comment by Kagamia** [comment]
虽然不知道您要表达什么，但是wcR2是依MIT协议开源的，您可以自由查看，使用，修改及分发源代码。

**Comment by HoneyTorres** [comment]
> 
害，可能我需要装一个VS来弄弄，主要是不想麻烦，想直接拿算法来写JAVA
