### ISSUE TITLE
Question: meaning of Wz_Uol ?

### ISSUE THREAD

**Issue by ppodds** [Kagamia/WzComparerR2#208]
What is the meaning of Wz_Uol property? 

Thanks!

![image](https://user-images.githubusercontent.com/11408727/184307187-a8700a82-d7d4-4737-ac88-ecc3fbd57da5.png)

**Comment by Kagamia** [comment]
`Uol` is a well-known data type in wz file, which means a 'soft link' node in wz data structure.
