### ISSUE TITLE
Unable to render map 410007000 in KMST 1.2.1145

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#209]
Other maps in Odium are fine.

Already tried ```/map 410007000``` command, click on portal or the dot on world map, none of them works.

Actual map in game behavior: https://www.youtube.com/watch?v=8gwL9gbvqTk

**Comment by Kagamia** [comment]
Just update my client.
I assume that the new portal type would cause indexOutOfRange error at somewhere.

**Comment by Kagamia** [comment]
push a commit here.
Now there're 18 different portal editor canvas in wz file, but I'm not sure if the mapping is correct.

**Comment by HikariCalyx** [comment]
Not fixed yet
