### ISSUE TITLE
是否存在批量提取数据的方法

### ISSUE THREAD

**Issue by photonrain** [Kagamia/WzComparerR2#210]
您好，我希望批量提取WZ中潜能数据，但我发现潜能栏目中的词条过多。如果手动将WZ数据记录下来，这会是非常繁琐的工作。请问能否批量将WZ的数据写入TXT文件中（或其他形式），方便进一步处理（进行概率计算或数据可视化等）。希望您给出建议，谢谢您！

**Comment by Kagamia** [comment]
可以使用lua script插件，直接调用[Potential.cs](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.Common/CharaSim/Potential.cs)类型加载潜能数据并输出。

**Comment by photonrain** [comment]
谢谢您，我会尝试使用lua script插件
