### ISSUE TITLE
HTML Comparison sometimes does not account for <> brackets

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#214]
So I noticed that sometimes, the values inside a <> bracket are truncated in a comparison report, likely because the report assumes that we're adding HTML tags. For example, achievement 1422 merely says `Obtain`, while 1184 shows `Complete <[Silent Crusade] Arkarium, the Guardian of Time>`, likely because the first < is followed by a [

![image](https://user-images.githubusercontent.com/34289651/193644935-a8c30ddd-bc1c-4e5d-bdf0-f470cbe72092.png)

In WzCR2 itself, 1422 shows `Obtain <Adventure Deep Dark Critical Ring>`

![image](https://user-images.githubusercontent.com/34289651/193645148-eb5fab77-2765-46d6-a4e2-db2249a710ad.png)

Another example includes quests. Quest 36341 shows up as `The book Wiz mentioned is a history book called the #b#k.` in the comparison report, where the text `<Chronicles of Ellin Forest>` is truncated.

![image](https://user-images.githubusercontent.com/34289651/193645818-0d6df8fc-27da-43e6-8b87-806397442f4d.png)

In WzCR2 itself, the text correctly shows up as `The book Wiz mentioned is a history book called the #b<Chronicles of Ellin Forest>#k.`
![image](https://user-images.githubusercontent.com/34289651/193646005-1a612c94-42d3-4207-8c47-a7f14e96da31.png)

And in game, it shows the text properly formatted with `<Chronicles of Ellin Forest>` in blue.
![image](https://user-images.githubusercontent.com/34289651/193645487-83e7307f-834f-4789-a707-9bd19fe4b97b.png)

**Comment by Kagamia** [comment]
Looks like all of the html texts are not escaped properly, add `HtmlEncode` for it.

**Comment by PirateIzzy** [comment]
Working now, thank you.
