### ISSUE TITLE
does it infinite loop?

### ISSUE THREAD

**Issue by anonymous5l** [Kagamia/WzComparerR2#218]
https://github.com/Kagamia/WzComparerR2/blob/cf1838e7e7d68b7317ae20405af70888b65c3cfa/WzComparerR2.WzLib/Wz_Image.cs#L328

**Comment by Kagamia** [comment]
What is the context of your question? Which wz version are you looking?

**Comment by anonymous5l** [comment]
i'm trying recode it to another language. just curious.
