### ISSUE TITLE
Ampersand issue

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#22]
Greetings,

![item](https://cdn.discordapp.com/attachments/236180502200057856/268942770452824064/1492196.png)

There is an issue with the use of an ampersand of this item with fixed Potential. See: `ATT _M.ATT: +10`
This should be: `ATT & M.ATT: +10` - This could easily be fixed by adding another ampersand, however I cannot find the code for this. I've tried searching for "ATT" and "M.ATT" but to no avail.

**Comment by Kagamia** [comment]
Do you use GDI to render potentials?
There's a format flag called `TextFormatFlags.NoPrefix`. Reference to [msdn](https://msdn.microsoft.com/en-us/library/system.windows.forms.textformatflags(v=vs.110).aspx). It also contains a example:

````C#
private void RenderText6(PaintEventArgs e)
{
    // use '|' operator here.
    TextFormatFlags flags = TextFormatFlags.Bottom | TextFormatFlags.EndEllipsis;
    TextRenderer.DrawText(e.Graphics, "This is some text that will be clipped at the end.", this.Font,
        new Rectangle(10, 10, 100, 50), SystemColors.ControlText, flags);
}
````

**Comment by Sunaries** [comment]
@Kagamia Yes, I do. However I use the code from KENNYSOFT.
Here is a diff checker: https://www.diffchecker.com/4mTcanZj
Left is my version, right is yours. 

I'm afraid of adding your code as well since it might conflict.

**Comment by Sunaries** [comment]
@Kagamia From that diff checker, I added your code from https://github.com/Kagamia/WzComparerR2/commit/2e3af7057d4b784a10bf000ba536eb9255d2ffc6 (with the exception of GearTooltipRender2.cs commit because that changes my font not to correspond with GMS)
I get the following result:

![test](https://cdn.discordapp.com/attachments/236180502200057856/269845076329496576/1492196.png)

Also, with this code when I try to simulate certain items I get many **NullReferenceException was unhandled** errors.

**Comment by Kagamia** [comment]
You should append the flag to everywhere you render the potentials, such as ring option, potentials, additional potentials in GearRenderer, potentials in SetItemRenderer.

eg: for Kennysoft's version:
[GearTooltipRender2.cs](https://github.com/KENNYSOFT/WzComparerR2/blob/master/WzComparerR2/CharaSimControl/GearTooltipRender2.cs) line: 629-
````C#
foreach (Potential potential in Gear.Options)
{
    if (potential != null)
    {
        TextRenderer.DrawText(g, potential.ConvertSummary(), GearGraphics.EquipDetailFont2, new Point(13, picH), Color.White, TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);
        picH += 15;
        }
    }
}
````
line: 669-
````C#
foreach (Potential potential in Gear.AdditionalOptions)
{
    if (potential != null)
    {
        TextRenderer.DrawText(g, "+ " + potential.ConvertSummary(), GearGraphics.EquipDetailFont2, new Point(13, picH), Color.White, TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix);
        picH += 15;
    }
}
````
