### ISSUE TITLE
怎么可以显示出一个完整的扎昆或者黑龙的boss图呢

### ISSUE THREAD

**Issue by HoneyTorres** [Kagamia/WzComparerR2#223]
现在是只有单个的怪物，比如只能显示8800000的主体，不能显示加手的

**Comment by Kagamia** [comment]
“自己PS”

每个部位都是独立的怪物ID，WC没有任何信息把他们拼凑在一起。

**Comment by HoneyTorres** [comment]
> “自己PS”
> 
> 每个部位都是独立的怪物ID，WC没有任何信息把他们拼凑在一起。

阿西巴，其实有坐标可以开发一个，目前我只能自己ps一下了

**Comment by Kagamia** [comment]
记忆里很早开发maprender的时候试过，扎昆其实所有部位的初始坐标是在同一个点上，通过程序绘图很容易把它们合并到一起。
