### ISSUE TITLE
WZ Format Break

### ISSUE THREAD

**Issue by AJ4real** [Kagamia/WzComparerR2#229]
Version: 243
File: MapleStory\Data\Effect\Effect_024.wz
Unknown image name: RawData

https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Wz_Image.cs#L177
`tag` variable is `RawData`

**Comment by Kagamia** [comment]
> Version: 243

Which client region?

**Comment by Kagamia** [comment]
just try to fix it.

**Comment by KENNYSOFT** [comment]
GMS v243, Data\Effect\Effect_024.wz\lut.img\0
