### ISSUE TITLE
Inaccurate comparer report

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#23]
Today, GMS has updated to version 181. I tried to use the comparer feature from 180 -> 181.
If I look into the comparison folder for 180->181, I see it generates **a lot of files** - Files that already exist and are probably not being changed or added in this patch. It took this comparison 33 minutes and there's already more than 1.5 GB worth of data in this comparison folder...

The patch itself is 73 MB, so the comparison should be fairly quick. 
This is a common issue I've gotten in the past before but I never reported it. But now it is annoying to see my space being taken by redundant data and it taking too much time.
One example, in the Map folder I now see BlackHeaven data - This is old and is not changed at all. 
If I click on the HTML file for Character.wz, it says 17911 changes. That's overkill for such a small patch.

Here is a visual example)

![test](https://cdn.discordapp.com/attachments/236180502200057856/276798706735382529/34344334.png)

↑ There is no change with this NPC yet it shows up in the comparison.

Because of this it is hard to distinguish what is really changed and what has been removed and added from looking at the different folders. Checking the String.wz HTML file says a few changes, so that should be accurate, but everything else isn't.

Do you have an idea why it is outputting existing files from any .wz file that shouldn't be there? I believe this is only happening with GMS because I never experienced this with the Korean version.

**EDIT:** A new patch (version 182) was released for GMS. It does the same thing! Another comparison folder filled with images of data that are already present. This doesn't happen with KMS since I also compared a new patch from the test server today...

**Comment by KENNYSOFT** [comment]
For reference: GMS download links

v182
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.exe
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.z01
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.z02
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.z03
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.z04
http://download2.nexon.net/Game/MapleStory/FullVersion/182/MSSetupv182.z05

v181
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.exe
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.z01
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.z02
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.z03
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.z04
http://download2.nexon.net/Game/MapleStory/FullVersion/181/MSSetupv181.z05

**Comment by Kagamia** [comment]
Client compressing patch. 😆

**Comment by KENNYSOFT** [comment]
Yes, I agree with @Kagamia. There "IS" a change in 0002100.img, which deletes a image and replace it with link. It can decrease client size, like KMS did.

**Comment by Kagamia** [comment]
KMS/CMS replace the linked images with a 1*1 size dummy canvas, but GMS use a "(link)" string stuff instead according to the screenshot.
Funny. 😆

**Comment by KENNYSOFT** [comment]
@Kagamia No, that's not a string. It's just linked node and I added a function for follow linkNode in comparer. See https://github.com/KENNYSOFT/WzComparerR2/blob/master/WzComparerR2/Comparer/EasyComparer.cs : line 507.

**Comment by Kagamia** [comment]
So that is why it takes more time to compare. 😃 

But I heard that GMS client has compressed since v177?

**Comment by Sunaries** [comment]
That particular change for that NPC also occurred during the comparison of 180->181. Something's not right.

Also, GMS has their client optimized and reduced in size a few patches ago. Again, this is only happening with GMS. I've tested: KMS, JMS, MSEA and it works fine.

**Comment by Kagamia** [comment]
Maybe GMS has not fully completed optimizing during previous patch.

You could compare the file size of Npc.wz from v.180 to v.182. The top of the report webpage also shows the file size before and after patching.

**Comment by Sunaries** [comment]
@Kagamia If that were the case, then it would be told in a patch note. I experienced this in the past where it outputted existing files.

**Comment by KENNYSOFT** [comment]
I downloaded GMS v181/v182 and compared these. I found that it really "IS" a change; they move some PNGs to other image and adjust links. I don't know why they did like this, but one thing is that they have not to tell this in a patch note. Below shows the difference in v181/v182.

![image](https://cloud.githubusercontent.com/assets/6624567/22615005/e4272244-eace-11e6-866e-b6e9d6cc9481.png)
▲ v181 01680075.img

![image](https://cloud.githubusercontent.com/assets/6624567/22615008/efd2fe38-eace-11e6-83f3-cfb8a8bc671c.png)
▲ v181 01680081.img

![image](https://cloud.githubusercontent.com/assets/6624567/22615012/fc55f5d4-eace-11e6-9d7e-f25533fd0e44.png)
▲ v182 01680075.img

![image](https://cloud.githubusercontent.com/assets/6624567/22615014/0221aeb8-eacf-11e6-9ae1-2da269461a74.png)
▲ v182 01680081.img

**Comment by Sunaries** [comment]
Hmm. A solution to remove the linked node comparisons is to remove that particular code that you added @KENNYSOFT ?

**Comment by KENNYSOFT** [comment]
No, the code that I added is just for print the destination node, not for comparing. If you want to skip node if the linked item is same, then you should change something in EasyCompare.cs.

**Comment by Sunaries** [comment]
GMS released new update today. Version 183.

![183](https://cdn.discordapp.com/attachments/236180502200057856/286618914933309440/182to183.png)
▲ 182 → 183

![182](https://cdn.discordapp.com/attachments/236180502200057856/286618909757538304/181to182.png)
▲ 181 → 182

Comparing for GMS takes incredibly long and so hard to notice new/modified content. 😢

**Comment by Kagamia** [comment]
2001.img->2012.img->2010.img
Nexon can't find the right place. 😃

**Comment by Kagamia** [comment]
A trial feature is committed.  https://github.com/Kagamia/WzComparerR2/commit/c7139991d31848b8339cb3421339750fa8f48235

Maybe it is useful for reducing the file size of comparing reports.
