### ISSUE TITLE
大佬可不可以提供一版Wzlib动态dll库

### ISSUE THREAD

**Issue by Zhanghao0150** [Kagamia/WzComparerR2#232]
然后加上接口使用说明，就可以别的语言调用了，我不会C#啊。看不懂，跪求了。

**Comment by Kagamia** [comment]
抱歉，代码是开源的，您可以自己完成这些工作，或者使用您熟悉语言对应的wz解析库。

**Comment by Zhanghao0150** [comment]
好吧，有java版本的wz解析库吗

**Comment by Kagamia** [comment]
可以参考其repo，比如 https://github.com/Brenterino/jwzlib

**Comment by Zhanghao0150** [comment]
好的 谢谢
