### ISSUE TITLE
更新了0901之后，动画提取有点问题。

### ISSUE THREAD

**Issue by WarshawskyG** [Kagamia/WzComparerR2#233]
<img width="218" alt="2221" src="https://github.com/Kagamia/WzComparerR2/assets/91048301/9258b362-b85f-4a0c-bc38-c9812ccc00ac">
下载了0905之后也是一样的问题，之前的版本没有遇到过。

**Comment by WarshawskyG** [comment]
<img width="131" alt="32131" src="https://github.com/Kagamia/WzComparerR2/assets/91048301/cb24dcda-a2a6-4ea6-9fb1-82e94d4c3004">
单个图片提取没有问题，技能动画、怪物模型动画等等提取都有问题。之后我换回2.1.1使用之后发现，读取Base.wz，（确认了选项里勾选了自动检测扩展）出现这样的情况。我怀疑是我VS出现了问题，但是不知道问题出在了哪里。希望这点线索可以帮助快速定位。

**Comment by WarshawskyG** [comment]
<img width="743" alt="捕获" src="https://github.com/Kagamia/WzComparerR2/assets/91048301/6fc80764-ef24-4c37-a99f-b35713adad65">
报错显示是在这里

**Comment by WarshawskyG** [comment]
<img width="743" alt="捕获" src="https://github.com/Kagamia/WzComparerR2/assets/91048301/3665f4bb-264b-491f-a701-a20415408c7b">
报错显示是在这里

**Comment by WarshawskyG** [comment]
#4

**Comment by WarshawskyG** [comment]
我找朋友拿了20230128版本，一切正常。不太明白问题出在哪。。
20230901版本之前运行也是一切正常，但是使用20230905版本之后，出现了报错，然后换回20230901版本也出现同样的问题。。。

**Comment by Kagamia** [comment]
感谢提交bug

错误源于上次工程更新，新的sdk style工程文件和以前不一致，已经修复。
