### ISSUE TITLE
QuickView NPC Tooltip Render doesn't display NPCs with an outlinked Default thumbnail

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#235]
I noticed that for NPCs that use the "default" thumbnail will have that image rendered in the NPC tooltip:
![Screenshot 2023-09-15 113830](https://github.com/Kagamia/WzComparerR2/assets/34289651/a49692f1-0a06-4062-84f0-ee1e11b7e51f)
![2161012](https://github.com/Kagamia/WzComparerR2/assets/34289651/6c096a60-401b-45a4-a06e-7b4ded9b33db)

But if the thumbnail is outlinked to another image, the NPC tooltip will not render the thumbnail:
![Screenshot 2023-09-15 113856](https://github.com/Kagamia/WzComparerR2/assets/34289651/69602ae6-6951-474e-bf6b-c7e07eca4701)
![9073005](https://github.com/Kagamia/WzComparerR2/assets/34289651/68b9bba8-192e-47f4-8a14-7bd5a08af567)

This will be a bigger issue once other regions implement the new Canvas folders, since all of the default thumbnails will outlink to the Canvas folders (note the path `Npc/_Canvas/2161012.img/info/default`:
![Screenshot 2023-09-15 210057](https://github.com/Kagamia/WzComparerR2/assets/34289651/d10df700-8e9c-4901-ab8b-db3e5dcd95b8)

**Comment by Kagamia** [comment]
Fixed. 

Thanks for reporting, it is more like a very old bug.
