### ISSUE TITLE
MaxLv + Additional Lv Preview for Skills

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#24]
Hey there,

As I was trying this feature:

![1](https://cdn.discordapp.com/attachments/236180502200057856/283687232504725514/Naamloos.png)

I came across a missing option. Someone was asking me if I could give the data of **(MaxLv)** + 2**.
I've came to the conclusion that the program only works when the skill has a maximum level of 30. The program ignores other skills that have a maximum level of 15 or 20 **when choosing the + 2 option**.

Example)

![2](https://cdn.discordapp.com/attachments/236180502200057856/283687233897103360/skill_2320013.png)
Skill: Blessed Harmony (2320013)

![2](https://cdn.discordapp.com/attachments/236180502200057856/283687233897103360/skill_2320013.png)

The person asked me if I could retrieve the data of this skill beyond its max level. I couldn't.
This is the reason ↓

![3](https://cdn.discordapp.com/attachments/236180502200057856/283687236221009920/skill_2320013_2.png)

The program is missing the `fixLevel` variable. This variable means that you cannot extend the skill level beyond the maximum level (which is 1 in this case). This can be added with orange text next to 'Undispellable (notRemoved) as 'Fixed Maximum Lv'.
There is another issue, however. The Beast Tamer class has a few skills with a maximum level of 10, 15 and even 20. The program can only recognize a maximum level of 30 which means you cannot obtain skill info beyond the maximum level of those skills.

- Add `fixLevel` as 'Fixed Maximum Lv' to skill preview
- Make it so that the program not only recognize a maximum level of 30, but other values as well.

**Comment by Kagamia** [comment]
Technically, it's based on whether the skill has a property named 'combatOrders' and value equals 1. It's common on almost all of 4th job skills. 'MaxLevel + 2' default level is designed for CO at first.

Of course, 'MaxLevel + 2' is not the limit, you can press '+-[]' key to adjust skill level, up to maximum lv.100, if the skill could buffed by CO.

`fixLevel` is a flag modifier, means that the value could only be 0/1, not a specific level.

**Comment by Sunaries** [comment]
@Kagamia Ah, so the + and - keys work while you preview it. I always thought you had to press it when you had that menu in front of you. Thanks for the explanation. :)
