### ISSUE TITLE
MapRender: png output on maps with transparent objects

### ISSUE THREAD

**Issue by nanochromatic** [Kagamia/WzComparerR2#240]
I've noticed the png output on maps with transparent objects can be overexposed if background argb values are used. Setting the background argb value to `00ffffff` can result in bright objects rendered in the png (see the row of four yellow bushes in the second image below). The map has transparent objects even in the no-argb png output. Unsure if this has an impact on the png output behavior. 

Tested below with KMS v383, map id 309000000. First image has no argb value set, second image set to `00ffffff`.

![no-argb](https://github.com/Kagamia/WzComparerR2/assets/5650392/299e13b0-5dee-4bd6-8495-027536bbad4f)
![00ffffff](https://github.com/Kagamia/WzComparerR2/assets/5650392/1ecff1a5-2def-4a22-be4b-d14b519fbc48)

In-game references
![image](https://github.com/Kagamia/WzComparerR2/assets/5650392/278b6a37-8a38-4d5e-a518-ad2b4d1cbf9d)
![image](https://github.com/Kagamia/WzComparerR2/assets/5650392/9cdff0eb-cf2a-43de-be3a-88fbaa4708fb)
[YouTube video](https://www.youtube.com/watch?v=Le21eHjdq8o)

**Comment by Kagamia** [comment]
This is not an expected behavior, will take a look.

**Comment by Kagamia** [comment]
Fixed by reseting alpha to 255 if user provides an opaque bgcolor.

**Comment by nanochromatic** [comment]
Tested the new build and can confirm setting an opaque bgcolor now outputs a png with no transparency. 👍
