### ISSUE TITLE
KMS和KMST客户端比对后有部分新增图片未输出到对比档案

### ISSUE THREAD

**Issue by haoren22ge** [Kagamia/WzComparerR2#241]
我对比KMSv1.2.382和KMSTv1.2.162时，发现map.wz中部分新增图片未显示在对比结果文档中：
![image](https://github.com/Kagamia/WzComparerR2/assets/11991876/55bdc2f3-04ff-47fc-833a-38abc2d3366e)
![image](https://github.com/Kagamia/WzComparerR2/assets/11991876/ab073eef-2dd9-4abc-aefd-1447947b8420)

这个问题在似乎在KMST将图集单独拿出来后经常发生。
我使用的厕所版本：
![image](https://github.com/Kagamia/WzComparerR2/assets/11991876/7474eb1f-fdb1-478f-a9ef-c0e1707d4f2d)

**Comment by Kagamia** [comment]
大概能猜到原因是输出带链接的png时，resolve link没有正确以当前wz_structure进行溯源，而是根据全局wc加载的全部wz文件组进行寻找的。
当寻找不到时就发生了fallback，输出了原始1*1的placeholder图片。

只不过，我这里没有两个客户端，不太好验证....

**Comment by Kagamia** [comment]
实际原因为输出图片并未使用完整wz路径命名，在客户端引入canvas强制link后，图片引用节点与实际存储节点会生成相同的文件名，导致文件被错误替换。

使用完整wz路径后解决了问题。
