### ISSUE TITLE
对比客户端的文件，感觉好像把每个文件都对比了一下

### ISSUE THREAD

**Issue by WarshawskyG** [Kagamia/WzComparerR2#244]
这次对比CMS v202和v203的时候出现的问题。这个问题之前在对比国际服的时候也曾出现过。
只是对比了2秒左右，Character里面的图片就多达6000多个。
<img width="540" alt="12221" src="https://github.com/Kagamia/WzComparerR2/assets/91048301/e86e7883-c47d-4c65-801d-396457b7891d">
不知道问题出在了哪里

**Comment by Kagamia** [comment]
客户端所有canvas资源全面转link集中管理了。

这是几个月前KMS的改动。

**Comment by WarshawskyG** [comment]
明白了，感谢回复
