### ISSUE TITLE
帧动画合成GIF的问题，每一帧的位置有偏差

### ISSUE THREAD

**Issue by taiyuuki** [Kagamia/WzComparerR2#247]
我下载了20231203.2这个版本，发现有些帧动画，每帧图片的尺寸不一样时，合成GIF就会对不上。

![preview](https://github.com/Kagamia/WzComparerR2/assets/56967520/49840a66-4f84-46b1-9671-739023a14c45)

**Comment by Kagamia** [comment]
这是预期行为，因为您选中的不是一个gif节点。

**Comment by Kagamia** [comment]
显然您前后两张截图选中的是两个不同的wz节点。

**Comment by Kagamia** [comment]
几个月前，KMS试图把游戏中所有的Canvas资源(也就是wz_png)，集中移动到单独的文件夹(也就是_Canvas)和img下，在原来位置上以placeholder+__outlink的方式逻辑引用。

在第一张截图中，您选中的正是这个_Canvas文件夹下的节点，该img下只有资源文件，没有帧描述信息，这就是为什么我解释“您选中的不是一个gif节点”。

**Comment by taiyuuki** [comment]
> 显然您前后两张截图选中的是两个不同的wz节点。

确实是不同的节点，是我疏忽了，没仔细看节点的路径，甚至没注意到连数据都不一样，再次感谢您的回复！
