### ISSUE TITLE
All png files are not saved

### ISSUE THREAD

**Issue by nyanyahee** [Kagamia/WzComparerR2#249]
![image](https://github.com/Kagamia/WzComparerR2/assets/159318970/9882e20b-4cf2-4273-b89e-06c2ec45e675)

I tested with this source, but there's no walk.1.mailArm. I can't save a few other arm files as well

![image](https://github.com/Kagamia/WzComparerR2/assets/159318970/3b19fc7c-dac6-4c8a-9323-b851fe0b38d9)

**Comment by nyanyahee** [comment]
![image](https://github.com/Kagamia/WzComparerR2/assets/159318970/fa48d26b-8bfe-47ba-9b75-b7060c03cc6b)
I modified line 38

**Comment by Kagamia** [comment]
`Character/Longcoat/01051405.img/walk1/1/mailArm/_outlink`: Character/Longcoat/_Canvas/**01050335**.img/walk1/1/mailArm

**Comment by nyanyahee** [comment]
But some arm files are missing
![스크린샷 2024-02-08 135826](https://github.com/Kagamia/WzComparerR2/assets/159318970/945dfe27-0053-425e-bf8e-6204c648cddb)

**Comment by Kagamia** [comment]
So what's your intention and expectation?

If you're trying to save all png resources of item 01051405, you can hierarchically loop all wz_png nodes and **resolve links** when dumping. Never touch `_Canvas` folder directly.

**Comment by nyanyahee** [comment]
I want to know how to save each one at once because it takes a long time and is cumbersome to save each one myself

I don't know how to fix it because some files are missing even if I do the above method

**Comment by Kagamia** [comment]
If you'are handling `_Canavs` image, you can't say 'some files are missing' because they didn't exist from the beginning.

**Comment by nanpuhaha** [comment]
> So what's your intention and expectation?
> 
> If you're trying to save all png resources of item 01051405, you can hierarchically loop all wz_png nodes and **resolve links** when dumping. Never touch `_Canvas` folder directly.

@Kagamia Hi, thank you.

How can I **resolve link** on Lua script? I cannot find "outlink" from [Wz_Image.cs](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Wz_Image.cs), [Wz_Node.cs](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Wz_Node.cs), [Ms_Image.cs](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Ms_Image.cs).

I probably need to use the [GetLinkedSourceNode](
https://github.com/Kagamia/WzComparerR2/blob/75420f810265a02516cb85c0de2ebe2b5d8bed93/WzComparerR2.Common/Wz_NodeExtension2.cs#L11)function, but I don't know how to use it in a Lua script. How can I use [GetLinkedSourceNode](
https://github.com/Kagamia/WzComparerR2/blob/75420f810265a02516cb85c0de2ebe2b5d8bed93/WzComparerR2.Common/Wz_NodeExtension2.cs#L11) on Lua script? I hope to check image info like [MainForm.cs#L1199](https://github.com/Kagamia/WzComparerR2/blob/75420f810265a02516cb85c0de2ebe2b5d8bed93/WzComparerR2/MainForm.cs#L1199)

**Comment by Kagamia** [comment]
I believe you can implement an equivalent version in lua.
Here's the example (not fully tested, use at your own risk):

```lua
import 'WzComparerR2.PluginBase'
import 'WzComparerR2.WzLib'

function string:split(sep)
  local t = {}
  for str in self:gmatch("([^"..sep.."]+)") do
    table.insert(t, str)
  end
  return t
end

local function GetLinkedSourceNode(node)
  local linkNode = node.Nodes["_inlink"]
  if linkNode and type(linkNode.Value) == "string" then
    local img = Wz_NodeExtension.GetNodeWzImage(node)
    if img then
      return img.Node.FindNodeByPath(true, linkNode.Value:split("/"))
    end
  end
  
  linkNode = node.Nodes["_outlink"]
  if linkNode and type(linkNode.Value) == "string" then
    return PluginManager.FindWz(linkNode.Value)
  end
  
  return node
end

-- get body node
local body = PluginManager.FindWz([[Character\00002000.img\walk1\0\body]])
local png = body.Value
env:WriteLine("{0},w={1},h={2},path={3}", png:GetType().Name, png.Width, png.Height, body.FullPathToFile)

local linkedNode = GetLinkedSourceNode(body)
png = linkedNode.Value
env:WriteLine("{0},w={1},h={2},path={3}", png:GetType().Name, png.Width, png.Height, linkedNode.FullPathToFile)
```

Sample output:
```
Wz_Png,w=1,h=1,path=Character\00002000.img\walk1\0\body
Wz_Png,w=27,h=32,path=Character\_Canvas\00002000.img\walk1\0\body
```

**Comment by Kagamia** [comment]
@nanpuhaha Push a commit https://github.com/Kagamia/WzComparerR2/commit/15a78210850f9502747ae7103e5ba6dc185722df to improve the behavior, now you can pass `FindWz` as a callback argument:

```Lua
import 'WzComparerR2.PluginBase'
import 'WzComparerR2.WzLib'
import 'WzComparerR2.Common'

local body = PluginManager.FindWz([[Character\00002000.img\walk1\0\body]])
local png = body.Value
env:WriteLine("{0},w={1},h={2},path={3}", png:GetType().Name, png.Width, png.Height, body.FullPathToFile)

local linkedNode = Wz_NodeExtension2.GetLinkedSourceNode(body, function(path) return PluginManager.FindWz(path); end)
png = linkedNode.Value
env:WriteLine("{0},w={1},h={2},path={3}", png:GetType().Name, png.Width, png.Height, linkedNode.FullPathToFile)
```
