### ISSUE TITLE
Error in Avatar initialization

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#25]
Hi, long to see you.

There is an error on avatar initialization: cannot load, like below image.

![image](https://user-images.githubusercontent.com/6624567/27292744-57495dba-554f-11e7-897b-ff181e3d783e.png)

I found that you've changed CharaSimLoader_WzFileFinding function in 5cc64024963e4537796f4319f7885a8f977e0337, like below box.

>                for (int i = 1; i < fullPath.Length && searchNode != null; i++)
>                {
>                    searchNode = searchNode.Nodes[fullPath[i]];`

Then, Nodes' [] operator does NOT ignore cases, so fullPath must be same with desired WzNode's path, also case matched.

Now, [AvatarCanvas.cs#L42](https://github.com/Kagamia/WzComparerR2/blob/5cc64024963e4537796f4319f7885a8f977e0337/WzComparerR2.Avatar/AvatarCanvas.cs#L42) is `return LoadZ(PluginBase.PluginManager.FindWz("Base\\Zmap.img"));` and KMS has only _Base\\**z**map.img_, so this initializing function fails; which means you cannot use Avatar tab functions.

The fix is very simple: just correct **Z** as _**z**_. See https://github.com/KENNYSOFT/WzComparerR2/commit/21f3f6409a65c7840e7da9c01fae61cf35a2fc4d for reference.

Thank you.

**Comment by Kagamia** [comment]
fixed in https://github.com/Kagamia/WzComparerR2/commit/3c27c980031163bee7caadedfca2468ad675ff09 :)
