### ISSUE TITLE
武器伤害上限加入单位

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#252]
此为 [CMS V204 起的改动](https://mxdact.web.sdo.com/project/v204/02.html#con)。由于目前游戏内没有自带超过1亿伤害上限的装备，所以没有加入“亿”这个单位的支持。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/8390067e-d9d9-4ce9-bccb-f08c97318c0d)

ItemStringHelper.cs, ln 104:
```
 case GearPropType.limitBreak: return "伤害上限突破至" + (value / 10000).ToString() + "万 " + value.ToString().Substring(value.ToString().Length-4, 4) + "。";
```

修改后的结果
![1452205](https://github.com/Kagamia/WzComparerR2/assets/29157608/d41d85fc-d08f-44d8-8adb-d0d0cd95100b)

**Comment by Kagamia** [comment]
已经加入。

感谢您的汇报:)
