### ISSUE TITLE
只会出现在 BUFF 中的技能 500061002 中的数值 #strX 无法正确被解析，能否将技能效果说明的部分隐藏

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#253]
在 WzComparerR2 中，这一技能只被错误解析了前面的 #s ，后面的 trX 的部分因 common 下面缺少 strX 变量，未能被解析。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/edc7f9c3-12b9-4fe7-a1a0-507ac14a5c94)

在实际游戏中，该技能的关联技能 500004020 中， strX为3*x。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/ff9a5e26-979b-4d75-8511-74dcb6e3f6da)

**Comment by HikariCalyx** [comment]
补充：500061002 应该是出现在顶部 buff 提示上面的技能，下方并不会显示任何当前等级的技能效果。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/fcac5029-39c0-4529-8c79-13ae06261234)

**Comment by Kagamia** [comment]
该技能没有strX这个属性，wc的行为符合预期。
![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/c2829d78-f3a8-42d7-a272-e48454535319)
