### ISSUE TITLE
KMST 1170 到 1171 更新文件有特别变化

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#255]
根据 KENNYSOFT 的 Discord 频道说明，直接从已有的 KMST 1170 更新到 1171 是不行的，必须按照以下顺序应用更新：
```
http://maplestory.dn.nexoncdn.co.kr/PatchT/01170/Minor/01to04.patch
http://maplestory.dn.nexoncdn.co.kr/PatchT/01171/01170to01171.patch
http://maplestory.dn.nexoncdn.co.kr/PatchT/01171/Minor/01to02.patch
```
目前还不知道如何判定当前的客户端是哪一种minor patch，只能挨个尝试。不排除正式客户端也会实装这一更新 Minor Patch 的方式。

希望加入的功能：在 Patcher 内加一个针对 KMST 1170+ 的 Minor Patch 的路径的支持。可以不着急立即加入，等待 KMS 实装后在更新。

**Comment by Kagamia** [comment]
我在思考添加一个额外参数，允许动态指定UI上最多出现的版本号输入框数量。
似乎一直有用户扩展它用于侦测客户端下载版本，而实际只用到了ver[1]。

**Comment by Kagamia** [comment]
支持了不定版本替换符，并且新增了一个kmst-minor默认配置项，旧的配置项在打开patcher后会自动更新。
对于覆盖更新软件的使用者可以通过编辑Setting.config，手动构造配置。

![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/4b093da9-7094-4ff9-af2a-c3278bca6591)

![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/1487dcf6-57cf-42a5-a67d-9da59bb24d49)

**Comment by HikariCalyx** [comment]
目前，1172-1173更新再次实装了这种更新模式，好像很多人总是会忘记安装minor更新。
目前比较可行的判定当前待更新的客户端使用的minor patch版本的方法，是读取 MapleStoryT.exe 的文件版本。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/d3d645d4-6033-449a-bd41-5fe9223b733b)

**Comment by Kagamia** [comment]
补丁本身就包含前置对比现有文件crchash的功能，不需要做额外的检测。

**Comment by HikariCalyx** [comment]
https://maplestory.dn.nexoncdn.co.kr/Patch/00390/Minor/01to03.patch
KMS正式区也已证实实装这一改动。
