### ISSUE TITLE
KMST 1.2.1172 的活动地图渲染不正确

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#257]
993244300和993245000渲染出来的结果如下：
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/208fcf77-f707-4acd-8e23-55c0e406e662)
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/4b67cc83-6c26-44ca-b212-66039d8c10ed)
实际游戏截图应该是像这样有观众背景的。
![image](https://github.com/Kagamia/WzComparerR2/assets/29157608/acce613a-bad2-4d08-8d60-f5178a122ed7)

**Comment by Kagamia** [comment]
可以帮忙指出图片中这些背景在wz的什么地方吗？

**Comment by HikariCalyx** [comment]
根据 KMS 1.2.389 -> KMST 1.2.1172 对比报告，实际渲染效果中缺失的部分文件名有这些，位于 Map\Obj：
```
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_10.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_11.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_12.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_13.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_2.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_3.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_4.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_5.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_6.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_7.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_8.png_new.png
21stEvent.img.spine.main.03_VictoriaCup_Stadium_F_9.png_new.png
21stEvent.img.spine.object.04_VictoraiaCup_TotalObject_F.png_new.png
21stEvent.img.spine.object.04_VictoraiaCup_TotalObject_F_2.png_new.png
```

说到这个，似乎 1172 版本开始的改版后斯乌 BOSS 过场动画也用到了骨骼动画，现版本 WzComparerR2 无法渲染，位于：
```
Mob\BossPattern\BossEnterAni.img\suu
```

**Comment by PirateIzzy** [comment]
To follow up on the issue with Suu / Lotus issue, the 1st phase animation doesn't use Spine, just a regular sprite animation. 2nd and 3rd phase both show "atlas" rather than `<name>.atlas`, and cannot be rendered.

![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/486de5ec-ac50-44f4-85f2-665933cfdcd0)
![image](https://github.com/Kagamia/WzComparerR2/assets/34289651/a86e80be-ac4f-4bde-be25-4453794022f9)

**Comment by Kagamia** [comment]
@HikariCalyx  @PirateIzzy 
Thanks for the investigation and detailed explaination, trying to fix.

**Comment by Kagamia** [comment]
![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/9c0107d5-a7e3-44f2-8ae2-c71121ca1e35)

![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/827804a8-91a8-471d-8778-ec75ec53a8d9)

![image](https://github.com/Kagamia/WzComparerR2/assets/10445904/90d71c8b-17e7-496b-b803-0540bd4f4e6d)

Fixed skeleton loading behavior for both MainUI and MapRender.
