### ISSUE TITLE
MapRenderV2 exception issue

### ISSUE THREAD

**Issue by imgoogoogo** [Kagamia/WzComparerR2#262]
There was no problem when I did the maplander on June 23rd by doing git clone
But when I tried git clone again on June 24th, I had a problem when I played Maplander

Error : 
Wz_Png exceeds the declared data size.

Code : 
throw new Exception($"Wz_Png exceeds the declared data size. (data length: {this.DataLength}, readed bytes: {startIndex}, next block: {blockSize})");

**Comment by Kagamia** [comment]
Yes, in that version we refined wzlib and introduced some breaking change.

Please provide your wcR2 version, client version, nodepath if possible for us to repro the error, thanks.
