### ISSUE TITLE
[BUG]最新版WzLib无法打开TMS v113部分wz文件

### ISSUE THREAD

**Issue by a2824256** [Kagamia/WzComparerR2#267]
问题描述：最新版WzLib无法打开TMS V113部分wz文件，但是20240424.1版本的WzLib能正常读取。
V113 Wz文件下载地址：https://pan.baidu.com/s/1b7iIk60A7FqlC1yg_UhscA?pwd=yqah

**Comment by HikariCalyx** [comment]
都这么古老的版本了啊，相当于CMS v79。我目前怀疑是那个时代的客户端编码不规范导致的打不开。

**Comment by a2824256** [comment]
> 都这么古老的版本了啊，相当于CMS v79。我目前怀疑是那个时代的客户端编码不规范导致的打不开。

20240424的WzLib是能打开的

**Comment by a2824256** [comment]
> > 都这么古老的版本了啊，相当于CMS v79。我目前怀疑是那个时代的客户端编码不规范导致的打不开。
> 
> 20240424的WzLib是能打开的

Kagamia/20240208-issue-template这个分支的Wz_Sound.cs是正常的

**Comment by Kagamia** [comment]
推送修复更新，在读取wz_sound时尝试是否解密。
该版本wz文件img字符串部分使用二次加密，但Wz_Sound的WaveFormatEx部分并没有加密，之前的重构漏掉了这段代码导致错误。

感谢您的提交 😆
