### ISSUE TITLE
GMS v251-v252 对比报错

### ISSUE THREAD

**Issue by WarshawskyG** [Kagamia/WzComparerR2#268]
![ERROR](https://github.com/user-attachments/assets/a80b568d-922a-4c57-ad54-dedafa75c11c)
对比skill时报错的
已经4次了

**Comment by haoren22ge** [comment]
对比的时候试试勾选“HashPngFIleName”，如果再不行那就不知什么原因了。

**Comment by WarshawskyG** [comment]
> 对比的时候试试勾选“HashPngFIleName”，如果再不行那就不知什么原因了。

可行，而且对比速度加快很多，感谢感谢

**Comment by haoren22ge** [comment]
> > 对比的时候试试勾选“HashPngFIleName”，如果再不行那就不知什么原因了。
> 
> 可行，而且对比速度加快很多，感谢感谢

应该就是之前CMS和TMS遇到的同样问题，名字太长了，当时CMS出的时候就这个问题，所以加了这个功能，就解决了

**Comment by HikariCalyx** [comment]
此问题的具体原因见 #226
