### ISSUE TITLE
.NET 6.0 版本中，EMS 客户端的带重音符号的字母 String 编码不正常

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#269]
在 GMS 的欧洲区存在之前，EMS 是早期 NEXON 欧洲公司面向欧洲国家推出的欧服，该客户端内包含多份不同语言的 String.wz。曾经推出的客户端的安装包可在这里下载： https://archive.org/download/emssetups2024
![image](https://github.com/user-attachments/assets/10c001d3-4de7-43e7-9da7-ca8445cf9c27)

以 EMS v27 版本内置的 StringFR.wz 为例，这是法语的 String 文件，在 .NET 4.x 版本的 WzComparerR2 下，欧洲语言常见的带重音符号的字母会被正常显示。在简体中文的系统编码下，带重音符号的字母以及后续的字母会组合成一个奇怪的汉字，这一点可暂且忽略，因为实际在 GMS 中也存在此情况。导出的 XML 文件只需使用 Visual Studio Code 更换打开的编码方式就可解决。
例如，下图中的 Serpent rétro bleu 在简体中文系统下会显示为 Serpent r閠ro bleu，将导出后的 XML 文件以 GBK 编码保存，再以 ISO 8859-1 编码打开后以 UTF-8 保存即可正常显示。
![image](https://github.com/user-attachments/assets/acded963-7cd5-49f3-81ce-9e38cfe30d88)

然而，在 .NET 6.0 版本的 WzComparerR2 下，欧洲语言常见的带重音符号的字母会被异常编码成 U+FFFD 字符，导出的 XML 文件也是如此，通用设置内的 WZ 默认编码选项也无法改变编码结果。
![image](https://github.com/user-attachments/assets/f8ffb0da-1659-4e98-ae67-cf2793ab7207)
![image](https://github.com/user-attachments/assets/588402a1-948c-4e21-9e24-e93f3ac0720c)

**Comment by Kagamia** [comment]
net462可以用iso8859正常解码
![image](https://github.com/user-attachments/assets/103de36b-e523-4ff1-8e99-7157e593ccaa)

net6好像忘记加载codepage包以至于配置无法生效。

但是我突然觉得有更好的解释方案，需要验证一下。

**Comment by Kagamia** [comment]
![image](https://github.com/user-attachments/assets/77740878-4a13-49e8-abed-7c254bb267fb)
Fixed.
