### ISSUE TITLE
Tooltip in World Map in MapRender

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#27]
Currently:

![!](https://cdn.discordapp.com/attachments/236180502200057856/337674964419215360/3434.png)

In-game:
![!](https://cdn.discordapp.com/attachments/236180502200057856/337677110053306378/ww2.png)

The text font also seems off even though it is Arial (same for minimap text).. hmm

**Comment by KENNYSOFT** [comment]
How can I see that worldmap window?

**Comment by Kagamia** [comment]
Font Shape&Layout Engine has not prepared for MapRender. Of course I'm working on it. 😆 

> @KENNYSOFT : press `W`

**Comment by KENNYSOFT** [comment]
Aha I didn't noticed yesterday's commit :)

**Comment by KENNYSOFT** [comment]
![image](https://user-images.githubusercontent.com/6624567/28456872-dbb36ac0-6e3e-11e7-89d7-15df550038ff.png)

Also \n is not properly treated.

**Comment by KENNYSOFT** [comment]
Solution for "\n": [Tooltip2.cs#L265](https://github.com/Kagamia/WzComparerR2/blob/fa46ba190c24b967355f37f3754709f98c347673/WzComparerR2.MapRender/UI/Tooltip2.cs#L265)
`desc` to `desc.Replace("\\n", "\n");`

**Comment by Kagamia** [comment]
@KENNYSOFT  It is still a preview version so far.
However it loads data from CMS/KMS/GMS successfully. 😆 

Finally we should port `GearGraphics.FormattedTextRenderer` from CharaSim to Monogame as an universal module.

**Comment by KENNYSOFT** [comment]
Right. That universal module should fix "#c" as well.

**Comment by KENNYSOFT** [comment]
How about making ESC function to go up one level?

**Comment by Kagamia** [comment]
@KENNYSOFT ESC is reserved for Option Window.
But there will be another way to switch the map.

**Comment by KENNYSOFT** [comment]
OK, great!
