### ISSUE TITLE
ms-support 分支在搜索时，无法正常指向除了 Mob/NPC/Skill 以外的任何结果

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#272]
试图双击搜索结果时，除了 Mob/NPC/Skill 下面的搜索结果，其它任何类别的搜索结果均无法正常跳转。
手动访问对应的搜索结果无法正常输出 QuickView 渲染图，Map 的部分虽然可以正常渲染，但无法正常识别是否属于 Map.wz。

**Comment by Kagamia** [comment]
Ack.

可能是因为msFile的引入，导致基于wzType的搜索方式失效了。

**Comment by Kagamia** [comment]
推送了一个更新，大概暂时恢复了
