### ISSUE TITLE
 MapRender: PNG Output on maps with transparent objects (addendum)

### ISSUE THREAD

**Issue by PirateIzzy** [Kagamia/WzComparerR2#274]
This is an addendum to #240 since it seems to be happening again with Tallahart maps as of KMST 1.2.178. It seems that the render doesn't properly render the clouds or the blue pillars, with some of them even having strange vertical lines.

Map ID 410013600
- render (you can see the clouds look off)
![410013600 (render)](https://github.com/user-attachments/assets/b8b02c68-ce6f-48dc-867a-fabecfcf51af)

- in-game
![410013600 (in-game)](https://github.com/user-attachments/assets/6ebc1afc-fd3a-4fb8-8f75-4e76bf542edd)

Map ID 410013601
- render (I drew red arrows to point to the vertical lines, but the clouds are also off)
![410013601 (render)](https://github.com/user-attachments/assets/ab145da1-0af1-4e05-8123-00a9fbf3bcf5)

- in-game
![410013601 (in-game)](https://github.com/user-attachments/assets/38a4415f-2aee-4baf-b1f6-39a01e84d4a6)
![410013601 (in-game 2)](https://github.com/user-attachments/assets/4be09a18-32d8-493f-a59b-a37ce41614f5)

Map ID 410013602
- render (I drew red arrows here as well, but the clouds are off + the blue pillars don't have transparency)
![410013602 (render)](https://github.com/user-attachments/assets/9806acee-ccc6-43ef-b99b-42d775898a1b)

- in-game
![410013602 (in-game)](https://github.com/user-attachments/assets/ef8854c1-e3f5-439f-a59e-f25771182d8d)

**Comment by Kagamia** [comment]
Seems these cases are all spine 4.x skeletons. The new spine renderer should have some bugs on additive blending.

**Comment by Kagamia** [comment]
Not sure if it is better than before.
410013602

![image](https://github.com/user-attachments/assets/6051d93e-b85c-4d31-8319-8f572ebafe7f)

**Comment by nanochromatic** [comment]
Thanks for taking a look, that looks better.

Two other things I notice in-game vs MapRender:
- Object outlines in-game are a bit smoother whereas object outlines in MapRender are more prominent:
In-game
![image](https://github.com/user-attachments/assets/a7aa725a-e956-4262-8f21-c2be48d1c858)
MapRender
![image](https://github.com/user-attachments/assets/bba5e0ec-1267-4f8f-b00a-090dee6f90e1)

- MapRender produces vertical line artifacts (see red arrow in the screenshot)
![image](https://github.com/user-attachments/assets/2b896376-6bc2-4ef7-a8ba-d8eaa7354053)

**Comment by Kagamia** [comment]
@nanochromatic For the vertical lines, I think it may be due to 'half-pixel problem' and it is a little hard to investigate so far.

Per the color difference between wcR2 and in-game rendering, I found that the official spine-runtime 4.1 does not support BlendMode nor per texture properties (PMA, TextureFilters, etc.) so I need to fix it by myself.

**Comment by Kagamia** [comment]
Push a new commit: https://github.com/Kagamia/spine-runtimes/commit/e565df6ae201026c9cbbf0cd83d4cf63cb1c3573

Here's the final version.
![image](https://github.com/user-attachments/assets/4e214dfb-bbaa-4b41-b401-87cc3850bdb7)

**Comment by nanochromatic** [comment]
@Kagamia This looks awesome, great work! I think the vertical line issue has also been resolved as I no longer see any when rendering maps that previously were impacted (for example, `410013602` no longer has the lines).

I'll let @PirateIzzy chime in as well, but this looks to be fully resolved on my end.

**Comment by Kagamia** [comment]
@nanochromatic So the vertical line is likely due to pre-multiplied-alpha textures, the semi-transparent pixels are shown as dark black color.

I’m glad to see it was fixed. We can close this issue aflter double check.

**Comment by PirateIzzy** [comment]
I can confirm it works. We can close this.
