### ISSUE TITLE
CMS 209to210 和 TMS 263to264 的手动补丁文件无法使用 WzComparerR2 更新

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#277]
错误原因均为 Checksum Error，可能是补丁文件结构发生了变化。
![image](https://github.com/user-attachments/assets/e634806b-2f1b-4cee-81d8-1141c6a76fff)
![image](https://github.com/user-attachments/assets/43272221-ab6f-4375-bc78-b6141932929a)

CMS补丁下载链接如下。访问时，必须携带正确的Referer Header才能顺利访问下载，因此不可直接复制链接到浏览器：
文件1：`https://secauth.gcdn.sdo.com/?url=https://mxdver0.jijiagames.com/210/MaplePatch209to210.exe`
文件2：`https://secauth.gcdn.sdo.com/?url=https://mxdver0.jijiagames.com/210/MaplePatch209to210.patch`

TMS：
https://maplestory-download.beanfun.com/maplestory/download/264PqhafvwNclDb/RvVNUeMseDkl/MaplePatch263to264.zip

**Comment by HikariCalyx** [comment]
补充一下处理措施。
以TMS v263to264为例，倒数第17到24字节是这个补丁文件的实际长度0xBACD2C45。通过16进制编辑器选取到从0开始长度BACD2C45，另存为00263to00264.patch后，即可正常更新了。
![image](https://github.com/user-attachments/assets/0e5b39ed-bbb0-4b10-a870-7c801b23b725)
![image](https://github.com/user-attachments/assets/8493b969-2539-4cc2-83a5-ab9d02916bac)

**Comment by Kagamia** [comment]
ack.

大概是因为patch文件结尾也开始遵守原来exe结尾的结构了，添加了额外的notice信息和长度信息。
看来以后要同时对exe和patch结构做相同处理了。

**Comment by Kagamia** [comment]
![image](https://github.com/user-attachments/assets/1f38efe4-2ded-4a25-8449-e6f398ae0e90)

**Comment by HikariCalyx** [comment]
CMS 209to210 patch测试可用👍
