### ISSUE TITLE
道具期限能力值厕所模拟跟游戏中实际显示不一致

### ISSUE THREAD

**Issue by haoren22ge** [Kagamia/WzComparerR2#278]
道具期限能力值在厕所模拟的跟游戏中显示的数值不一致，如下：

WC模拟显示：
![9G 7MXJF2H$P9) `K%6X5YF](https://github.com/user-attachments/assets/a8b406ea-de35-45fd-83c0-90f5ffb69033)

游戏中显示：
![4%RUZ%T~T2@EH @J9P0LVGQ](https://github.com/user-attachments/assets/09dc2bd2-43a7-4a05-a931-259717178b66)

道具ID：1143246
使用客户端：CMSV210
使用厕所版本：
![image](https://github.com/user-attachments/assets/b458cde0-fd9f-441e-a330-afd28993b2dc)

**Comment by Kagamia** [comment]
在上古版本中，abilityTimeLimit确实指示的是道具的**最终属性**，而不是**额外附加属性**。
不知道什么时候它改成现在这样的...

**Comment by Kagamia** [comment]
在最近的几个更新中修复了。
#293, b2c878901ba93ca0430ef29071903c6cac2765ec, 8cf1cb066a3c72bf95925fa09d41cce660d0a9dc, 9dc50bab05a709c8e0673a8680c2922de2d2c5f6

最终大概这样：
![1143246(1)](https://github.com/user-attachments/assets/158cd836-b3dd-444e-844c-0522b19593f4)
