### ISSUE TITLE
从 ms 文件导出的 IMG 无法被 WzComparerR2 解析

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#284]
JMS v427 和现版本的 KMS/KMST 客户端均可复现。
![image](https://github.com/user-attachments/assets/f688f09e-6846-4440-9493-bbc905485a13)

预期表现应当是会出现直接展开就能看到的子node，推测是 MainForm.cs 内 tsmi1Export_Click 函数对来自 ms 文件的 IMG 没有做好处理。

**Comment by Kagamia** [comment]
修复了一个导出时忘记解密文件的bug，现在应该可以正常导出了。

**Comment by HikariCalyx** [comment]
![image](https://github.com/user-attachments/assets/5037bf98-ecfb-4310-a4f9-eec643581e9a)
验证可行👍
