### ISSUE TITLE
关于SPINE后期更改版本无法解读

### ISSUE THREAD

**Issue by cxx3-s** [Kagamia/WzComparerR2#286]
**前期WZ版本骨骼中的架构【.json】(string)**
可读取SPINE版本号, 骨骼内容, 动作方式 以便于SPINE中逆向
![1729085490931](https://github.com/user-attachments/assets/a0932cc9-91bd-41d6-a065-7e9d2e357454)

**但在后期WZ版本修改成了【.skel】(rawData)**
无法在Wcr2中读取到内容
save下也无法读取到(造成无法从SPINE中逆向)
但使用渲染地图却能正常显示SPINE动作方式
![1729085448712](https://github.com/user-attachments/assets/bcd4e8ad-2f54-4f49-b2c9-19cda19b9ec3)

**Comment by Kagamia** [comment]
skel格式请自行使用[spine-runtime](https://github.com/EsotericSoftware/spine-runtimes)读取，也可以按照[官方文档](https://esotericsoftware.com/spine-binary-format)人肉阅读。
