### ISSUE TITLE
JMS v428 特定勋章的渲染效果并未正确居中

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#287]
该勋章道具ID为1143384。
![1143384](https://github.com/user-attachments/assets/4763a06a-b10b-402f-934e-e32f373109cf)
关联贴图 UI\NameTag.img\medal\1120 内容如下。
![image](https://github.com/user-attachments/assets/9a11bc56-b6f3-48c9-9b16-5915e4657efe)

**Comment by Kagamia** [comment]
试图修复，在center为空的场景下只绘制ani0本身。
![1143384(1)](https://github.com/user-attachments/assets/c554b132-ac73-4641-b598-4c20bbf01f94)
