### ISSUE TITLE
JMS v428 特定道具因为 String 表内使用 uol 导致无法正确渲染 Tooltip

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#289]
具体出现问题的道具为5002724和5002725，渲染结果不显示标题和具体内容。在基于 @KENNYSOFT 的 KMS 分支的所有 WzComparerR2  中，试图渲染这类道具会直接弹出 Exception。
![image](https://github.com/user-attachments/assets/c9817d9d-e442-4028-8615-992bcf136912)

![image](https://github.com/user-attachments/assets/760f68c7-4569-4912-83c4-84625ed6c584)

关联的 XML 内容如下：
```
  <dir name="5002246">
    <string name="name" value="砂糖にゃん" />
    <string name="desc" value="青い瞳が魅力的な子猫の#c砂糖にゃん#。" />
    <string name="descD" value="生命の水が枯れて人形の姿に戻ってしまいました。特定の魔法で復活させることができます。" />
  </dir>
  <dir name="5002247">
    <string name="name" value="チョコにゃん" />
    <string name="desc" value="艶やかな黒い毛が魅力的な子猫の#cチョコにゃん#。" />
    <string name="descD" value="生命の水が枯れて人形の姿に戻ってしまいました。特定の魔法で復活させることができます。" />
  </dir>
```

**Comment by Kagamia** [comment]
手头没有客户端用于测试，仅按照issue的描述试图实现，请求帮忙验证。

**Comment by HikariCalyx** [comment]
![image](https://github.com/user-attachments/assets/2c9ae5a9-8499-43d3-a307-1bf9c861420f)
此问题已确认得到修正。
