### ISSUE TITLE
Canvas读取RGB565Thumb问题

### ISSUE THREAD

**Issue by anonymous5l** [Kagamia/WzComparerR2#290]
https://github.com/Kagamia/WzComparerR2/blob/f766224f7e4b3092110afd0871ea69d839ca1034/WzComparerR2.WzLib/Wz_Image.cs#L246-L247

在之前的版本是可以成功读取的在Commit `ecbede52d4f2e8aafddaa9d921050e8d6855ed7e` 之后进行了修改导致这里的`form`少加了一个`byte` 所以格式识别成`513`(也就是`RGB565`)而不是`517`(也就是RGB565Thumb) 

改为

```C#
int form = reader.ReadCompressedInt32() + reader.ReadByte();
reader.SkipBytes(4); 
```

问题解决。

**Comment by Kagamia** [comment]
Thanks.

Fixed in https://github.com/Kagamia/WzComparerR2/commit/be5f8512c27060d03b1f32c8dea7b373849400b8
