### ISSUE TITLE
Genesis weapon skill tooltip question

### ISSUE THREAD

**Issue by terjun** [Kagamia/WzComparerR2#295]
The Genesis weapon has a separate tooltip that shows the two skills that can be obtained while completing the quest.
This tooltip is located above the set item window, and, incidentally, the set item tooltip for the lucky item being applied is also displayed above the set item tooltip.
Is it possible to implement another tooltip on top the set item tooltip?
Although it is KMS, an image is also attached.

![dfgdfgfdgdfgfhfhhjjgjj2](https://github.com/user-attachments/assets/4176057c-af0e-4450-b468-c4c910433743)

**Comment by Kagamia** [comment]
Do you have any idea that how the skills are stored in wz file?

**Comment by terjun** [comment]
Actually, in my plan, I thought it would be okay to only print text tooltips for Genesis weapons on top of the set items.
So, I thought it would be okay to print it out by referring to the skill item in the string.

**Comment by Kagamia** [comment]
Thanks, but I think the actual problem is that how to identify these weapons **without hardcoded IDs**.
Does it declare the corresponding relationship of skills somewhere in wz?

**Comment by terjun** [comment]
First of all, in my think opinion, since the Genesis weapon is included as a weapon in the Eternel set, the first condition is that it is a weapon, and the second condition is that if the set item code is an Eternel set the tooltip is displayed...

**Comment by Kagamia** [comment]
So it is more like some kind of hard-coded rules. 

I also confirmed with some experts and also get the truth that the things are not explicitly declared in wz, Genesis weapons are all hardcoded with item IDs in maplestory.exe.

Let‘s file a work item as your described, active the widget when meet specific setItemID and for weapon type only.

**Comment by Kagamia** [comment]
![1472275(2)](https://github.com/user-attachments/assets/a12c99a0-b0a4-4e2c-a8c5-4fbf75169c5e)
The layout is a little different between KMS and CMS, just implement CMS style.

**Comment by terjun** [comment]
Thank you very much the Release.
Later let's try jokertoseitem, which I am personally trying to implement by referring to the code.
(Maybe, pich[2] = genesis + Joker + Set)

**Comment by Kagamia** [comment]
Joker part won't be considered as charaSim scope because it is hard to determine the active set names, the actual behavior varies by all over the gears you're wearing, a title with empty list also looks confusing.

**Comment by terjun** [comment]
Now that I think about it, I think it would be better not to do it. You can close the issue.
Adjusted for KMS.

![1472275.png](https://github.com/user-attachments/assets/1b5c91cf-a11b-4086-9730-30a643b5deb5)

**Comment by HikariCalyx** [comment]
KMST 1.2.1185 broke the implementation, which would provide incorrect librated skill name when rendering destiny weapon:
![Image](https://github.com/user-attachments/assets/5c0d45df-c356-4f1d-8eb6-f2fb8dc7b2ab)

Following commit fixed this by reading equipment level:
https://github.com/HikariCalyx/WzComparerR2-JMS/commit/7b9533f04046a5a844502e99b0d065b447bb5331

![Image](https://github.com/user-attachments/assets/f6ab3c7b-c37f-47ea-99a4-77520f0c0243)
