### ISSUE TITLE
你好，请问如何使用Lua导出.ms扩展名的xml

### ISSUE THREAD

**Issue by stillms** [Kagamia/WzComparerR2#297]
Base.wz里面没有Packs，所以我无法导出.ms文件的xml，请问如何修改Lua脚本

**Comment by Kagamia** [comment]
和原来没有区别。直接用img路径寻找你想导出的img即可，不需要关注文件的物理路径。

参考 #280

**Comment by stillms** [comment]
> 和原来没有区别。直接用img路径查找你想导出的img即可，不需要关注文件的物理路径。
> 
> 参考#280

感谢你，解决了
