### ISSUE TITLE
Set Effect for Party Quest equips

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#30]
I noticed that the set effect window in WCR2 is below the list of equipment while it should be next to it.
The window above/next to the set effect mentions `(Equip)` for all Party Quest equipment. However, other equips that are not part of the Party Quest Set don't have `(Equip)`, but the usual `(Hat)`, `(Shoes)` etc.

↓ Simulated
![test](https://cdn.discordapp.com/attachments/88992151643369472/340210620400140298/1072872.png)

↓ In-game
![test](https://cdn.discordapp.com/attachments/88992151643369472/340210587441168384/ingame.png)

**Comment by KENNYSOFT** [comment]
I think expandToolTip flag matters to that issue.

See below:
![image](https://user-images.githubusercontent.com/6624567/28868835-a3ca7880-77b5-11e7-9b20-dd6db17b0f47.png)

**Comment by KENNYSOFT** [comment]
Also, if the "parts" flag is on, then the 'typeName' should be "(Equip)" if there isn't exist 'representName'

**Comment by Sunaries** [comment]
Hm, in SetItemTooltipRender.cs there is this part:

`
                    itemName = itemName ?? string.Empty;
                    typeName = typeName ?? "Equip";

                    if (!Regex.IsMatch(typeName, @"^(\(.*\)|（.*）)$") && !Regex.IsMatch(typeName, @"^(\[.*\]|（.*）)$"))
                    {
                        typeName = "(" + typeName + ")";
                    }
`

**Comment by KENNYSOFT** [comment]
@Sunaries That code is not related with this issue. it doesn't care about 'parts' flag.

**Comment by Kagamia** [comment]
Yes, there are not any special flags defined in wz, so it can't be simulated perfectly same as the game, except hard coding.

**Comment by KENNYSOFT** [comment]
@Kagamia There is some special flags like `expandToolTip` and `parts` :)

**Comment by Sunaries** [comment]
Yup. `expandToolTip` does like the name suggests. It expands the tooltip window to having a third window since it's too big otherwise in the game.

**Comment by Kagamia** [comment]
So, maybe the `parts` take the effect. 😄 
I've checked all set items with the `parts`, all of them are pet equip sets, and all of them are shown with `Equip` tag.

**Comment by KENNYSOFT** [comment]
@Kagamia For `expandToolTip`, see my code in https://github.com/KENNYSOFT/WzComparerR2/commit/c51b34610f9ba5170a637edc70e0df51d86cfd60

**Comment by Kagamia** [comment]
@KENNYSOFT  Thanks, I'll read it.

Perhaps I will drop by to bring `CombineProperties` to another place.

**Comment by Sunaries** [comment]
I think @KENNYSOFT meant https://github.com/KENNYSOFT/WzComparerR2/commit/a5ff4b5fc3c7f1e1641370b5e32f9bb57b61d537

**Comment by KENNYSOFT** [comment]
@Sunaries Oh right! thanks :)
