### ISSUE TITLE
"Unknown char '%'. Error

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#31]
This only applies to versions with the Beast Tamer class. I was randomly checking out skills, and wanted to preview skill ID: 80011348. 

It gave me an error saying: **Unknown char '%'**
I think I know why it crashed. I exported a .XML file of the respective .img and came across this:

```
<dir name="common">
        <int32 name="maxLevel" value="4" />
        <string name="mpCon" value="0" />
        <string name="time" value="2+3*x" />
        <string name="cooltime" value="180" />
        <string name="x" value="5+10*(x-1)%" /
        <string name="indieSpeed" value="-50" />
      </dir>
```
`<string name="x" value="5+10*(x-1)%" /`

Can you reproduce this @Kagamia since you have CMS installed?

**Comment by Kagamia** [comment]
How is it shown in the Game? 😃 

Or, how the game translate the char '%' ?>

**Comment by Sunaries** [comment]
@Kagamia I can't find an in-game screenshot of it. It's a ring with a buff skill.

![r](https://cdn.discordapp.com/attachments/236180502200057856/341553718220554240/icon.png)
**Rawr Ring**
**Description:** Infused with the deadly power of the mystical creature Lingling. Increases Critical Max Damage for a short time, but restricts movement.
**Level readout:** MP Cost: 0, Duration: 20 sec, Max Critical Damage: +60%. Speed: -50. Cooldown: 180 sec
**Level readout (data):** MP Cost: #mpCon, Duration: #time sec, Max Critical Damage: +#x%. Speed: -50. Cooldown: #cooltime sec

**Comment by Kagamia** [comment]
So... the char '%' is useless in the expression, we could ignore it. 😀
