### ISSUE TITLE
'#' character bug

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#32]
There are descriptions of items that don't have **#c** included, but just **#**. There's a bug where the first letter after the hashtag doesn't appear.

Example)
![t](https://cdn.discordapp.com/attachments/236180502200057856/341605079163469827/2435582.png)

![t](https://cdn.discordapp.com/attachments/236180502200057856/341605254439370752/1.png)

Other examples)
![t](https://cdn.discordapp.com/attachments/236180502200057856/341605080400789504/2435636.png)
_(**N**einheartroid)_

![t](https://cdn.discordapp.com/attachments/236180502200057856/341605081436651541/2435733.png)
_(**N**odestone)_

**Comment by KENNYSOFT** [comment]
See https://github.com/KENNYSOFT/WzComparerR2/commit/9ae4dff376562d5cd447854ce2eb0ce2cc0875f0 > Parser.cs

**Comment by Sunaries** [comment]
@KENNYSOFT Yup, I just realised I wasn't using my [Unstable] build, but the [Stable] build. The latter doesn't have the changes that I added to the [Unstable] build.
