### ISSUE TITLE
Avatar模擬騎寵

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#34]
有一些騎寵的動作不是sit
而是由forceCharacterAction控制動作
例如1983326 用sit模擬會顯得怪異

**Comment by Kagamia** [comment]
emmm 确认bug的确存在... 是相当麻烦的问题...

加入日程，近期会修复。

**Comment by Kagamia** [comment]
在最新的更新中已经支持 => https://github.com/Kagamia/WzComparerR2/commit/fe8dd33837b600905a323788e87c9b19a6c62fcb
