### ISSUE TITLE
MapRender建議

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#35]
MapRender建議
W大地圖下拉選單加入滑鼠滾動功能 減少下拉動作 操作會更直覺化
鼠標雙擊地圖光點 MapRender自動跳轉到該張地圖

**Comment by Kagamia** [comment]
嗯... 下拉控件为ekUI源生控件，编程性不一定很好，大概要试试看。

点击worldmap自动跳转OK（属于设计内但是未实现功能，因为需要一个对话框提示还没做好），会在2.1版本优先加入。

其实对于ekUI我已经hacking进去很多了... 不过有些非关键操作不急于开发..
2.1版本的目标也就是修复这些细小的使用不方便的地方，会逐渐调整的。
