### ISSUE TITLE
希望能在FrmPatcher.cs加入國外版的Patch下載點

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#37]
settings.Add(new PatcherSetting("TMS", "http://tw.cdnpatch.maplestory.beanfun.com/maplestory/patch/patchdir/{1:d5}/{0:d5}to{1:d5}.patch"));
settings.Add(new PatcherSetting("CMS", "http://125.39.60.17/maplestory/patch/patchdir/{1:d5}/{0:d5}to{1:d5}.patch"));
settings.Add(new PatcherSetting("MSEA", "http://patch.maplesea.com/sea/patch/patchdir/{1:d5}/{0:d5}to{1:d5}.patch"));

**Comment by Kagamia** [comment]
似乎是个好主意~


因为配置文件的更新机制，建议自行把这些设置手动编辑到配置文件中去。

另外，我个人没有安装那么多的MapleStory客户端版本，无法验证地址的正确性，也无法保证可以及时更新失效的地址=w=
