### ISSUE TITLE
關於怪物掉落

### ISSUE THREAD

**Issue by wangdiskater** [Kagamia/WzComparerR2#40]
首先很感謝你提供的工具，就想問一下怎麼能看到怪物的掉落物品有哪些，比如綠蝸牛-》金幣、綠蝸牛殼等等...這個可以看到嗎？

**Comment by Kagamia** [comment]
不可以。怪物掉落物品完全由服务器控制，客户端没有任何**有效**的信息。

在上古版本客户端内是有怪物手册数据的，现在可能还残留在客户端内，不过after-bigbang后几乎认为完全失效了。
