### ISSUE TITLE
小建議

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#41]
希望能快點加入保存AVATR造型的功能
有時候模擬好人物很想把圖片保存起來

**Comment by KENNYSOFT** [comment]
Is this issue related to saving character in avatar module? If then, could you translate it to English?

**Comment by KKMAA** [comment]
AVATAR沒辦法保存人物成gif 只能在程式上模擬很可惜

**Comment by Sunaries** [comment]
@KENNYSOFT You have this in your version. See commits made on January 20, 2017. -> https://github.com/KENNYSOFT/WzComparerR2/commits/master?after=c49e9ca83c968bd70d47e2c925de8ec5378a45d5+104

**Comment by KENNYSOFT** [comment]
@Sunaries Right, someone made it for KMS version and I accepted pull request. But I'm not sure this issue is related to this function; Chinese is not well translated.

**Comment by Kagamia** [comment]
Yes, It is requested avatar saving functions.

--------------

目前来说还没到实现的时候，虽然源代码里有一些测试代码似乎实现了导出，但是没有一个通用的合适的程序模型和UI来做到这一点。

主要还是多图层问题，目前已经有人物/表情/座驾三个动画图层了，计算KeyFrame非常费劲。在普通的动画预览和保存中我干脆没算，直接用的fixed delay然后上下帧对比决定抽帧.....   

2.1将会正式引入特效图层和对应的UI，然后才会考虑实现保存。
