### ISSUE TITLE
Network error?

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#42]
![image](https://user-images.githubusercontent.com/6624567/30781674-6ea87d96-a15e-11e7-95c7-1a729c0818b8.png)

I recently adapted your Network plugin code and get this error message on startup. What's this mean and how I fix this?

**Comment by KENNYSOFT** [comment]
I added Network plugin reference to main project, like below.

![image](https://user-images.githubusercontent.com/6624567/30781938-855d1e2a-a163-11e7-9ffd-b2962ef48b6b.png)

Now I don't get error!

![image](https://user-images.githubusercontent.com/6624567/30781941-8c4de25a-a163-11e7-8e4d-84a421564421.png)

@Kagamia I think you should also commit WzComparerR2.csproj file.

**Comment by Kagamia** [comment]
The main program has no strong dependency with the plugins.

You should manually compile each plugin, or config in the `Project Dependencies` (not reference)

**Comment by KENNYSOFT** [comment]
Hmm, okay, but if I remove reference then this error occurs back. Not solved by adding dependency...

**Comment by KENNYSOFT** [comment]
Aha, I got it. I don't know why but MapRender plugin has "Newtonsoft.Json.dll" too, so it crashed :( When I removed that, no errors!

**Comment by Kagamia** [comment]
😭   Yes... MapRender referenced `Json.net` on version 1.x for network chat supporting, and was removed after version 2.x, and it will come back on version 2.1. 😆

**Comment by Sunaries** [comment]
@Kagamia You aren't supposed to add references?

I currently have it like this and the program works fine. 

![t](https://cdn.discordapp.com/attachments/236180502200057856/361927563037245441/111111.png)

**Comment by KENNYSOFT** [comment]
It's conventionally not recommended. Plugin is add-in feature, so main program should not reference and have dependency to any plugin.
