### ISSUE TITLE
PDEF, BossDMG, IgnoreDEF icons have jagged edges

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#43]
Not sure if it is just me, but it looks like the three icons have jagged edges.

![1](https://cdn.discordapp.com/attachments/88992151643369472/361493272104796161/jaggededges.png)

**Comment by KENNYSOFT** [comment]
@Kagamia I think graphic doesn't draw PNG with alpha values... like that icons and job availability background.

**Comment by Kagamia** [comment]
This is how it looks like with 16 times scale in photoshop:

![qq 20170927131908](https://user-images.githubusercontent.com/10445904/30897009-878e74c6-a386-11e7-818b-5714241ac118.png)
![qq 20170927131458](https://user-images.githubusercontent.com/10445904/30897010-8790b380-a386-11e7-94be-8b7767c76c89.png)

**Comment by KENNYSOFT** [comment]
@Kagamia What's the difference between upper and lower one?

**Comment by Kagamia** [comment]
@KENNYSOFT  one is with black background and one is transparent. 😄

**Comment by KENNYSOFT** [comment]
Where can I find that transparent image?

**Comment by Kagamia** [comment]
@KENNYSOFT  
UI.wz\UITooltip.img\Item\Equip\Summary

**Comment by KENNYSOFT** [comment]
Maybe that image in KMS is black(upper) one... T.T

![image](https://user-images.githubusercontent.com/6624567/38285026-2b0c1d90-37f9-11e8-96de-a147eba18252.png)
