### ISSUE TITLE
Pet's stats misread

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#44]
![1](https://cdn.discordapp.com/attachments/236180502200057856/361499474239160320/skill_80000007.png)

It says `0 ATT: +3`. The **0** shouldn't be there. It should say **Weapon**.

String: 

```
  <dir name="80000007">
    <string name="name" value="Lv. 1 Demon's Heinous Pact" />
    <string name="desc" value="Better lock your soul up tight! Increases both Attack Power and Magic Attack by 3." />
    <string name="h" value="#Weapon ATT: +#padX, Magic ATT: +#madX" />
```

It misreads #W.

**Comment by Kagamia** [comment]
How the game itself shows that?

`
` Weapon ATT : +3


Does it ignore `#`?

**Comment by KENNYSOFT** [comment]
It will show in orange color :)

**Comment by Kagamia** [comment]
So it's really hard to compatible GMS and other MS. :(

**Comment by KENNYSOFT** [comment]
I think it's related to https://github.com/Kagamia/WzComparerR2/issues/38#issuecomment-326456548 .
Because #Weapon is not in camelCase, # should treated as #c.
