### ISSUE TITLE
Strange characters in KMST 1.2.058 Map001.wz

### ISSUE THREAD

**Issue by KENNYSOFT** [Kagamia/WzComparerR2#45]
KMST recently updated to 1.2.058 and now Map.wz is divided to Map.wz and Map001.wz. I updated my code to support that file and seeing this file gives me below result.

![image](https://user-images.githubusercontent.com/6624567/31783631-f2253198-b539-11e7-8345-912767162317.png)

Its Back folder is just properly works, but there are some strange characters, or a blank entry.

**Comment by KENNYSOFT** [comment]
By the way, the uppermost textbox is something like address bar, which is I just use for my developing, would be kind of an idea for convenient UI in next version.

**Comment by Kagamia** [comment]
Have you tried loading Map001.wz separately?

![image](https://user-images.githubusercontent.com/10445904/31809043-7e1e1c64-b5a8-11e7-8180-835811ca0c2f.png)

**Comment by Kagamia** [comment]
![image](https://user-images.githubusercontent.com/10445904/31810128-2fb200ae-b5ad-11e7-84d6-33350d5ce640.png) Okey you find the bug. Congratulations!

**Comment by Kagamia** [comment]
https://github.com/Kagamia/WzComparerR2/commit/f2d0039314fe83a06758aecfd54e62eb454a905a  bug fixed.

**Comment by KENNYSOFT** [comment]
yeah~ thanks for fix :)
