### ISSUE TITLE
can export  WZ file's all image in a one time ?

### ISSUE THREAD

**Issue by thisisjin** [Kagamia/WzComparerR2#47]
to find something is so difficult ,
so i think if can do this to help find, will save many time for me

**Comment by Kagamia** [comment]
Not support yet, but you could run script with **LuaConsole** plugin.
Here is an example -> [DumpXml.lua](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/Examples/DumpXml.lua)

**Comment by thisisjin** [comment]
sorry ，i cound ont understand it . 
my ackonwlege about script is so poor ,

Anyway，thanks

**Comment by thisisjin** [comment]
@Kagamia 
可能你誤解了我的意思。我是想輸出WZ文件的圖像。
并非IMG文件。
請問有什麽辦法麽

**Comment by Kagamia** [comment]
同样目前没有简单的操作支持，但是Lua控制台的脚本依然可以做到这一点 >.<

把导出的代码稍加调整，添加一个图像过滤器，对于img解压后递归执行即可。

**Comment by thisisjin** [comment]
@Kagamia 對對。不用追求簡單。我開始嘗試用你提供的方法導出了UI的IMG文件。
你說的“圖像過濾器”   ，我對這方便沒有接觸過，不懂是什麽。我對代碼這方面一竅不通
方便的話可以提供一份參照本給我嗎. 感激不盡

**Comment by Kagamia** [comment]
Okey~  -> [DumpImages.lua](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.LuaConsole/Examples/DumpImages.lua)

**Comment by thisisjin** [comment]
@Kagamia 
謝謝你！
我修改了輸出WZ文件為UI，在輸出過程中釋出兩個文件夾后就終止了。
輸出一欄的日志為
“(extract)Basic.img
(extract)CashShop.img
A .NET exception occured in user-code”

是哪裏出錯了麽

另外，如果要做到下圖這般，預覽某個IMG圖像的話，是需要如何操作呢
![image](https://user-images.githubusercontent.com/22115417/32426083-afbeb006-c2f2-11e7-9c1a-bc4da2ff59b4.png)

**Comment by thisisjin** [comment]
貌似這張圖就是 "quickview"功能顯示的。
我還以爲是通過什麽方式可以直接顯示在右邊。XD

**Comment by Kagamia** [comment]
我发现了一个wz名称会导致生成包含无效字符的文件名，已经修复。请重新checkout。

Charasim的QuickView预览框，当你选择了有效的装备/怪物/npc的img或Item的子节点时可以使用QuickView进行预览
也可以开启AutoQuickView自动预览。

**Comment by thisisjin** [comment]
@Kagamia 
好的，我去嘗試下。要是還有疑問再來打擾你。
感謝你的熱心幫助

**Comment by thisisjin** [comment]
@Kagamia 
thanks for your help 
my problem was solved
i will close this issue .
thanks ,mate
