### ISSUE TITLE
Some of the interface can not be displayed completely

### ISSUE THREAD

**Issue by thisisjin** [Kagamia/WzComparerR2#48]
OS：win10 enterprise version 1703 
軟體界面的有些内容不知道爲什麽無法顯示完全。
猜測可能是由於作業系統的問題?
請問有什麽辦法可以讓其完整顯示麽。
謝謝
![image](https://user-images.githubusercontent.com/22115417/32497418-73d743b2-c407-11e7-80e4-eedc54ff4fc4.png)

**Comment by Kagamia** [comment]
简单来说是windows有一个全局字体大小的设置，会影响到一切和字体绘制相关的界面功能，如果程序不支持适应的话会导致乱掉。。。

如图，对于win10系统在开始-设置-系统-显示里面

![qq 20171107231130](https://user-images.githubusercontent.com/10445904/32500802-539242b4-c411-11e7-8a9a-74b41fde7b87.jpg)

**Comment by thisisjin** [comment]
還真的是，😁
另外patcher現在還起作用嗎。
那個patch download Url貌似TMS的鏈接是錯誤的。

我比較關注自定義更新的prepatch還有outputPng現在是否還有效？
衹需要單獨勾選outputpng應該就會輸出差異圖片了吧?不需要去勾選compare選項？

**Comment by Kagamia** [comment]
1> 起作用  顺带已经识别了TMS的64位长度标识的.patch文件
2> 如果认为是错误的请告诉我正确的地址XD
3> prepatch可用，可以预览和自选需要更新的子文件并且调整更新顺序。
  outputpng也有效，可以正常在对比结果中输出图片
4> outputpng是compare的子选项，不选是不可以的：（

**Comment by thisisjin** [comment]
確實起作用。是我誤操作了。XD
以爲今天楓之谷會向203版本邁進。
