### ISSUE TITLE
沒有載入到插件

### ISSUE THREAD

**Issue by s23301955** [Kagamia/WzComparerR2#50]
MapRender 和Avatar 載入不到
開啟about處顯示沒有加載插件
版本2.1

**Comment by Kagamia** [comment]
首先检查您发布路径下`Plugin`文件夹是否存在插件文件。
![image](https://user-images.githubusercontent.com/10445904/33353489-0bb75c7a-d4e9-11e7-8c50-2bf286d9f82e.png)

默认的解决方案设置中，主项目和插件项目之间没有设置编译依赖，所以插件不会自动随主程序编译并部署。
如果上述文件夹没有文件，您可以手动逐个单独编译您需要的插件。

**Comment by s23301955** [comment]
Plugin文件夾內有插件
但打開wcr2後不會載入

**Comment by Kagamia** [comment]
抱歉，目前没有遇到类似的bug报告。 😢 

如果您在调试模式下无法加载，可以在[Program.LoadPlugins()](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2/Program.cs#L43)函数下进行断点调试来寻找原因。

**Comment by s23301955** [comment]
我使用同樣版本的主程式+Plugin
在電腦A Win10 1607 組建14393 下可正常載入
電腦B Win 10 1703 組建15063 下則無法載入任何Plugin

**Comment by Kagamia** [comment]
在我的surface pro上任何windows 10的build(1511/1607/1703/1709)都可以正常运作。
目前也没有收到win10特定版本上无法加载插件的错误报告。

**Comment by CMSFANS** [comment]
win10文件保护机制阻止了载入，右击相关DLL文件，选择解除锁定-确定，次回启动即可载入。 @s23301955
