### ISSUE TITLE
地图过大无法保存问题

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#51]
CMS V148
地图编号:867123400 冬日城堡度假村：银色山脉下山  Map.img\PL\867123400
使用MapRender模拟 Scroll Lock保存时会失败

**Comment by Kagamia** [comment]
请试试在x64系统下使用wcR2.anycpu版本以获得更大的可用内存上限。

因为这个地图真的是太大了... 无论是截图还是渲染还是保存都没有做针对的优化 😭
