### ISSUE TITLE
About scripts in wz files

### ISSUE THREAD

**Issue by Ludibrium** [Kagamia/WzComparerR2#52]
Hello!

I wonder if there is anyway to figure out where are maplestory's scripts saved. For example, scripts in Map.wz which usually have things to do with portals, and scripts in quest.wz/check.img seems like it contains NPC's actions.

Can you add a function that shows path to those scripts?

Thanks!

Background:

 I'm working on a small program that aims to extract maplestory quests.  The method is very simple: Given a key word, it searches Quest.wz/QuestInfo.img , if it finds a quest's name matches the key word, it records the quest's id, then extracts Quest.wz/Say.img/questid to get the words NPC saying.

Currently it doesn't work well. For example, I input "Lachelein" and search, the result is like that:
![questviewer](https://user-images.githubusercontent.com/17794729/34752654-97f18fe6-f5ee-11e7-89d0-ce5628321b04.PNG)

As you can see, it only extracted some quests' saying,  for other quests, it only extracted their name. And /Saying.img/questid is empty, too.

Then I occasionally found something interestring in Quest.wz/check.img. Most of quests that I can't extract have scripts, like this:
![default](https://user-images.githubusercontent.com/17794729/34753254-eb6348c4-f5f1-11e7-9230-f55f2d6c623d.PNG)

I think the script in it contains more information about those quests. How to extract them?

**Comment by Kagamia** [comment]
I think there is no way to find out that.

Scripts are actually server side functions.

**Comment by Ludibrium** [comment]
Thanks! It seems hard to get this game's whole story without drilling a high level character. They only push some of story fragments in our wz file. :)
