### ISSUE TITLE
Is there any plan or road map to upgrade to dotNet Core

### ISSUE THREAD

**Issue by xepher** [Kagamia/WzComparerR2#53]
As you know, MS had shipped dotNet Core as the latest framework.
It can be run on Unix like OS.
So my question is, Is there any plan or road map to upgrade to dotNet Core?

**Comment by Kagamia** [comment]
Not considered.

Dotnet core is designed for server side use, no GUI framework supported.
And WcR2 has heavily depending on GDI+/Dx11/Winform Controls, Can't easily port to .net core.
