### ISSUE TITLE
EquipmentSkill

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#54]
A couple of items (non-existant in KMS) use a new variable ‘EquipmentSkill’. I don’t know if this is in CMS, but I’ll report it regardless. 

**Simulated**
![.](https://cdn.discordapp.com/attachments/402586960901832705/402590764284248095/1114401.png)

**In-game**
![.](https://thumb.gyazo.com/thumb/1200/_9c1e439fa97d866ee1b7872baddd8756-png.jpg)

Simulation doesn’t have the text: “The Ring of Torment Lv. 1” in orange. 

**Detailed**
![.](https://cdn.discordapp.com/attachments/88992151643369472/402591907152265216/45455454545.png)

There is also an item named Lucid’s Earrings which allows you to frighten your enemies with nightmares, stunning 15 enemies for 9 seconds. A bind skill from an earring. I assume this item has th le same variable.

**Comment by Kagamia** [comment]
![1114401](https://user-images.githubusercontent.com/10445904/34997170-b11368fa-fb16-11e7-97d0-312980aa3f85.png)
![qq 20180116234132](https://user-images.githubusercontent.com/10445904/34997214-d179670c-fb16-11e7-8495-ddf1d6cd46dc.png)
when `CharaSimSetting.Gear_ShowLevelOrSealed` is enabled, It will be rendered as a level-up-bonus property.

**Comment by Sunaries** [comment]
![.](https://cdn.discordapp.com/attachments/236180502200057856/402915818628710410/1114401.png)

True, but it doesn't exactly replicate it like in-game below the ring description without the option enabled.

**Comment by KENNYSOFT** [comment]
It cannot, cause like some ring from the tower of Oz has 1~4 level and it's determined in server.

**Comment by Kagamia** [comment]
![1114401](https://user-images.githubusercontent.com/10445904/38223931-211f1f46-3720-11e8-8d34-2b1d21cb9e5f.png)

However, it has shown the summary by default.
