### ISSUE TITLE
ScrollLock 没法截图了

### ISSUE THREAD

**Issue by txiaocao** [Kagamia/WzComparerR2#55]
ScrollLock 没法截图了

![tim 20180208110222](https://user-images.githubusercontent.com/3929991/35953457-b6f8115c-0cbf-11e8-92b8-3183ca32a25c.png)

**Comment by Kagamia** [comment]
bass初始化失败可能是一个声卡错误，请检查系统默认音频输出设备。
ScrollLock没法截图。。。可以提供一个详细的使用场合吗?

**Comment by txiaocao** [comment]
1、嗯，这个错误是因为声卡被禁用了，不影响使用
2、地图渲染MapRenderV2，早前V1版本，可以按F1-F9功能键，以及ScrollLock 截取全图，现在按这些快捷键不能提取素材和截取地图全图了

**Comment by Kagamia** [comment]
mapRender快捷键一直生效，请参考源代码：
https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.MapRender/FrmMapRender.cs#L436

如果一直无法使用快捷键，请试图获取或编译最新版本尝试。注意：**Release中不保证发布最新版本。**

如果仍然无效，请报告一下您当前的系统环境和wc版本。 😃
