### ISSUE TITLE
请问一下 avatar的坐标系是怎样的？

### ISSUE THREAD

**Issue by ljwlaji** [Kagamia/WzComparerR2#56]
想在cocos里面复现 但是坐标系把我搞懵了

**Comment by ljwlaji** [comment]
是左上角为0,0 还是左下角 还是右上角还是右下角呢

**Comment by Kagamia** [comment]
冒险岛全部坐标系都是左上角原点坐标系
从左到右: -x --- 0 --- +x
从上到下: -y --- 0 --- +y
