### ISSUE TITLE
Bosses in Arcane River don't display HP correctly

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#58]
Take Lucid for example, if you've fought her before, you should know how much HP she has.
It can't be zero.
![lucid-hp0](https://user-images.githubusercontent.com/29157608/37535885-03c9238c-2984-11e8-870a-0498f6248053.png)

If you really don't know, here's the reference info:
http://maplestory.wikia.com/wiki/Lucid/Monster

Is such a huge value not supported by WzComparer?

**Comment by Sunaries** [comment]
This is not a bug. The real HP value is stored server side. This bit of information cannot be extracted. What you see on fabsites that have the HP of Lucid listed is just an estimate made by players.

**Comment by HikariCalyx** [comment]
OK, thanks for your explaination.
