### ISSUE TITLE
[Bug] MapRenderV2 not working on GMS v193.4 

### ISSUE THREAD

**Issue by Ludibrium** [Kagamia/WzComparerR2#59]
WzComparerR2 Version: 2.1.1.0
MapRenderV2 Version: 2.1.0.0

For x86 version, MapRenderV2 can load maps but it fails to render background (I've tried ctrl+1).
Example:
![bug](https://user-images.githubusercontent.com/17794729/37820701-6fe02c0e-2ebc-11e8-9cd6-89f6b3ca0d79.PNG)

For anyCPU version, it crashes when trying to load maps.
Example:
![bug_anycpu](https://user-images.githubusercontent.com/17794729/37820751-97cee46c-2ebc-11e8-91cd-61bb0ea41f7c.PNG)

There's a file named "Map001.wz" in GMS folder, and I've never seen it in CMS (haven't played CMS for a long time). Maybe that's why bug occurs?
![gms_diff](https://user-images.githubusercontent.com/17794729/37820901-02e1eb3c-2ebd-11e8-87f5-b6f3cc2e8d22.PNG)

Example Map: 300000000 Ellin Forest：Altaire Camp  Map.img\3rd\300000000

**Comment by Kagamia** [comment]
for Q1: **File**-**Options**, check `auto detect extra wz files.`
![image](https://user-images.githubusercontent.com/10445904/37821490-b1e90006-2ebe-11e8-9056-bda6e3909bff.png)
![image](https://user-images.githubusercontent.com/10445904/37821503-b9759938-2ebe-11e8-9537-e7de16c2db9e.png)

for Q2: 
This may be caused by a corrupted system file called `xinput1_3.dll` in your X64 system folder `%systemroot%\system32`. Check if it is lost or damaged.

**Comment by Ludibrium** [comment]
> for Q1: File-Options, check auto detect extra wz files.

Solved.

> for Q2:
This may be caused by a corrupted system file called xinput1_3.dll in your X64 system folder %systemroot%\system32. Check if it is lost or damaged.

I have a signed xinput1_3.dll in WzComparerR2 folder.
It works well with x86 version, both x86 version and anyCPU version won't work if deleted. Also, error message is different if deleted. See:
![bug_no_xinput3](https://user-images.githubusercontent.com/17794729/37823648-13d85680-2ec5-11e8-80ba-460a9cf59456.PNG)
I think it means this dll is not hijacked..?


Nothing changed after copied to %systemroot%\system32.

> edit1:
CMS has Map2.wz instead of Map001.wz.

GMS has it too. :)

**Comment by Kagamia** [comment]
`xinput1_3.dll` is a native library, so it works only with the matched architecture(x86 or x64) of the application. 

WcR2 is a managed application. `WcR2.exe` is build for x86 only for less memory use, and `WcR2.anycpu.exe` is build for modern system for better performance, it will auto detect `bits` of system and choose the best mode. (x86 in 32-bit system, and x64 in 64-bit system)
 
From your words, you have got an x86 `xinput1_3.dll` in the root directory of WcR2, and you are working on a 64-bit system.  So, you'd better to move the file to `WcR2Root\Lib\X86` or `%systemroot%\syswow64` folder, then find a x64 version of `xinput1_3.dll` somewhere and copy it into  `WcR2Root\Lib\X86` or  `%systemroot%\system32` folder.

Another solution, install [DirectX Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=8109) from Microsoft will fix the issule.
