### ISSUE TITLE
模拟地图异常

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#60]
CMST V136
模拟940204116 尖耳狐狸谷：狐狸树末端 Map.img\etc\940204116
会异常
https://imgur.com/dhaMRRe

**Comment by Kagamia** [comment]
问题已经捕获，正在修复。

因为上个版本更新了粒子的模拟，现在正在适配游戏中一切可以见到的粒子算法。
大概明天会提交commit。

**Comment by Kagamia** [comment]
已修复。
https://github.com/Kagamia/WzComparerR2/commit/c24afb3e1f2477a2651192c403fa9ae63a215eea
