### ISSUE TITLE
请问有什么讨论组或测试组之类的吗 刚学c#的新手

### ISSUE THREAD

**Issue by lin8631** [Kagamia/WzComparerR2#62]
曾今的老玩家 偶尔在论坛上翻到你的作品 
![qq 20180402194129](https://user-images.githubusercontent.com/38003999/38195052-16718934-36ae-11e8-9c5e-aa98a9d260f1.png)工具栏有段时候点不开
![qq 20180402194226](https://user-images.githubusercontent.com/38003999/38195070-2ecb27d8-36ae-11e8-9ae0-6822a76f103e.png)
是这个报错吗

**Comment by Kagamia** [comment]
不被Application.Run捕获的错误一般为代码中特意忽略的异常，不会引发程序错误。

暂时没人反映UI相关的操作异常。
如果可以复现的话，请提供一个确切的操作系统环境，以及可以稳定触发bug的方式。

讨论组可以通过QQgroup140552267，或是联系kennysoft加入他们的discord group中。

**Comment by KENNYSOFT** [comment]
Me?

**Comment by Kagamia** [comment]
@KENNYSOFT  😂  I say welcome to our discord channels if he interests in WcR2 and c# develpment.
