### ISSUE TITLE
Patcher加入CMS连结

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#65]
CMS的.patch下载位置
http://mxd.clientdown.sdo.com/maplestory/patch/patchdir/00151/00150to00151.patch
GMS的连结已失效 可以移除

**Comment by KKMAA** [comment]
因为我提供的00151是 4/11CMS的改版 明天就能下载
如果要上一版的连结 改个数字即可

**Comment by Kagamia** [comment]
确认地址可用~已收录到Patcher。

https://github.com/Kagamia/WzComparerR2/commit/038ef955a9b6600074532236645e98548c3e19bc
