### ISSUE TITLE
CMS V151 MapRender渲染不出背景

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#66]
提前更新了V151，地图渲染就出现问题了……
如你所见，某些图层调不出来。
![cmsv151](https://user-images.githubusercontent.com/29157608/38563021-788e7256-3d0e-11e8-86d6-ff6bda4f2237.png)

使用最新的源码编译（使用Visual Studio 2017编译），运行环境是Windows 10 Version 1803 (Build 17133.1)
TMS V205仍然可以正确渲染，等明天TMS V206更新之后也一并测试一下好了

另外就是能否隐藏特定NPC，因为有些地方的NPC在使用MapRender渲染的时候会重叠在一起，实际游戏中基本没有重叠的情况

**Comment by Kagamia** [comment]
CMST.136/CMS.151版本Map.wz拆分。
解决方案参考：https://github.com/Kagamia/WzComparerR2/issues/59

**Comment by Kagamia** [comment]
思考了一下隐藏npc问题，当前版本暂时没有开发计划。
后续比较长期的开发计划可能会考虑。

**Comment by HikariCalyx** [comment]
感谢回答。手动加载base.wz和map001.wz之后就正常了，CMS V151, TMS V206, GMS V194.1均测试通过。
