### ISSUE TITLE
称号模拟的问题

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#69]
有部分称号模拟 并非依照跟游戏显示的相同
例如编号3700487 春日山谷植物管理员
使用WCR2模拟是这样
"春日山谷植物管理员"

但游戏显示中是这样
"在哈夫林农场里收获100次的实行生"
此类的称号 会连动任务次数
都是依靠String.wz的Ins.img的nickWithQR参数說明显示

**Comment by Kagamia** [comment]
十分有趣的机制，感谢提交。

**Comment by Sunaries** [comment]
test
