### ISSUE TITLE
fileLength of wavHeader is too long

### ISSUE THREAD

**Issue by xsoameix** [Kagamia/WzComparerR2#7]
I found fileLength of wavHeader is too long in [this line](https://github.com/Kagamia/WzComparerR2/blob/master/WzComparerR2.WzLib/Wz_Sound.cs#L145):
```C#
Array.Copy(BitConverter.GetBytes(this.dataLength + 44), 0, wavHeader, 4, 4);
```

The [usage](http://soundfile.sapp.org/doc/WaveFormat/) of the fileLength field of WAVE file format is:
> This is the size of the 
> entire file in bytes minus 8 bytes for the
> two fields not included in this count:
> ChunkID and ChunkSize.

The fileLength should be:
```C#
Array.Copy(BitConverter.GetBytes(this.dataLength + 44 - 8), 0, wavHeader, 4, 4);
```

Did I misunderstanding something ?

**Comment by Kagamia** [comment]
Yes, you're right XD
It will be fixed in next commit.

**Comment by xsoameix** [comment]
Great !
