### ISSUE TITLE
Long title names

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#70]
![t](https://cdn.discordapp.com/attachments/88992151643369472/443823198317051904/3700487.png)

Today GMS updated to ver 195 and added items. Along with this title, but the name is too long so it cuts-off. Any solution for very long title names to resize window if it matches X characters?

**Comment by Kagamia** [comment]
The tooltip is fixed width in the game, horizontal expanding is not a good way.
