### ISSUE TITLE
请教一下，倒计时组件在哪个wz路径下呀，找了好久没找到

### ISSUE THREAD

**Issue by txiaocao** [Kagamia/WzComparerR2#74]
RT
请教一下，倒计时组件在哪个wz路径下呀，找了好久没找到。打BOSS的倒计时

**Comment by Kagamia** [comment]
可以提供一个`完整清晰的`游戏截图吗

**Comment by txiaocao** [comment]
![default](https://user-images.githubusercontent.com/3929991/41359892-12bff2b0-6f5e-11e8-98f2-5aea885a9dab.PNG)

**Comment by Kagamia** [comment]
`Map\Obj\etc.img\timer2`
