### ISSUE TITLE
OctreeQuantizer 中可能存在 int 类型溢出的问题

### ISSUE THREAD

**Issue by poerin** [Kagamia/WzComparerR2#75]
使用 WzComparerR2 载入 Mob.wz 文件，选中 2700103.img 项，选中 skill1 项。使用 BuildIn 作为 Gif 的编码器，保存图片能复现问题。

**Comment by Kagamia** [comment]
建议切换成IndexEncoder。

默认的gif编码器是微软上古的代码库，无法维护了。

**Comment by poerin** [comment]
嗯，gif 也不支持半透明，所以现在喜欢使用 apng。不过在 OctreeQuantizer 中将 _red、_green、_blue 换成 uint 或者 ulong 类型可以暂时解决这个问题。

**Comment by Kagamia** [comment]
嗯，推测也是值超出范围了。。
不过那套库还是.net 1.1时代流传下来的东西，而且源代码实在懒得看就不修了...
index的encoder是从momiji源代码里抄的并且修了一些bug，应该十分稳定。

apng...没有合适的图床/浏览器支援有限/索引色和gif一样描述度有限，32位色文件体积还太大.... 总体上属于一个很尴尬的东西..做出来其实是为了我们在discord上交流用的....国内的环境里太难了...

**Comment by poerin** [comment]
是呀，目前支持比较有限。不过现在 Chrome 也支持 apng 了，对比 gif、apng、webP，感觉还是 apng 比较好。参考这个链接：
http://littlesvr.ca/apng/gif_apng_webp1.html

**Comment by Kagamia** [comment]
终于翻出了微软的源代码修改了一下，理论上应该修复了这个问题，请求测试。

因为我没有你的详细导出参数所以无法还原错误=w=
