### ISSUE TITLE
Error with prepatch as of KMST v1069

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#77]
This issue persists when selecting Compare Folder after selecting patch file and MapleStory folder.

KMS ver. (Kenny) ↓
![kms](https://cdn.discordapp.com/attachments/88992151643369472/457457729808891904/45545.png)

GMS ver.  ↓
![gms](https://cdn.discordapp.com/attachments/236180502200057856/457465671417331733/56565.png)

**Comment by Kagamia** [comment]
Nexon has uploaded the wrong file 😆
