### ISSUE TITLE
KMST v1069 gif输出异常

### ISSUE THREAD

**Issue by KKMAA** [Kagamia/WzComparerR2#78]
输出以下技能的gif档都会出现错误
400031024 이르칼라의 숨결 的keydown
400051040 노틸러스 어썰트 的effect0

错误图
https://imgur.com/sH1WObX

错误说明
System.AggregateException: 發生一或多項錯誤。 ---> System.ArgumentException: '-249' 不是 'red' 的有效值。'red' 必須大於或等於 0，並且小於或等於 255。
   於 System.Drawing.Color.CheckByte(Int32 value, String name)
   於 System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   於 System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   於 ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   於 ImageManipulation.Quantizer.Quantize(Image source)
   於 WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   於 WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   於 WzComparerR2.PictureBoxEx.<>c__DisplayClass28_4.<SaveAsGif>b__2()
   於 System.Threading.Tasks.Task.InnerInvoke()
   於 System.Threading.Tasks.Task.Execute()
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   於 WzComparerR2.PictureBoxEx.<>c__DisplayClass28_0.<SaveAsGif>b__0(Int32 curTime)
   於 WzComparerR2.PictureBoxEx.SaveAsGif(AnimationItem aniItem, String fileName, ImageHandlerConfig config)
   於 WzComparerR2.MainForm.buttonItemSaveImage_Click(Object sender, EventArgs e)
   於 DevComponents.DotNetBar.BaseItem.RaiseClick(eEventSource source)
   於 DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   於 DevComponents.DotNetBar.PopupItem.InternalMouseUp(MouseEventArgs objArg)
   於 DevComponents.DotNetBar.ButtonItem.InternalMouseUp(MouseEventArgs objArg)
   於 DevComponents.DotNetBar.BaseItem.InternalMouseUp(MouseEventArgs objArg)
   於 DevComponents.DotNetBar.ItemContainer.InternalMouseUp(MouseEventArgs objArg)
   於 DevComponents.DotNetBar.ItemControl.OnMouseUp(MouseEventArgs e)
   於 DevComponents.DotNetBar.RibbonBar.OnMouseUp(MouseEventArgs e)
   於 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   於 System.Windows.Forms.Control.WndProc(Message& m)
   於 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   於 System.Windows.Forms.ContainerControl.WndProc(Message& m)
   於 DevComponents.DotNetBar.ItemControl.WndProc(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (內部例外狀況 #0) System.ArgumentException: '-249' 不是 'red' 的有效值。'red' 必須大於或等於 0，並且小於或等於 255。
   於 System.Drawing.Color.CheckByte(Int32 value, String name)
   於 System.Drawing.Color.FromArgb(Int32 alpha, Int32 red, Int32 green, Int32 blue)
   於 System.Drawing.Color.FromArgb(Int32 red, Int32 green, Int32 blue)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.OctreeNode.ConstructPalette(ArrayList palette, Int32& paletteIndex)
   於 ImageManipulation.OctreeQuantizer.Octree.Palletize(Int32 colorCount)
   於 ImageManipulation.OctreeQuantizer.GetPalette(ColorPalette original)
   於 ImageManipulation.Quantizer.Quantize(Image source)
   於 WzComparerR2.Common.BuildInGifEncoder.AppendFrame(Bitmap image, Int32 delay)
   於 WzComparerR2.Common.BuildInGifEncoder.AppendFrame(IntPtr pBuffer, Int32 delay)
   於 WzComparerR2.PictureBoxEx.<>c__DisplayClass28_4.<SaveAsGif>b__2()
   於 System.Threading.Tasks.Task.InnerInvoke()
   於 System.Threading.Tasks.Task.Execute()<---

**Comment by Kagamia** [comment]
切换成IndexGifEncoder。

**Comment by poerin** [comment]
https://github.com/Kagamia/WzComparerR2/issues/75

这是由于 int 类型上溢导致的，你也可以尝试将 int 换成 uint 或者 ulong 可以解决这个问题。

**Comment by Kagamia** [comment]
duplicated as #75.
