### ISSUE TITLE
Frame 中的 CreateFromNode 函数可能导致死循环

### ISSUE THREAD

**Issue by poerin** [Kagamia/WzComparerR2#79]
尝试选中 Npc\2111000.img\say 后点击 “ExtractGif” 按钮。程序进入到 FrameAnimationData 的 CreateFromNode 方法内的 for 循环，当 i =14 时，执行 Frame.CreateFromNode 方法。然后进入该方法的 while 循环体内：
``` C#
            while (frameNode.Value is Wz_Uol)
            {
                Wz_Uol uol = frameNode.Value as Wz_Uol;
                Wz_Node uolNode = uol.HandleUol(frameNode);
                if (uolNode != null)
                {
                    frameNode = uolNode;
                }
            }
```
执行 uol.HandleUol(frameNode) 的返回值始终为 null，因而 frameNode 的值不会改变，由于 frameNode 的值没有改变，因而 uol.HandleUol(frameNode) 始终为 null。即，若 uol.HandleUol(frameNode) 返回null，则进入死循环。

**Comment by Kagamia** [comment]
已修复=> https://github.com/Kagamia/WzComparerR2/commit/ccc6fc8a0953106ed4cb51545bdbc2db6b3c3e65

**Comment by poerin** [comment]
再说 HandleUol(Wz_Node currentNode) 这个方法，frameNode.Value 为 "../4" 分割之后 为 ".." 和 "4"，首先遇到 ".." ，currentNode 变为 2111000.img，然后是 "4"，然而 2111000.img 并没有索引值为 "4" 的子节点，因此返回 null，这就是 HandleUol 返回 null 的原因。那么问题就在于 Npc\2111000.img\say 的 14 号节点的值 "../4" 指向的内容不存在。

**Comment by Kagamia** [comment]
@poerin  代码中同时修复了对于`..`的解析错误bug，请详细检查代码diff并检查执行结果。

本质上错误原因是`..`被执行了两次，使用uol的时候已经预先获取了`parent`，遇到`..`又执行一次。
所以这次修正强行过滤一次，希望符合wz设计的预期。

如果没有其他错误请关闭issue。

**Comment by Kagamia** [comment]
测试一下，之前的修复方式似乎有问题，貌似新的读取方法会导致大量链接失效。😢 

NPC\2111000这里的确是一个wz数值错误，并且kms也存在这个错误。 
游戏里反而读取的一点问题没有，但是也不知道冒险岛本身识别它的基理，很谜 🤣 

总之，上个补丁回滚，严肃的不支持这个`../4`了。
