### ISSUE TITLE
MapRender: 100000000 does not load

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#80]
After applying recent commits of yours, I noticed that in the updated build the map render specifically does not work for 100000000.

Other maps work fine. If you check image below, you see on left side the updated build and on the right side the build without the new code.

![kms](https://cdn.discordapp.com/attachments/236180502200057856/458938460879978496/5665.png)

**Comment by Sunaries** [comment]
This is weird... 🤔

**Comment by KENNYSOFT** [comment]
@Sunaries You tried Henesys in GMS, right? @Kagamia showed KMST's Henesys.

**Comment by Kagamia** [comment]
However, [this commit](https://github.com/Kagamia/WzComparerR2/commit/718401093c3ed0f70c8bcca0f34f36682c24b277) allows exception break in coroutine task debugging.

If you find further bugs plz tell me :)
