### ISSUE TITLE
The avatar has some simulation bugs 

### ISSUE THREAD

**Issue by jessicasama** [Kagamia/WzComparerR2#81]
Like the hair code 41160, when I choose the “prone" action，the hair layer is not prone hair layer。
![qq 20180622223514](https://user-images.githubusercontent.com/40495040/41783022-69d0e304-766e-11e8-9c5c-722f49731491.png)
The prone hair layer is here
![qq 20180622223532](https://user-images.githubusercontent.com/40495040/41783718-2bc3c00c-7670-11e8-9723-c2616603d633.png)

but like the code 41773.The prone hair layer will be covered automatically on the initial layer
![qq 20180622223643](https://user-images.githubusercontent.com/40495040/41784125-59b1e600-7671-11e8-844c-f5c56b59babd.png)
![qq 20180622223635](https://user-images.githubusercontent.com/40495040/41784131-5d615eca-7671-11e8-8866-a8e4101d5a1b.png)
some hair simulations have these bugs。

**Comment by Kagamia** [comment]
Really a serious bug. I spend all day fixing it but find no way except hard coding. 😢

**Comment by KENNYSOFT** [comment]
I think prone can be hardcoded, but hair cover problem can be solved. For now, there exists a checkbox which indicates that hairCover to use or not, but it can be auto determined. You can check https://labs.crr.io/maplestory/WZData/blob/master/MapleStory/Characters/CharacterAvatar.cs , it uses VSlot, I think.

**Comment by jessicasama** [comment]
@Kagamia  I didn't expect it to be such a complex work.  anyway,  thank you for your hard work.

**Comment by jessicasama** [comment]
Although there are some codes I don't fully understand, but I think it's very useful information. Thank you for your answer.

**Comment by Kagamia** [comment]
@KENNYSOFT  Yeah, I believe that airCover is decided by vslot, I've dump all vslot of caps 3 years ago and then confirmed that.

But finally, I was not able to think out a perfect mechanism, it is delayed for many years until you remind me. 🤣

**Comment by Kagamia** [comment]
fixed -> https://github.com/Kagamia/WzComparerR2/commit/abdf2834f4478e78de828035d2932ba198bc3cc8

**Comment by jessicasama** [comment]
@Kagamia  Great!  Thanks
