### ISSUE TITLE
贝尔达地图的沙尘暴粒子不能正确模拟

### ISSUE THREAD

**Issue by HikariCalyx** [Kagamia/WzComparerR2#82]
在 CMST V140、TMS V208 里的沙尘暴预期应该是黄褐色的，模拟器里出来的是黑色……
![verdal_sandstorm](https://user-images.githubusercontent.com/29157608/41909434-956d4f3a-7979-11e8-919d-d94dd7a67563.png)

**Comment by Kagamia** [comment]
参考了一下cocos2dx的粒子系统参数，可能是OpacityModifyRGB的处理方式问题...

暂时修复，不知道会不会影响其他地图的粒子绘制。 => https://github.com/Kagamia/WzComparerR2/commit/118921015b563336f8f6d8e280bc9938bde8c3f6
