### ISSUE TITLE
更新進度條

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#83]
WIN10 1804更新後，無法正常顯示進度條(數字)
![1530191834506](https://user-images.githubusercontent.com/37591855/42048532-1d308bb8-7b36-11e8-8ae0-4fdb0388e1e5.jpg)

**Comment by Kagamia** [comment]
我的surface pro上已经更新win10 build17134，没有发现类似问题...

可以试试原版程序，最新release的版本，有无类似bug。

**Comment by lowrt** [comment]
最新release的版本仍還是有問題...
![inked1530291991291_li](https://user-images.githubusercontent.com/37591855/42105475-0a482e66-7c03-11e8-842f-d3755ff7cd63.jpg)
![1530292029166](https://user-images.githubusercontent.com/37591855/42105208-20f4ac1c-7c02-11e8-8989-2bf50259e3ad.jpg)

**Comment by Kagamia** [comment]
在我的开发环境中无法复现，无法查明原因。
推测可能是缺少系统字体问题，或组件库自身bug。

建议在更新时开启prepatch进行两步式更新，这样可以提前计算出补丁后文件大小，或许可以成功显示出进度条了。

**Comment by lowrt** [comment]
抱歉 晚回復

字體顏色變成白色，造成看不到
是我本身電腦問題嗎...
![1536064688828](https://user-images.githubusercontent.com/37591855/45042970-940cfa80-b09e-11e8-861a-c52fcb4c1340.jpg)
