### ISSUE TITLE
關於染色顏料

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#86]
WZCR2未支持染色顏料
![391ada0a1f04d312ae66b00ff14c3bcb](https://user-images.githubusercontent.com/37591855/42357846-7534ac14-810c-11e8-9724-0f3576eb32f8.JPG)

- 遊戲中

1702796
![ad8e2170f67fef88057edcb4455bfffb](https://user-images.githubusercontent.com/37591855/42357797-3533d4be-810c-11e8-8bfa-13843948771b.JPG)

- WZCR2

![1702796](https://user-images.githubusercontent.com/37591855/42357873-99b98bf4-810c-11e8-83e1-a88d33752d67.png)

`colcorvar` =可染色

**Comment by KENNYSOFT** [comment]
Wow.. interesting function.

**Comment by butcherCHEN** [comment]
@KENNYSOFT
Does the KMS have this fuction？

**Comment by Kagamia** [comment]
CMST没有检测到该装备有这个属性，并且也没有人向我提供游戏截图...

**Comment by lowrt** [comment]
@Kagamia  
CMS V153 有嗎?...

**Comment by lowrt** [comment]
@Kagamia 
可能那裝備沒開放染色
以下這些裝備基本有屬性
1005142 
1005149 
1005150 
1053302 
1053303 
1053304

**Comment by Sunaries** [comment]
@butcherCHEN 
> Does the KMS have this fuction？
No, KMS does not have the dye function. GMS recently got a new update which got this dye item and other related UI in the data.

![](https://cdn.discordapp.com/attachments/236180502200057856/464826867153633280/5860000.png)

In GMS, the item 1702796 does not have the `colcorvar` variable.

**Comment by lowrt** [comment]
@Kagamia  
GearTooltipRender2.cs 有語法錯誤

```
            //绘制desc
            List<string> desc = new List<string>();
            GearPropType[] descTypes = new GearPropType[]{
                GearPropType.tradeAvailable,
                GearPropType.accountShareTag,
                GearPropType.jokerToSetItem,
                GearPropType.colorvar,
            };
```

**Comment by lowrt** [comment]
感謝~
