### ISSUE TITLE
About face accessory simulation.

### ISSUE THREAD

**Issue by jessicasama** [Kagamia/WzComparerR2#88]
Some face accessories have invisibleFace feature,such as ID 1012633
![2345 20180711142508](https://user-images.githubusercontent.com/40495040/42554161-669a5f6a-8516-11e8-965e-e39391d602c3.png)

In game, when I use it, the character face will be hidden.  Whether the invisibleFace feature can be added in the character simulation.

**Comment by KENNYSOFT** [comment]
Oh it's already in KMS version :)

**Comment by jessicasama** [comment]
@KENNYSOFT 
Yes,I got your KMS version,it fixed this problem very well.

**Comment by Kagamia** [comment]
fixed. 😆
