### ISSUE TITLE
New particular map crashes

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#89]
KMST 1071 was released today. I wanted to check out a certain map, but it crashes the Map Render but the BGM continues to play even though the Map Render window is crashed and closed.

Map ID: 993063001

Error:

![t](https://cdn.discordapp.com/attachments/88992151643369472/467024589927481354/565.png)

**Comment by Kagamia** [comment]
annoying=x=

Is there any video recording or snapshots in game?

**Comment by Sunaries** [comment]
I’m afraid there isn’t yet.

**Comment by Sunaries** [comment]
Thanks, it works. 👍 

![t](https://cdn.discordapp.com/attachments/236180502200057856/468003062406184970/20180715123638978_993063001.png)
