### ISSUE TITLE
please add xml export function

### ISSUE THREAD

**Issue by monkeysax** [Kagamia/WzComparerR2#9]
WzComparerR2 has only img export plz add XML export funtion

**Comment by Kagamia** [comment]
Update~  see the latest commit.

**Comment by KENNYSOFT** [comment]
Updated code cannot be compiled. You should fix below part.
>//输出子节点
>foreach(var child in node.Nodes)
>{
>&nbsp;&nbsp;&nbsp;&nbsp;DumpNodeXml(writer, child);~~1~~
>}

**Comment by KENNYSOFT** [comment]
Updated code cannot be compiled. You should fix below part.

>**WzComparerR2/MainForm.cs:1584**
>
>//输出子节点
>foreach(var child in node.Nodes)
>{
>&nbsp;&nbsp;&nbsp;&nbsp;DumpNodeXml(writer, child);~~1~~
>}

**Comment by Kagamia** [comment]
Maybe a typo, already fixed :)
