### ISSUE TITLE
Background color character simulator

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#91]
Is it possible to add this feature similar to GIF extraction where you can pick your own background color? Right now you can only choose for transparency.
A black background suits better for animated images because you can see the effects and particles a lot better.

![](https://cdn.discordapp.com/attachments/88992151643369472/474671379770245132/avatar_sit_default_walk1.gif)

The above image looks good because the background color on Github is white, but on other platforms where the background color isn't white, the image looks terrible.

**Comment by Kagamia** [comment]
It supports bgColor at the moment.

**Comment by KENNYSOFT** [comment]
Yes, it supports bgColor, but only in main project's gif extraction. @Sunaries extracts that image from avatar plugin, and it uses GIF export function in WzComparerR2.Common project; a plugin project cannot use more beautiful exporting method which is implemented in main project. You can move these parts to common project... 😄

**Comment by Kagamia** [comment]
Yes, the settings of Gif Extraction is not designed for global using.
You could add your own setting groups into avatar plugin if necessary.
