### ISSUE TITLE
Avatar問題

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#93]
Character/TamingMob
1. ID 1932085.img
![1535016881744](https://user-images.githubusercontent.com/37591855/44518109-01627800-a6fc-11e8-8ec1-57faf853ee42.jpg)
![1535017143575](https://user-images.githubusercontent.com/37591855/44518110-01fb0e80-a6fc-11e8-9ebc-4509025b8922.jpg)
有部分騎寵的動作設定是錯誤的
例如翅膀常態顯示為`"sit"`
需要手動調整為`"fly"`才符合正常動作

2. ID 1983247.img
![1535018203397](https://user-images.githubusercontent.com/37591855/44518862-fa3c6980-a6fd-11e8-8084-fc1789d8955c.jpg)
![1535017200951](https://user-images.githubusercontent.com/37591855/44518259-63bb7880-a6fc-11e8-98e5-58afb9ea1af9.jpg)
有部分椅子圖層錯誤
z=`tamingMobFront`
z=`tamingNobRear`

3. ID 1932418.img
![1535018489506](https://user-images.githubusercontent.com/37591855/44519127-aaaa6d80-a6fe-11e8-8bdd-3c4381ddcea8.jpg)
.cs裡面有寫`forcingItem`但是不會顯示帽子
裝備也不會顯示

**Comment by Kagamia** [comment]
>> 1
好像这个骑宠没有规定具体的角色默认动作，也不知道是否有其他属性约定了这个动作。
我会想办法搜索一下和其他座驾的区别。

>> 2
emmm 感官上这样绘制好像没什么问题。。。怀疑是wz规定了`bodyhide`等其他属性。。等我回去调试一下。。。

>> 3

`forcingItem`在当前版本是一个确信不支持的属性..... 代码里只是简单过滤掉避免误读
