### ISSUE TITLE
skill數值錯誤

### ISSUE THREAD

**Issue by lowrt** [Kagamia/WzComparerR2#94]
- 42120011
![1535281136033](https://user-images.githubusercontent.com/37591855/44627559-95357d80-a962-11e8-803c-b9097e498d52.jpg)
![inked1535277317392_li](https://user-images.githubusercontent.com/37591855/44627564-a3839980-a962-11e8-9be1-1ebf742ebfd1.jpg)

`預覽圖跟遊戲中不符`

海外技改後，此問題已無問題了

**Comment by Kagamia** [comment]
奇怪。。也就是说这种描述中省略了`d(x)`函数符号么...
