### ISSUE TITLE
bodyAttack

### ISSUE THREAD

**Issue by Sunaries** [Kagamia/WzComparerR2#95]
```
if (!MobInfo.BodyAttack)
{
sbExt.Append("无触碰伤害 ");
```

Currently, the program doesn't read this variable correctly for me. The variable either has a 0 or 1 value assigned to it.
`bodyAttack 0` means the mob does not inflict touch damage.
`bodyAttack 1` means the mob inflicts touch damage.

If a mob has `bodyAttack 1`, it won't output the text at all for certain mobs...
**What can be added so that it will say "Body Attack" for 1 and "No Body Attack" for 0?** 

There are new variables that might be handy to add:
`ignoreDamage` = monster ignores damage inflicted (these monsters are added in the Black Mage update)
`fixedBodyAttackDamageR` = I believe this is % based touch damage

**Comment by Sunaries** [comment]
@Kagamia Ah, I see. I have a fix. When a mob did not have `bodyAttack` in the data, it would still show up.

**### Mob.cs:**
```
            this.FirstAttack = false;
            this.BodyAttack = -1;
            this.DamagedByMob = false;
```
this.BodyAttack = false; -> this.BodyAttack = -1;

`public bool BodyAttack { get; set; }` -> `public int BodyAttack { get; set; }`

`case "bodyAttack": mobInfo.BodyAttack = propNode.GetValueEx<int>(0) != 0; break;` -> `case "bodyAttack": mobInfo.BodyAttack = propNode.GetValueEx<int>(0); break;`

**### MobTooltipRenderer.cs**

```
if (!MobInfo.BodyAttack)
{
sbExt.Append("无触碰伤害 ");
```

↓

```            
            if (MobInfo.BodyAttack == 1)
            {
                sbExt.Append("[Touch Damage] ");
            }
            else if (MobInfo.BodyAttack == 0)
            {
                sbExt.Append("[No Touch Damage] ");
            }
```

**Comment by Kagamia** [comment]
`bodyAttack` not declared means `bodyAttack = 0` => `No Touch Damage' which someone has confirmed.
See https://github.com/Kagamia/WzComparerR2/commit/3fd81283926058b57a6d7a865d7283283879eb6f
