### ISSUE TITLE
MapRender无法显示地图背景（MapRender can't show  background）

### ISSUE THREAD

**Issue by SStar909** [Kagamia/WzComparerR2#96]
使用WzComparer2的MapRender，渲染的地图没有背景（显示为黑色）
When using MapRender of WzComparer2，the rendered map can't show background(background is black)
![image](https://user-images.githubusercontent.com/42778793/44735687-babbb600-ab1f-11e8-80f6-09d5551edc36.png)

**Comment by Kagamia** [comment]
Update to the latest version.

**Comment by SStar909** [comment]
I have downloaded these files，but how to use them for update?
![image](https://user-images.githubusercontent.com/42778793/44798576-73e3c400-abe4-11e8-8a88-b6db575b6794.png)
