### ISSUE TITLE
如何来更新WCr2

### ISSUE THREAD

**Issue by thisisjin** [Kagamia/WzComparerR2#97]
首页有看到作者写着release不会释出下载地址，但是软件的update直接导向的就是这里。。

所以跑来提issues了。 请问是通过何种方法来更新呢

**Comment by Kagamia** [comment]
1> 自行编译=w=
2> 下载他人预编译好的版本=w=
3> 有一个维护者的测试群会提供非正式的发布版=w=

很少正式发布release是因为bug太多了没修完不敢发 🤣

**Comment by thisisjin** [comment]
thanks~
