### ISSUE TITLE
WzComparaR2 How to store?

### ISSUE THREAD

**Issue by jerry87123** [Kagamia/WzComparerR2#99]
![default](https://user-images.githubusercontent.com/43235116/45478396-6d258700-b776-11e8-8d96-bd66da927375.PNG)

Unable to save?

**Comment by Dban1** [comment]
Yea, what I did was copy the code over from KENNYSOFT's version. Hopefully this can be added soon.

**Comment by jerry87123** [comment]
How do you store it now?

**Comment by jerry87123** [comment]
Is there a new way to store teaching?

**Comment by Dban1** [comment]
@Jerry87123 Actually you can just download Kennysoft’s branch of WzComparerR2 haha, it has the save option

**Comment by jerry87123** [comment]
Already found the answer Thank you~

**Comment by jerry87123** [comment]
Is there still a problem?

**Comment by jerry87123** [comment]
What do people and chairs do to be separated?
